### ISSUE TITLE
Handling global objects and suspension

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#1]
Hi
I’m not sure this is the right place but I’m trying anyway :-). I just want to share a problem I had when developing a Windows 8.1 app. Maybe I has attacking the problem in the wrong way, but I asked on StackOverflow (http://stackoverflow.com/questions/20846859/sharing-session-data-between-frames-and-support-load-restore-state) and never found a build in solution so I created one on my own.

I’ll try to rephrase my problem here. Imaging you are creating a game where everything runs locally. You have the following pages:
- Welcome page
- Game page (you navigate here from the Welcome page)
- Statistics page and Cheat page (you navigate to these from the Game page, and returning to game page).

The Welcome page is using a WelcomeViewModel. This view model could be recreated every time the page is loaded.

The Game page and the Statistics page is a GameEngineViewModel. These pages are using the same object. The statistics page is showing statistics of the current game.

The Cheat page is using a CheatViewModel. This view model should have a reference to the GameEngineViewModel.

My problem was how to share the GameEngineViewModel object on different pages. It was quite tricky because the state of this object needed be saved when the application was suspended. My CheatViewModel also needed to be saved when it was suspended. And when it was restored the reference to the GameEngineViewModel needed to be intact.

My solution was to add support for global objects in the SuspensionManager. Every global object needed to support the DataContract attribute. I’ve posted on StackOverflow how I did it. But in short I added methods to add, remove and get global objects (where every object was identified by an id). I also changed SuspensionManager to serialize and deserialize these objects when appropriate.

When this was I changed my pages and view models like this:
- When a game was started from the Welcome page, a GameEngineViewModel was created and added to global object list. The id of passed to the Game page that then got the right object from the global object list.
- When the Game page was closed the GameEngineViewModel was removed from the global list.
- When the Statistics page was loaded the same id was used as parameter and the page loaded the object from the global list.
- When the Cheat page was to be loaded a CheatViewModel was created and also added to the global list. The CheatViewModel didn’t have a direct reference to the GameEngineViewModel. Instead it was only aware of its id and was using that to get the right from the global list.

This is a big simplification from what I did. In real life it was a lot harder because I was also creating a WPF-application that was using the same viewmodels but that’s a different story :-).

But I hope you are getting my point. I think it would be great if there were some support in the template to handle objects that are shared between pages and where the state needs to be retained when the application is getting terminated.

I’m still not sure that I solved this in a good way, so if anyone has any other approach to share I’m more than willing to learn :-).

**Comment by JerryNixon** [comment]
First, thanks for the question.

Keep your life simple, don't use the Suspension Manager, just persist your view models to file whenever you hit a checkpoint. Is it when the user does something? Is it when you navigate to a new page? Only you can determine the correct checkpoints. You should use the OnNavigatedFrom in your view models to verify that you have saved your state, this is global insofar as the app-level deferral. This does not, however, give you more then the 5 seconds any app is allowed to suspend. 

To that end, the checkpoints help your app save more frequently along-the-way so you can be successful when you suspend. Having different view models as properties of another view model is a common practice and there is nothing wrong with that. It's also nice because your view model repository is easily reused because you are not creating something new. Moreover, it doesn't matter if this is a static singleton or not; this approach is universally the same for every app. 

Now, to your point. The template could share global objects in a lot of different ways, but I think you would be disappointed how it would be implemented. That's because the way App 1 (not your app) needs to share across is far more complicated than the way your app does, and so you have considerable overhead to use a "generic" solution than that simple implementation you are enjoying right now. What's wrong with creating a GlobalObjects class with a bunch of static properties? Nothing, and its elegance is in its simplicity. Do you need a template for that? No. 

That being said, I would be open to a pull request if you wanted to suggest something. But I recommend that unless you already have a universal solution in mind, that you take my advice and enjoy your own solution and let developers simply solve this themselves on a one-off basis.  //Jerry

**Comment by pekspro** [comment]
Thanks for answering :-).

I think you have some really good points (and the code you posted on StackOverflow was starting me thinking).

In my case I have relative small objects so the 5 seconds limit shouldn’t be a problem. So far that a generic solution will be fine. But a generic solution could clearly be misused so I’m not sure if that is an good idea after all .

Either way, I plan to port my app to Windows 10 in a while. Then I will have a deeper look on this.  

(Finally, I just want to thank for your videos on MVA – they are excellent :-)

**Comment by JerryNixon** [comment]
Cheers.
