### ISSUE TITLE
Navigating between pages which takes long time to load

### ISSUE THREAD

**Issue by MMalikKhan** [Windows-XAML/Template10#1010]
Hi @JerryNixon ,

I have a login page after which i am launching the Shell by using the below code. I am not sure what i am doing wrong, the home page loads but the page starts blank and then few elements comes and then other elements get populated. I wanted to delay the loading of the home page until my home page is fully loaded. On the `OnNavigationTo` has some code to get the database records and build a pivot. Its truly not the idea app behavior. could you please suggest me how i can implement this case .

Once the `NavigateTo(Typeof(Home))` is executed the focus is moved to the home page.. there is no `async` to wait until the page is fully loaded .. 

```
 // create a new frame 
 var nav = NavigationServiceFactory(backButton, ExistingContent.Exclude);

 // create modal root
 Window.Current.Content = new ModalDialog
 {
     DisableBackButtonWhenModal = true,
    Content = new Shell(nav),
    ModalContent = new Busy(),
};
nav.Navigate(typeof (Home), await GetHomePageParams(isNewUser),
    new SuppressNavigationTransitionInfo());
```

**Comment by mvermef** [comment]
are you using latest nuget?  Don't forget to verify changes to the app.xaml.cs file and shell file(s) since there have been rather large changes to the projects since the last release.  Nothing says you have use the NavigateTo method overrides either, you could use the Loaded event for the page... Where in your code do you call the initial navigate?

**Comment by JerryNixon** [comment]
Here's a reference https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Bootstrapper#root-frame
