### ISSUE TITLE
Unit Test App project doesn't work

### ISSUE THREAD

**Issue by SamuelLioult** [Windows-XAML/Template10#1028]
Hi,
I have an issue when I launch a unit test app project on a Hamburger (Template10) based project.
The error message is "Défaillance irrémédiable (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))" (sorry, error is in french)

And here is the stack trace:
   at Windows.UI.Xaml.Application..ctor()
   at Template10.Common.BootStrapper..ctor()
   at MyProject.App..ctor()
   at MyProjectUnitTests.MyProjectUnitTests_XamlTypeInfo.XamlTypeInfoProvider.get_OtherProviders()
   at MyProjectUnitTests.MyProjectUnitTests_XamlTypeInfo.XamlTypeInfoProvider.CheckOtherMetadataProvidersForName(String typeName)
   at MyProjectUnitTests.MyProjectUnitTests_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName)
   at MyProjectUnitTests.App.GetXamlType(String fullName)

I have not managed to solve the problem with the other post on the subject.
Also I tested a unit test app project on a project based on MS blank template, it's work fine.

Thanks
Samuel

**Comment by mvermef** [comment]
In app.xaml.cs do you have [Bindable] attribute decorating the App class?

**Comment by SamuelLioult** [comment]
Yes, but only in the project targeted by tests
In the last version of Hamburger Template, the app.xaml.cs class has already the [Bindable] attribute.

**Comment by mvermef** [comment]
you can only unit test the class libraries at present, unit testing with views will not work

[prism reference](https://github.com/PrismLibrary/Prism/issues/140) scroll to the bottom...

**Comment by SamuelLioult** [comment]
Hi @mvermef,

I try to run tests only on the class. I am in the start of my project, and actually I have only the views of the base hamburger template. I try to test my business logic.

**Comment by SamuelLioult** [comment]
Okay, so this problem appears only when I want to debug tests. If I run it using the Test menu and clicking "Run->All tests" it works well. But if I run tests clicking "Debug->All tests" it doesn't work (I have the error described in the first post of this topic).

**Comment by SandipAhluwalia** [comment]
Yes, I can also confirm the problem. Whenever debugging the unit tests, I see the same exception, but it works fine when just running it. We have some spent time trying to investigate and resolve this, but no success so far, so if anyone else out there has found a workaround or solution to this issue then please do share :)

**Comment by JerryNixon** [comment]
I'll see what I can do.

**Comment by nuwannnz** [comment]
I also have the same issue. Can't debug a unit test.Throws a Catastrophic failure exception . But can run them perfectly. Also the Visual Studio Test Explore becomes not responding after the exception and must restart Visual Studio.

**Comment by briandunnington** [comment]
Just to add some additional info: Although the Catastrophic Failure exception is thrown, it is not fatal. In fact, if you turn off 'Break when this exception type is user-unhandled', the unit test app will continue to run and the tests can be debugged as normal (and the test runner does not hang and can be re-ran without relaunching VS). Any code in the app-under-test's constructor does not get executed due to the exception, but this at least helped me debug some tests that were self-contained. Still not sure of the root cause (I know the Prism team said that UWP testing in this manner is not supported, but VS does support it and it works for apps that dont use a custom Application class, so there must be some way to get it to work).
