### ISSUE TITLE
BottomAppBar sample no longer works.

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1030]
Anyone care to figure it out?

**Comment by SWilkov** [comment]
Hi Jerry, I've just run BottomAppBar sample and can't see any errors? what error are you seeing?
Thanks

**Comment by dg2k** [comment]
@JerryNixon It fails due to Localization (or Globalization depending on how you look at it).

**NumberColorConverter** converter assumes a dollar $ sign in stripping the value string for parsing (to obtain Red or Green colors based on positive negative values) but if the currency sign changes with  regional setting it fails. PR #1041 fixes this.
