### ISSUE TITLE
ExtendedExecutionReason.Unspecified and BootStrapper.HandleSuspending()

### ISSUE THREAD

**Issue by borsliu** [Windows-XAML/Template10#1032]
I have a problem when using ExtendedExecutionReason.Unspecified with template10.

If I open an ExtendedExecutionSession with ExtendedExecutionReason.Unspecified, then click 'Close' button. Then, I found the only way to close this ExtendedExecutionSession is in the ExtendedExecutionSession.Revoked event. But, this event has racing problem with BootStrapper.Suspending event. In other words, I can not guarantee that this ExtendedExecutionSession is closed before BootStrapper.HandleSuspending(). If so, a "system exception" will be thrown when HandleSuspending() try to open an ExtendedExecutionSession  with ExtendedExecutionReason.SavingData. 

In ExtendedExecutionSession.Revoked, If I use
await Dispatcher.DispatchAsync(() =>
{
     if(args.Reason ==ExtendedExecutionRevokedReason.SystemPolicy )
     {
           CloseExtendedExecutionSession();
           ...Do UI things...
      }
}
Then, the "system exception" is always thrown.

**Comment by JerryNixon** [comment]
By default, Template 10 automatically enters every app into Extended Execution when it is suspending. This provides, as you know 10 minutes instead of 5 seconds, resources providing. I think your code might be in conflict with that T10 implementation. Don't you? It makes me realize that this needs to be optional, if so. But I want your feedback before I make any decisions here.

**Comment by borsliu** [comment]
Yes, this is the case. When I create an ExtendedExecutionSession with Unspecified reason. this behavior is unavoidable. If app's close button is clicked, I have no chance to close my ExtendedExecutionSession properly before BootStrapper.HandleSuspending().

I think, if BootStrapper.HandleSuspending() can be overriden, it will be good enough for my case.

**Comment by pnp0a03** [comment]
I have a similar issue with borsliu. My app using ExtendedExecutionReason.LocationTracking to track the location of the phone. In some cases, app trying to suspend without closing my EE session, then it cause the system exception.
I vote to "be optional" for using EE at BootStrapper.HandleSuspending. Because.. In many cases, 5 sec is enough for saving the app status. 
best regards, :)

`
System.Exception: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Windows.ApplicationModel.ExtendedExecution.ExtendedExecutionSession..ctor()
   at Template10.Common.BootStrapper.<HandleSuspending>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
`

**Comment by JerryNixon** [comment]
Will make it optional.

**Comment by JerryNixon** [comment]
Now you can set `BootStrapper.AutoExtendExecutionSession` to false;
