### ISSUE TITLE
NavigationServices.FirstOrDefault()

### ISSUE THREAD

**Issue by matsujirushi** [Windows-XAML/Template10#1067]
Compile error at NavigationService sample code in [wiki](https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Services).

`var nav = WindowWrapper.Current().NavigationServices.FirstOrDefault();`

Maybe...
`var nav = WindowWrapper.Current().NavigationServices[0];`

**Comment by JerryNixon** [comment]
This can only occur if there is no NavigationService. We've had discussions about this before. Since Template 10 was born as a Navigation framework, it simply makes no sense to accomodate a scenario without a NavigationService. That being said, the error is clearly Window.Current if there is an error, because FirstOrDefault does not result in an error. Since you said it was a compile error and not a runtime error (which is amzing to consider) you need to provide more information - or did it resolve itself?

**Comment by Opiumtm** [comment]
@matsujirushi 
[.FirstOrDefault()](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.firstordefault%28v=vs.110%29.aspx) is defined in `System.Linq` namespace.
It is failed to compile because namespace should be referenced.
Wiki example isn't a complete source file, it's just a few lines of code.
If you want to compile this example, you should reference `System.Linq` namespace by `using System.Linq;`.
