### ISSUE TITLE
10586, again

### ISSUE THREAD

**Issue by MikeBishop** [Windows-XAML/Template10#1094]
T10 seems to be working just fine on my project that targets 10586.  However, I notice that when I open the T10 sources on my VS15 install with the 10586 SDK, a pretty substantial list of the projects don't open and VS prompts me to go get the 10240 SDK.  When I up the targeted version for these projects, they open just fine, though I can't swear to overall functionality.

Is there a plan to bulk-retarget the samples, library, etc.?

**Comment by JerryNixon** [comment]
There is no plan to support VS15 until it is RTM later this year.

**Comment by MikeBishop** [comment]
I think there must be some confusion.  Visual Studio 2015 RTM'd in... 2015.  And has three updates, which have also RTM'd.

**Comment by darenm** [comment]
I think the confusion comes from the fact you referred to VS15, which is the name of the next version of Visual Studio that is currently in preview 3 https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx - certainly not your fault that Microsoft has come up with this naming convention.

**Comment by JerryNixon** [comment]
Let's all just agree, the current names of Visual Studio are confusing!
1. Visual Studio 2015 is version 14 (released in 2015) - we call it Visual Studio 2015
2. Visual Studio XXXX is version 15 (to be released in 2016) - we are calling it VS15

We 100% have plans to support Visual Studio 2015, Update 3. I want to share with you my experience recently. I open the Template 10 solution only for Visual Studio 2015 Update 2 to tell me I didn't have the UWP SDK installed. This is strange since I code UWP all day long and teach on it and write on it and... you get the idea. Instead of fighting it, I just installed Update 3, which was conveniently available that day. I reached out to the Visual Studio UWP experience PM and asked why I saw that. His answer was vague, but he did tell me several developers had already reported the anomaly. 

I say all that to say this. You might need to refresh Visual Studio. This is not likely T10.

**Comment by mvermef** [comment]
yea make sure you have 1.4 UWP SDK install associated w/Update3 and had **_some_** performance fixes.  control panel -> Programs and Files -> Visual Studio -> Modify, verify all things you want and 1.4 is checked.

What was really strange for me today was my DisplayPort not functioning!!!  Till I shut it off at 1030pm last night...
