### ISSUE TITLE
Could not resolve mscorlib for target framework '.NETCore,Version=v5.0'.

### ISSUE THREAD

**Issue by xiaoliwe** [Windows-XAML/Template10#1095]
Could not resolve mscorlib for target framework '.NETCore,Version=v5.0'.  This can happen if the target framework is not installed or if the framework moniker is incorrectly formatted.

**Comment by mvermef** [comment]
What is it you are trying to do? Can you post your project.json file? Gonna go with isn't a T10 issue, for now.  

I personally have had issues with getting RTM of asp.net core to work on my mobile dev box.  Could be related with Update 3, not sure yet.

**Comment by JerryNixon** [comment]
Closing because too little information.

**Comment by DanJ210** [comment]
I am getting this error after I created an app on App Studio, it's even published on the store. But when I download the source code, I have a Microsoft.Advertising.Universal SDK reference error. Right+Clicking to add a service reference gives me this same error code.

**Comment by mvermef** [comment]
How does this have anything to do with T10? And why post on a year old thread?

**Comment by DanJ210** [comment]
Because the same things may be used in the Templates for Windows 10 in App Studio boilplate creation. And not many searches come up relevant enough come up. It's the same exact error from a XAML template so maybe there was some insight into why that could be if there was an answer to why this same exact error was being caused. This year was the earliest year I could find.

**Comment by mvermef** [comment]
Don't think we can do much for you

**Comment by DanJ210** [comment]
I guess no one could have any idea why a template might cause this?
