### ISSUE TITLE
 Shell Page with ShellViewModel but no OnNavigatedToAsync fired.

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#1131]
I have an Global User Control which will displayed in  every page. So I set it in Shell Page.
The Shell Page with an ViewModel(ShellViewModel). But some methdos, like OnNavigatedToAsync, OnNavigateFromAsync etc, have never fired when start the app.

I need some functions from ViewModel, like PageStates. How can i do it in Shell Page like other pages navigated by hamburgermenu.

**Comment by JerryNixon** [comment]
I think you mean view-model.OnNavigatedTo() that is part of INavigable, right? If this is what you mean then you should know that these overrides are only called for view-models of pages, not all view models. For example MainPage+MainPageViewModel will have the view-model.OnNavigatedTo() called by the NavigationService. This is actually 90% of why we have a NavigationService. There is no mechanism to call it otherwise. If you need an event you can use NavigationService.Frame.Navigated;

**Comment by IIARROWS** [comment]
I added a view model (called "`FrameViewModel`") to the `Shell`view with an hamburger menu, so it is the DataContext of the `Shell` page.
I use this view model to centralize basic navigation command (like GoToSettings) and to manipulate the hamburger menu entries.
I want to store the menu entries when the application is suspending and restore them on restart, but the `OnNavigatedTo`and `OnNavigatedFrom`are never fired.

Have you any suggestion on how to achieve that?
At the moment I am thinking about moving the save and restore methods to the `App` class, but that would mean to change the menu management, considering that `FrameViewModel` is referenced by other VMs in order to add or remove menu entries.
I could do that, the only thing that's stopping me is that I think the `Shell` should respond to those events, because it's always and "active" page and I want to be sure it's the only, or best, option I have.

**Comment by JerryNixon** [comment]
I have tested this in a new Sample called MultipleViewModels and it works as expected. Perhaps you could take a look. I will close this issue myself if I don't hear back from you by Friday, @IIARROWS

**Comment by IIARROWS** [comment]
I'm sorry but don't see this sample.

**Comment by JerryNixon** [comment]
https://github.com/Windows-XAML/Template10/tree/master/Samples/MultiplePageHeaders My mistake @IIARROWS, It's called "page headers" not "view-models". I have view-models on my mind, I guess :)

**Comment by mvermef** [comment]
is OnInit preferred in this case, since it doesn't conform to current template CreateRootElement? Or does it matter?

**Comment by JerryNixon** [comment]
Thanks @mvermef you are right. There is no call because it is not in a Frame.

**Comment by IIARROWS** [comment]
Maybe OnInit could work, but what even should I use for storing the state on the app closing /suspending?

**Comment by IIARROWS** [comment]
Maybe OnInit could work, but what even should I use for storing the state on the app closing /suspending?

**Comment by IIARROWS** [comment]
Maybe OnInit could work, but what even should I use for storing the state on the app closing /suspending?

**Comment by IIARROWS** [comment]
Giving the new information, I'll just move the logic to an event handler of OnSuspending and OnResuming of the App.

In case anyone else encounters this issue, I think it's the best way to manage that kind of state changes.
