### ISSUE TITLE
[Bug] "Back" mobile navigation and HamburgerMenu

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#1140]
I noticed strange behaviour on Windows 10 Mobile with my hamburger template project. Steps:
1. Run project (phone or emulator)
2. Navigate to DetailsPage.
3. Navigate to MainPage with HamburgerButton from HamburgerMenu
4. Press "Back" buton.
5. Application does not go back to DetailsPage but terminate without exception!

I tested this on phone with Windows 10 Mobile Insider version and on emulators (10.10240 and 10.10586). Do you have this problem in your projects?

**Comment by dg2k** [comment]
Nothing odd and this is possible if page history is cleared by MainPage navigation. See a XAML excerpt for `<Controls:HamburgerMenu` shown below with `ClearHistory` set to `True`.

```
<Controls:HamburgerButtonInfo x:Name="LandingPage"
    ClearHistory="True"
    PageType="views:MainPage">
```

ClearHistory has its advantages to avoid _convoluted navigation_ (my own phraseology!) and start new navigation from top, but the downside is the app exits because navigation is cleared and it assumes a gate to exit it all. To overcome this (say, from user's perspective) I would intercept the `BootStrapper.BackRequested` event, check if the `PageType` is one with `ClearHistory` OR if navigation stack depth is zero and warn the user that the next back button will exit the app (you can use a nice dialog). I would navigate to the landing page (Home Page) to offer this dialog.

Alternatively, disable the `ClearHistory` (just remove the attribute as the default is `False`), and even then at some point of Back operation your app will exit when the navigation stack depth is zero (meaning Back to where it started).

**Comment by marcinmarkiewicz** [comment]
@dg2k Thanx a lot. It works! It`s not a bug. ClearHistory set to false works fine in my scenario.

**Comment by dg2k** [comment]
@marcinmarkiewicz 
Of course, not a BUG; it's by Design.
Please remove the string **[BUG]** from the title -- we now know this is not the case.

**Comment by JerryNixon** [comment]
You should really close your non-bugs
