### ISSUE TITLE
NullReferenceException in BindableBase.RaisePropertyChanged

### ISSUE THREAD

**Issue by cmpute** [Windows-XAML/Template10#1141]
In one of my test Project, I create a class inherited from BindableBase, and I set some of its properties in the constructor of MainPage, it throws a unhandled NullReferenceException from Template10Library.dll.
And when I use the source code of BindableBase to override the RaisePropertyChanged and check the exception, I found that it occurs at`var dispatcher = WindowWrapper.Current().Dispatcher;`
![catch](https://cloud.githubusercontent.com/assets/9154441/17076740/a12f8bec-50ec-11e6-8e10-27a13040a978.png)
When I test instantly, WindowWrapper.Current() returns null.
I wonder how this happened, and it seems better to use WindowWrapper.Current()?,Dispatcher

**Comment by JerryNixon** [comment]
When are you calling this? Is it in the constructor of App.xaml.cs?

**Comment by cmpute** [comment]
@JerryNixon In a thread started in the constructor of MainPage.xaml.cs And it just happen for few times, weird

**Comment by schuettecarsten** [comment]
@cmpute 
In a thread? Or in a task? Think about starting the task in OnNavigatedTo override.

@JerryNixon 
It should be possible to check for null here, but what should we do then? Call the handler and let the user handle the Thread change?

**Comment by cmpute** [comment]
@schuettecarsten In an async method called from the constructor. Sorry for replying so late

**Comment by JerryNixon** [comment]
This is not something we are going to fix. There is no reason any reasonable framework would support this scenario. From an OOP point of view, calling an async method from a synchronous constructor creates an unreliable state for both your application and the framework. This is most certainly a timing issue. That's because this type of operation in a class constructor falsely assumes the properties of the class have value, including properties like Dispatcher. As a matter of advice for you @cmpute I would recommend that you not do this, but instead set view-model properties in the OnNavigateTo override. And set other class's properties in a similar approach, even if you have to manufacture it. Async operations in a constructor do not allow constructing code to rely on the new class.

**Comment by cmpute** [comment]
@JerryNixon Yes, I indeed noticed that I should use async operation in OnNavigateTo or other methods, but as for a complete framework, I think it would be better to throw a new Exception when the property is not initialized in order to provide more information for developers who are not that experienced.
