### ISSUE TITLE
Template10 vs UWPCommunityToolkit

### ISSUE THREAD

**Issue by tibitoth** [Windows-XAML/Template10#1183]
Hi Guys!

In the UWPCommunityToolkit repo I ask a question https://github.com/Microsoft/UWPCommunityToolkit/issues/158 about Template10 collaboration. They said you are working with the toolkit's community to integrate it into Template10. Do you provide some more information about it, and do you need help to achieve this?

**Comment by JerryNixon** [comment]
Easy. Template 10 is the framework. The toolkit is just a bunch of UI controls. There's almost zero overlap except for the HamburgerMenu. If you are using Template 10 then the toolkit's HamburgerMenu will only be a frustration for you because it has very few features. Otherwise there's nothing uncompat between the two being in the same project. They have nothing MVVM or Navigation which is the core of Template 10 in my heart. Some of their controls are really terrific. Some of their services can really save a developer a lot of work. I might migrate some of Template 10's UI controls (except for Hamburger Menu) into the toolkit, depending on some things. Does this help?

**Comment by tibitoth** [comment]
That's sounds good. Thank you!
