### ISSUE TITLE
Can we have VisualState as a property in the ViewModelBase? #request #feature

### ISSUE THREAD

**Issue by Jebarson** [Windows-XAML/Template10#1184]
Its a pretty common need that we need the VisualState to be exposed in the view model. Currently I am achieving this via an intermediate ViewModelBase and have the property set from the UI on the visualstate setter. May be something to add on the next version?
# featurerequest

**Comment by JerryNixon** [comment]
This will never happen. This used to be more philosophical than technical, but as we are moving to portal Xamarin-compat interfaces, it becomes far more technical. Let me explain the philosophy, though. What belongs in code-behind? Logic around your view is what belongs in code-behind. Animations, complex-interactions, drag-and-drop, and (yes) visual states. That's because the code-behind is the logic of the view. The logic for what the user sees and does. What does not belong in the code-behind? Well, that's the logic around data and the logic around application flow. That's what a view-model is for. It is for taking care of data and flow. Your view-model should care less if your user is in portrait or landscape mode. So, 90% of the time there is nothing in your view-model that has anything to do with visual states. But what about the 10%? What do you do when the view-model knows the user is not logged in and you have a not-logged-in visual state? My initial preference is a property in your view-model and a listener (probably a data behavior) that changes the view state based on the INPC event. That's right, you have SOMETHING in your view-model that impacts visual state but you do NOT have anything explicitly related to the visual state in the view-model. You might have to just trust me on this one, but you want to keep this separation. Not because you want to make your view-model abstract or isolated. That's an okay reason, but the real reason is because it will make your design and your design maintenance easier - far easier.  I have seen developers raise events in their view-model and listen to those events in their code-behind (or you can use a behavior) and change visual states that way. That's a fine solution, too. The two solutions have this in common, the information is coming from the view-model, the visual state is not coming from the view-model. And then you might ask what if you have a property in your view-model called (string) "CurrentVisualState". I have seen this, too - and this is, generally, a bad idea. It's just crossing the line. It means you either have a literal string that must always sync wit the visual state or an enum that must sync. It's the recipe for trouble and it's not worth implementing this eventually painful pattern. And, lastly, why not have VisualState as a default visual-state property in Template 10? Because VisualStateGroups allow for sophisticated visual states in a view and it means more than one visual state could be active at one time. Creating a property would not only violate the portability and philosophy of the view-model, it would also impose considerable assumptions on the developer and designer. Consider visual state IsAdmin/IsNormalUser and IsEditing/IsViewing and IsPortrait/IsLandscape - you could easily have IsAdmin+IsViewing+IsLandscape all active at one time. I hope this makes sense to you.

**Comment by Jebarson** [comment]
Sorry wouldn't accept with that philosophy. There are situations where you need that. e.g.) you don't write your viewmodel based on the visual state (and may be you shouldn't). However, there are instances where you need your converter to be aware of that. And for a converter to know what the visual state is, there aren't plenty of options available, other than params (which aren't bindable) or having a dependency property injected into it.

As always for me, need comes before design.

**Comment by IIARROWS** [comment]
Well, nothing is preventing you from doing that.
But a library should be as simple and efficient as possible, evaluating general use cases before exceptions.
