### ISSUE TITLE
Documentation for NavButtonBehavior could be clearer

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1228]
I understand the principle of what this behavior is doing, but I'm struggling, specifically, to understand the Back behavior.
In normal use, wouldn't the Back behavior be to simply go to the previous Frame on the page stack? If that was the case, binding the Frame in the NavButtonBehavior would seem to be redundant, yet this is exactly what Template 10 does in PageHeader.xaml:

```
    <interactivity:Interaction.Behaviors>
        <behaviors:NavButtonBehavior Direction="Back" Frame="{Binding Frame, RelativeSource={RelativeSource Mode=TemplatedParent}}" />
    </interactivity:Interaction.Behaviors>
```

It isn't clear to me if that use of NavButtonBehavior does, indeed, go back to the previous frame on the stack or if it is doing something else! If it is doing something else, it could be useful to document what it is doing and how it works.

**Comment by JerryNixon** [comment]
This behavior is intended for changing the behavior of the back button through declarative XAML. The validation sample demonstrates this. If you have a popup and you want to include a CLOSE button then this behavior can do just that through declarative XAML. You can set `Handled` to true and it will ensure the back navigation does not execute. Since you seem to be playing with it, perhaps you could enhance the documentation for the next developer.
