### ISSUE TITLE
Seperation of T10 library into separate Nuget packages

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#1233]
As discussed in #684, it would be better to split T10 2.0.0 into separate Nuget libraries, allowing developers to pick and choose what functionality to have included. 
# Package Lists
## Existing Nuget packages
- Template10.Validation
## Yet to be created
- Template10.Interfaces
- Template10.App
- Template10.App.Android
- Template10.App.iOS
- Template10.Mvvm
- Template10.Utilities
- Template10.Xaml.Controls
- Template10.Xaml.Converters
- Template10.Xaml.Behaviors
- Template10.Xaml.AttachedProperties

**Comment by tibitoth** [comment]
Could you indicate the scope or the purpose of each package in some sentence?

**Comment by JerryNixon** [comment]
Template10.App will include the BootStrapper and the NavigationService. This will necessarily require MVVM, which we can't put elsewhere - in part because I do NOT want Template10 to be mistaken for an MVVM framework. That being said, INav and all the other interfaces should be moved to Template10.Interfaces, though I am not certain that is a separate package. The goal with Template10.App is to distill Template10 down to the basic framework it is, and no other controls or helpers or behaviors or freaking anything. Then we create the ones for the rest. The end goal is that Template10.App becomes the golden package that represents the core of Template10 and the other packages are subject to outside influences like the Community Toolkit, et al. Returning, in a way, to where Template 10 started - Prism. That being said, there are aspects of Prism for UWP that might need to be considered before we settle on how v2 of T10 looks in T10.App. Anyway, that's me thinking out loud. App is the most important package here, and we need to invest into Prism - potentially making Prism.Core a built-in dependency to Template 10 (up for investigation first). Some consult from @brianlagunas will make sense here, too.

**Comment by darenm** [comment]
I would certainly vote for aligning on a single core implementation and closer alignment to Prism. As @JerryNixon notes - the p&p variation of Prism was the inspiration for what became T10, and that effort was primarily expended because the p&p (patterns and practices) team were no longer planning to maintain Prism. 

Of course, as often happens, after the p&p announcement, multiple people spotted the need for a foundational framework to accelerate app development - we collaborated on what became T10 (essentially collecting services and patterns we used to build a non-trivial sample app for a MVA) and @brianlagunas revived Prism. Had Prism been first, I'd have certainly been contributing there.

The current sum of what has become T10 feels a little too heavy and overly opinionated in it's current incarnation, despite the best intentions to the contrary. Breaking T10 into these packages makes a lot of sense to me as long as we can manage and constraint the package inter-dependencies well - we don't gain much if to use Template10.PackageX we inherit dependencies on every other. :)

**Comment by callummoffat** [comment]
I totally agree. If Template 10 was built to replace Prism (which was revived), it would make sense to reintegrate as much of that framework code as possible. It's no use having two different frameworks that perform the same function. If Prism provides the stuff we need, we can use that, rather than bloat the framework.

Also, I totally agree on constraining inter-dependencies. Where possible, it would probably be wise to depend only on the core packages. Keeps it clean, although that won't be possible.

I do think, however, that we should provide "meta-packages" (i.e. Nuget packages which serve no function other than to download parts of T10) for beginners.

**Comment by brianlagunas** [comment]
@JerryNixon we should have a chat about the common goals that Prism and Template10 are trying to achieve.  Prism will soon be revamping its UWP guidance.  Since I am slowing down on Prism for Xamarin.Forms, I'll have more time to put towards UWP.
