### ISSUE TITLE
Template 10 : Cross-platform support

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#1234]
As discussed in #684, Template 10 should be cross-platform (with support for Xamarin). As much of it as possible should be cross-platform.

**Comment by akshay2000** [comment]
This issue seems too broad at first glance. Let's try to zero down into the problem. What components of Template10 need to be cross platform? First and foremost, ViewModels. Those aren't portable because NavigationService and it's friends rely on UWP specific classes. To remedy this, we need to make interfaces abstract enough so that they do not rely on platform specific code. Currently, I have a working solution but requires implementing `INavigable` on each individual ViewModel explicitly. This results in a lot of repeated code like [this example.](https://github.com/akshay2000/MonocleGiraffe/blob/xamarin-rework/MonocleGiraffe/MonocleGiraffe/ViewModels/BrowserPageViewModel.cs).
Let's start with following rough checklist of what needs to be done. We can start working once @JerryNixon approves of the design.
- [ ] Restructure `INavigable` to make it PCL compatible.
- [ ] Restructure `INavigationService` to make it PCL compatible.
- [ ] Supply platform dependent implementations of the interfaces above. This is important to avoid creating bridges between different navigation interfaces (for example, MVVMLight navigation service + T10 interface). All platforms can stick to using the T10 implementation.
- [ ] Supply platform dependent ViewModelBase implementation to make use of platform specific state management, etc.
- [ ] Make `IStateItems` platform independent. I think the interface and it's implementation both already are PCL compatible. We just need to integrate them in VMs in platform agnostic way.

Let me know if I missed something.

**Comment by JerryNixon** [comment]
Very good

**Comment by syaifulnizamyahya** [comment]
Are there any plans for cross platform support? If there is, any eta?

**Comment by akshay2000** [comment]
@syaifulnizamyahya I think #1444 should answer your question.
