### ISSUE TITLE
Adjustable hamburger buttons single choice issue

### ISSUE THREAD

**Issue by callMeJohn96** [Windows-XAML/Template10#1247]
I'm trying to use an ObservableCollection to add the buttons through C#. 
Here is how I add them:

```
           `var button = new HamburgerButtonInfo();
            button.ClearHistory = true;
            button.NavigationTransitionInfo = new Windows.UI.Xaml.Media.Animation.SuppressNavigationTransitionInfo();
            button.PageType = typeof(RandomPage);
            button.PageParameter = Informations;
            button.Content = "Content of CollectionItem";
            MyHamburgerMenu.PrimaryButtons.Add(button);`
```

Everything works but when I'm trying to select a button of the menu after I've selected another one, the last one doesn't get unselected and in result I can't reselect it. Any ideas?

**Comment by JerryNixon** [comment]
Buttons are uniquely identified by a combination of their PageType and PageParameter properties. If your two buttons share the same PageType + Param then they cannot be differentiated.

**Comment by callMeJohn96** [comment]
I see...but I want all the buttons to lead to the same page but each containing a different list of objects...Is it possible to configure this?

**Comment by JerryNixon** [comment]
Yes, just create the uniqueness by passing in a different parameter, even if the receiving page does not use the incoming parameter. Use it to differentiate the buttons that way. Think about it, how does the Hamburger menu know what button to highlight otherwise? Imagine you click a Ham button and it highlights the one you clicked. Fine. Then imagine you use the back button either on your device or in the app, you def want to the Ham menu to highlight the newly navigated to page, right? But how does it know the page to which you have navigated? There is no page name, there is only page type and parameter. So the Ham menu is working perfectly, you see. And you can use it the way it is just by differentiating with a parameter. I hope this makes sense. Thanks for using Template 10.

**Comment by callMeJohn96** [comment]
it's actually a very good idea... solved my problem... thanks :)
