### ISSUE TITLE
ChangeTypeConverter does not handle URIs

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#1259]
Looks like URIs are a limitation of the converter in the present form.  solution for this is not clean with existing code (as nice as the converter is 👍 ).  Since there is no direct conversion from string to URI (since this is how this came about), it would require either some hackish code or a different converter which would you prefer?

**Comment by JerryNixon** [comment]
The converter is limited to types from/to which can actually be cast. I think it should have been called the CastTypeConverter. Because of this, I hope you can see why string to URI can never work. And, I hope you can see why this is not a bug in the behavior. That being said, writing a small handler in the converter to handle this explicit conversion would be an okay solution, I think.

**Comment by mvermef** [comment]
Ok :)
