### ISSUE TITLE
HamburgerMenu + PageHeader+ CustomTitleBar animation problem

### ISSUE THREAD

**Issue by alesdvorakcz** [Windows-XAML/Template10#1275]
Hi,
When I use same custom color for these controls, there is weird transition animation. It would be nice if the PageHeader component stay at the place. Is there any way how to do it?

PS: I really love Template10. Its pretty awesome ;-)

**Comment by JerryNixon** [comment]
Hi. Thanks. Yes, this is very simple to accomplish. The reason you see the animation is because Template 10 applies the default Page Transition animation when you navigate. You can suppress this animation, but that's not really what you are asking. What you want is for the animation not to cause the Command Bar to move but still apply the animation to the rest of the page content. Right? This is somewhat common of a request, to be honest and I am going to add this to the templates so future developers can see the implementation. That being said, to help you now, I want you to read about the [EntranceNavigationTransitionInfo.IsTargetElement](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.media.animation.entrancenavigationtransitioninfo.istargetelement) attached property. Applying this to the content of your page but NOT the Page Header will cause the content to animate without animating the Page Header. It's that simple and I'm glad you brought it up so I can add it to the default templates.

**Comment by alesdvorakcz** [comment]
Thank you, it is exactly what I needed.
