### ISSUE TITLE
Adding a ButtonType=Literal to HamburgerButtonInfo breaks theme changing

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#1285]
T10 1.1.12. When I add HamburgerButtonInfo to HamburgerMenu, set Literal type to it and add some children elements for example StackPanel with TextBlock and trying to change theme there is exception in AppTheme property's setter of SettingsService - in RefreshStyles method. (An exception of type 'System.InvalidOperationException' occurred in Template10Library.dll but was not handled in user code Additional information: Sequence contains no matching element). Bug?

**Comment by JerryNixon** [comment]
Not sure, can you set it manually in the element?

**Comment by Gabsch** [comment]
Same problem for me. This happens even in a new created Hamburger template when any buttons ButtonType is set to Literal (right at the button in XAML).

EDIT:
When no symbol icon is set, but a button you will get a NullReferenceException instead.

**Comment by swisszeni** [comment]
Just encountered the same problem. V 1.1.12
As described above, can repo with a fresh template.

Edit:
Ok found the Bug. It is caused by [this](https://github.com/Windows-XAML/Template10/blob/0c3b9f54c186548a576e80771583fd5d909f8e38/Template10%20(Library)/Controls/HamburgerMenu.xaml.cs#L790) line in HamburgerMenu.xaml.cs looking for RootGrid.
`var child = children.OfType<Grid>().First(x => x.Name == "RootGrid");`

But according to the DataTemplate for `ButtonType=Literal` (found [here](https://github.com/Windows-XAML/Template10/blob/c2910a30af71425c58c67815fc74409272d1a34f/Template10%20(Library)/Controls/HamburgerMenu.xaml#L83-L95)) there is no RootGrid specified and thus the LINQ fails.

@JerryNixon file as Bug?
