### ISSUE TITLE
Change log summary for 1.19?

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1299]
Is there a change log document that simply states what changed from 1.18 to 1.19, without having to dig through git commits?

**Comment by JerryNixon** [comment]
Let me try to do it off the top of my head since they had not been updated since March and there's no reliable record since then of changes ONLY to the templates. 

Two changes to project.json: 
1. Now defaults to NetCore 5.2.2 
2. Now defaults to Template 10 1.1.12

Three changes to XAML
1. Added "Custom" area to app.xaml
2. Added "CreateRootElement" to app.xaml.cs in Hamburger Template
3. Added EntranceNavigationTransitionInfo.IsTargetElement="True" to all views
