### ISSUE TITLE
Navigation refresh throws JsonReaderException

### ISSUE THREAD

**Issue by KristofferBerge** [Windows-XAML/Template10#1304]
"Unexpected character encountered while parsing value: e. Path '', line 0, position 0."

I'm trying to refresh a view. Refreshing with no arguments gives me an empty view, but when passing the proper argument i get a JsonReaderException. The same object is fine when navigating to a new instance of the same view. The OnNavigatedToAsync is not reached before the exeption is thrown.
Running on .net core version 5.2.2

```
var nav = WindowWrapper.Current().NavigationServices.FirstOrDefault();
//Throws exception
nav.Refresh(someObject);
//Works fine
nav.Navigate(typeof(Views.myView), someObject);
```

**Comment by mvermef** [comment]
Which json provider are you using? My guess is improper or malformed data.  Possible and I have had it happen, extra apostrophes

**Comment by KristofferBerge** [comment]
The exception is thrown by "Newtonsoft.Json.JsonTextReader.ParseValue()". I'm passing a normal object from C# (not json) so i don't know if i can prevent improper data.  I have no aphostrophes in any fields. Why isn't the navigate method throwing the same exception when provided with the same data?

**Comment by tibitoth** [comment]
The problem is that the `NavigationService.Refresh()` method doesn't serialize the given parameter, but the `Navigate()` does.
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L340
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L211

Currently you need to serialize the parameter by hand like this:

``` csharp
NavigationService.Refresh(SerializationService.Json.Serialize(someObject));
```

I think we need to add serialization into the `Refresh()` too.

**Comment by mvermef** [comment]
Missed that little bit, hope that works, should be an overload then imo

**Comment by JerryNixon** [comment]
In 1.1.13 NavigationService.SerializationService will be read/write so you can customize it. That being said, Refresh() will no longer require a serializable parameter since you will have already navigated with one. I have made the changes and updated the NavgationService in the branch and will merge next week, planning to push 1.1.13 next week to NuGet, too.

**Comment by JerryNixon** [comment]
That being said, I think Refresh(param) is a mistake.
