### ISSUE TITLE
Template10 throws exception on launch when my phone is set to High Contrast

### ISSUE THREAD

**Issue by prajjwaldimri** [Windows-XAML/Template10#1318]
Only happens when the color scheme is set to High Contrast.
Here are the details of the exception: 

Exception: 
> {"Object reference not set to an instance of an object."}

StackTrace:
> at Template10.Controls.HamburgerMenu.UpdateFullScreen(Nullable`1 manual)\r\n   at Template10.Controls.HamburgerMenu.UpdateControl(Nullable`1 manualFullScreen)\r\n   at Template10.Controls.HamburgerMenu.HamburgerMenu_Loaded(Object sender, RoutedEventArgs args)"

This even happens on newly created app using Template10's templates in VS.

I am using VS 2015 for the development and the min and max version of the targeted OS are both set to Windows Anniversary Update.

**Comment by JerryNixon** [comment]
I will have to investigate that. Does it happen on Desktop, too? If not, what build of Mobile?

**Comment by prajjwaldimri** [comment]
Crashes on desktop too. 

Desktop build: 14393.447
Mobile build: 10.0.14393.448

**Comment by JerryNixon** [comment]
I have not forgotten you. Just not gotten around to fixing this yet. Still on the list.

**Comment by prajjwaldimri** [comment]
No Problem 👍

**Comment by PrefabErik** [comment]
I ran into the same problem using the Template10 Hamburger template.
I've downloaded the Template10 code, ran the debugger on the Hamburger template code and found that there's a problem with the defined brushes in the default Custom.xaml HighContrast resource dictionary.

The brushes for the HamburgerMenu control in HightContrast are assigned a SystemColor instead of a brush. This will cause all the defined brushes of the control to be set to null in the constructor by the InitializeComponent method.
Later on, the UpdateFullScreen method is called where the Opacity of the HamburgerBackground is set, but set to null this will throw a NullReferenceException.

So, changing the defined colors to brushes will fix the problem.

**Comment by PrefabErik** [comment]
As a side note, there's another issue with the default Custom.xaml.
It uses style setters inside the ThemeDictionaries, the problem with that is if the user changes the light/dark setting on the Settings page it will not update the color scheme of the controls.
The app has to be restarted to reflect the change.

A better way is to define brushes (or other properties) with a unique name and assign that brush in every theme. Then outside the ThemeDictionaries use the style setters to set the brushes of the controls once and refer to the unique brush names as a ThemeResource.
This way if the user changes the light/dark theme it will update the color scheme immediately.
