### ISSUE TITLE
New View always created?

### ISSUE THREAD

**Issue by RomeoPavoni** [Windows-XAML/Template10#132]
Adopting Template10 in my main app i realize the Loaded event of the main page is always fired when his button on the Hamburger Menu is clicked, it seems a new view is created for every click on the Hamburger Menu button firing his constructor.

Is this an expected behavior and is there a way to avoid it?

**Comment by JerryNixon** [comment]
This is the expected behavior. Because the Hamburger Menu doesn't do anything but host the Frame, what you are seeing is the behavior of the XAML Frame. That is to say, the Frame navigates to a type and not to an instance. The result is that each time you go to a page it is created. 

> https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.page.navigationcachemode.aspx

UNLESS you change the NavigationCacheMode which allows you to cache the instance and reuse that instance the next time. That being said, you can expect the OnNavigatedTo to be called in both the view and the view-model by the Template 10 framework. Determining if your current call is an instantiation or a reuse can be as simple as setting a field value and looking for it.

Warning. Read how the cache mode works. In some cases you will not reuse the view you think you would otherwise have reused because of memory constraints. This scenario is pretty rare and occurs mostly in low-end phones.

**Comment by lyling** [comment]
When I should know the view is from cache in my viewmodel ? In OnNavigateTo method, every time I click the hambergermenu though NavigationCacheMode is Enabled.
