### ISSUE TITLE
[Question] Color addon darken/lighten are internal (ColorUtils)

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1333]
Why are the methods internal and not public? If I want to use these methods, this is not possible due to the internal limitation. https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Utils/ColorUtils.cs#L15

**Comment by JerryNixon** [comment]
Because they don't work properly.

**Comment by JerryNixon** [comment]
They work *just* enough for the HamburgerMenu, their only consumer.

**Comment by JerryNixon** [comment]
What we need to write is a ColorService in Services.

**Comment by JerryNixon** [comment]
There *is* a ColorService in Services, by the way.

**Comment by JerryNixon** [comment]
I tested it when I wrote it years ago. But haven't looked at it in a long time.

**Comment by JerryNixon** [comment]
Find it here: https://github.com/Windows-XAML/Template10/tree/master/Template10%20(Services)/ColorService

**Comment by JerryNixon** [comment]
As a reminder, a Helper is a kind of class that could be copied and pasted into any class without change. That's because a helper is a wrapper of code in a generic way. A Service, on the other hand, might not work in some projects and might need to be rewritten. Services are specific to the scenarios and often expose only small portions of the Helper, according to the needs of the app. The interface is for the Service, not the Helper. The interface helps you in mocking both designtime and test data.

**Comment by jp-weber** [comment]
Thank you for your explanation. I remember that I have looked into ColorService long time ago and had not seen an "Color" addon with darken/lighten methods or similar function in the class. So I have used in my fork the ColorUtils class where I had set all methods to public.

But I wonder, that ColorUtils is the only class in Utils folder where the methods are set to internal.

Would you consider it for good if we extend the ColorService to these functions or add other methods to manipulate the color?

**Comment by JerryNixon** [comment]
Yeah, probably. :)
