### ISSUE TITLE
CatastrophicFailure in NavigationService.ClearCache

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#1335]
Sometimes, a CatastrophicFailure (0x8000FFFF) is thrown in NavigationService.ClearCache. I can see customer reports on this, but cannot reproduce this issue on my devices.

**Comment by JerryNixon** [comment]
What to do what to do. The method is a little mysterious to me, to be honest. What's the goal of the method? Re/un-setting the cache to delete what's there?

````
public void ClearCache(bool removeCachedPagesInBackStack = false)
{
    DebugWrite($"Frame: {FrameId}");

    int currentSize = _Frame.CacheSize;

    if (removeCachedPagesInBackStack)
    {
        _Frame.CacheSize = 0;
    }
    else
    {
        if (_Frame.BackStackDepth == 0)
        {
            _Frame.CacheSize = 1;
        }
        else
        {
            _Frame.CacheSize = _Frame.BackStackDepth;
        }
    }

    _Frame.CacheSize = currentSize;
}
````

**Comment by schuettecarsten** [comment]
Exactly. The page cache cannot be flushed directly, so it has to be set to 0 and then set back to the original size.

**Comment by JerryNixon** [comment]
But you get a catastrophic error?

**Comment by schuettecarsten** [comment]
Yes, when setting the CacheSize to 0. Looks like this sometimes fails for unknown reasons. I do not get the failure myself, but we use HockeyApp and can see several crashes at our customers.

**Comment by JerryNixon** [comment]
Would it help to wrap it in a try/catch block for the sake of HockeyApp?

**Comment by schuettecarsten** [comment]
Yes, that should help as a workaround. I will add a PR for this.

**Comment by NicoTiing** [comment]
@schuettecarsten 

I dont know if this will help or related to the issue
but in my scenario , I enabled NavigationCacheMode on my second page so when navigated to third page then go back all datas are still in there , but when go back to first page , needs it to be disabled , I tried that ClearCache method but still having problem on that

I just add this on my OnNavigatingFrom method of my secondpage:
`if (e.NavigationMode == NavigationMode.Back) {
                this.NavigationCacheMode = NavigationCacheMode.Disabled;
            }`
never encountered that CatastrophicFailure again

so try disbaling navigationcachemode instead of ClearCache
