### ISSUE TITLE
PageHeader PrimaryCommands Styling problem

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1337]
The default background of the `PageHeader` is "dark" so the `Text`/`Content` must be "light" in this case, white.
But the default foreground of the `PrimaryCommands` is black. If i change the `RequestedTheme` of the `PrimaryCommands `to Dark, everything goes fine until you change the window's `Width `that some of the `PrimaryCommands `slip into the ellipsis drawer. Now, I cannot see the text of the command because it is white on light background. Is there something i should be doing to get the style correct? Thanks!

**Comment by JerryNixon** [comment]
There is a bug with the CommandBar control that the PageHeader sub-classes. For reasons I don't know, the RequestedTheme doesn't seem to propagate to the child commands. You can solve this by setting RequestedTheme on each item, but it's a nuisance. I know. I can't fix it with the PageHeader because it has to remain dynamic depending on how you plan to change it in your app.
