### ISSUE TITLE
How to make visible the MainMenu only after a successful login ?

### ISSUE THREAD

**Issue by zakkar1** [Windows-XAML/Template10#1342]
Hi ,
In the MainPage of the Template I want to display the main menu of my app ONLY if the user has logged in successfully into the system I'm trying to make it happen with no success so far.
So what I did was.
I went to the MainPageViewModel in the OnNavigatedToAsync method.
I wrote the below code.

  Controls.LoginPart MyLogin = new Controls.LoginPart();
            MyLogin = Controls.LoginPart.MyLogin;
            if (MyLogin == null) MyLogin = new Controls.LoginPart();
            
            Models.UserCredentials MyCredentials = new Models.UserCredentials();
            MyCredentials = MyLogin.UserCredentials;
            if (MyCredentials == null) MyCredentials = new Models.UserCredentials();
            Views.Shell MyModal = Views.Shell.Instance;
         
            if (string.IsNullOrEmpty(MyCredentials.UserName))
            {
                MyModal.LoginTapped(null, null);

            }

The above code when the app is running it opens directly the Login Screen . The same screen like the Template has.
I have placed a Listview in the MainPage which is invisible.
Now that my Login popup is open what code do I need to write and WHERE in order to make the listview in my MainPage to appear ?
In the Loaded event of the MainPage I have already populated the listview items but I have made the Listview invisible.
Is there any code and how am I suppose to do that in the LoginPart.cs to write and make the listview in the MainPage Visible ?
I have tried the below but with no success

In the MainPage.XAML.cs I have the below

   public void MakeVisible()
        {
            this.itemListView.Visibility = Windows.UI.Xaml.Visibility.Visible;

        }

Which I call from the LoginPart userControl. Which is not working.
 Views.MainPage MyMainPage = new Views.MainPage();
            MyMainPage = Views.MainPage.MyMainPage;
            MyMainPage.MakeVisible();
           
            LoggedIn?.Invoke(this, EventArgs.Empty);

Any ideas on how to open the login screen when my app starts and ONLY if the user has logged in to display the menu ?

Appreciate your help on this.

**Comment by dg2k** [comment]
Put your login control in Shell.xaml with ModalDialog as a container (i.e., ModalDialog is in Shell.xaml and it contains the login control)

- Make ModalDialog to startup with its IsModal property true. I would use binding to a property for **IsModal**  but your choice.
- When authentication is done successfully, negate **IsModal** (possibly via binding) and the user will now find the MainPage which is waiting behind the ModalDialog.
- Yes, you can subscribe to LoggedIn event in Shell.xaml.cs to signal authentication and negate IsModal.

**Comment by zakkar1** [comment]
Hi dg2k ,
So far I am able when the app starts to open the modal lofin window. I can do that.
I have two options here.
1.Pre populate the Items in the Main page (I have done it in the Loaded event)  and remove the close buttons from the login screen so the user must definitely pass the authentication.

2. Or which this is the Option that I prefer , after the successful login to "tell" somehow to the MainPage that you are OK now so Fill the Listview with data.

The second option I'm trying to accomplish. How can I notify the MainPage that something is changed so start filing the Listview and display the Items on screen.

Is there any way to tell the MainPage that now Display the items ? Make for example the Listview visible.
I wrote in the MainPage.XAML.cs a public void  which I call from the login screen but the Listview still remains invisible.

public void MakeVisible()
{
this.itemListView.Visibility = Windows.UI.Xaml.Visibility.Visible;
    }

Any ideas ?

**Comment by dg2k** [comment]
Between subscribing to an event (say, that of LoginPart and/or your own custom event creation) and [RegisterPropertyChangedCallback](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.dependencypropertychangedcallback), you can easily make Shell, LoginPart UserControl and MainPage (view or view-model) to work together as you desire.

**Comment by zakkar1** [comment]
Do you have an example because I 'm not sure that I understand what you 're saying ?
Where should I need to write and what ?

**Comment by dg2k** [comment]
I cannot offer a ready-made example that fits your requirement but here is a concept you can implement.
- First, can you get the LoginPart control to work from Shell.xaml? There is enough sample on this already.
- Shell.xaml.cs can subscribe to LoginPart's LoggedIn event and now you should be able to implement a ModalDialog login because LoggedIn event will be used to change IsModal property.
- Let assume that IsModal is bound to a DP in Shell.xaml.cs, and call this **IsAuthenticated** bool DP.
- As an illustrative example, in MainPage view or view-model, register PropertyChanged callback for **IsAuthenticated**  (which is now Views.Shell.Current.IsAuthenticated) by using  Views.Shell.Current.IsAuthenticated.RegisterPropertyChangedCallback(...) so that MainPage view or view-model can listen to IsAuthenticated property change. Now you detect authentication in MainPage with DP in Shell that is bound to the LoginPart UserControl. Sounds complicated but it's okay. There are more elegant solutions (but at added complexity) such as avoiding dependence on Views.Shell.Current. but won't go there.

Hope this helps. Beyond this, I'm afraid Bing and Google are your best friends as numerous examples/samples/ideas can be found elsewhere, for instance on [stackoverflow site](http://stackoverflow.com/search?q=template+10/).

**Comment by JerryNixon** [comment]
Just think about your login page as the main page and navigate there first. After a successful authentication you can navigate to your real main page. This will give you what you want.

**Comment by zakkar1** [comment]
Hi Jerry,dg2k ,
Yes it worked. I'm Navigating to LoginPart First and after the login to the MainPage.
 Thank you for your Help and you useful adviceHi Jerry,dg2k ,
