### ISSUE TITLE
PageHeader in Narrow State covers Hamburger when Ellipsis is clicked

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1349]
When I resize my app's window to `**Narrow** `state and click the ellipsis, the `PageHeader `covers the `HamburgerMenu`. But when it is in `Normal `or `Wide `state, opening the Ellipsis works just as before. Is this the intended behavior? I just noticed this last night.

**Comment by JerryNixon** [comment]
Does this occur with a new hamburger project?

**Comment by ghost** [comment]
will check it.

**Comment by ghost** [comment]
@JerryNixon yes, it also happens in a new hamburger project. When you resize the window to Narrow state and click the ellipsis, the PageHeader hides the Hamburger button.

**Comment by JerryNixon** [comment]
Trying to understand why this is not occurring when I try it.

**Comment by erossetto** [comment]
@JerryNixon: I can reproduce this behavior as well, let me know if you need help with a repro.

**Comment by michaelhutchful** [comment]
I have a simillar issue, but with Bottom.Appbar. If I use it on a page level, it covers the hamburger menu. it is fine when I add it to the shell. But using the Bottom.Appbar in the shell is way too much work. Are there any ways to make the hamburger the furthest item?

**Comment by swisszeni** [comment]
## Analysis
This seems to be a behavior of CommandBar. As soon as the SecondaryCommands are expanded, it renders above other UI elements. Don't know if this is intended or not, but it is annoying for sure.

## Repo code
[Repo gist](https://gist.github.com/swisszeni/9784f0729fe94c2ecfed5b7b7a71ff9e)

## Proposed fix
Instead of using a spacer in the PageHeader, that shifts the headers content 48px to the right when in inline or overlay state, alter the margin of the PageHeader. This way the HamburgerButton isn't on top but on the left of the PageHeader and thus doesn't get hidden.
