### ISSUE TITLE
Hamburger template with MvvmLight

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Windows-XAML/Template10#1366]
It would be nice if someone could do a MvvmLight Hamburger template for Template10. Im in the middle of development when I realize, MvvmLight could be of help. 

I tried integrating MvvmLight with vanilla Hamburger template. So far it was unsuccessfull. Theres a lot I need to learn (MvvmLight, Template10) before I would be able to pull that off.

Thanks.

**Comment by Pinox** [comment]
Agree , many Xamarin sample projects use MVVM light and it would be great to see that working with using portable viewmodels in template10. Have been waiting ages for this on template 10, don't have the skill set todo it myself. Would really be helpful for novices.

Seriously thinking of using native development in Xamarin projects on the UWP side  instead of Xamarin Forms for UWP.  If someone would be so kind to perhaps include an existing sample xamarin forms app with Template10 on the UWP side that will be super cool. I'm missing the link to make the UWP app shine on especially "desktop PC" form factors leveraging my existing code base.

+1

**Comment by mvermef** [comment]
It's in progress.  Jerry is working on right now, December = family first though.

**Comment by syaifulnizamyahya** [comment]
Thats nice to hear @mvermef . Happy holidays to @JerryNixon , all template10 devs and @mvermef , @Pinox

**Comment by JerryNixon** [comment]
![wp_20170101_17_58_42_rich](https://cloud.githubusercontent.com/assets/1749983/21584460/ddab10de-d04c-11e6-9954-bcb88026348d.jpg)
Aloha lei, guys.

**Comment by mvermef** [comment]
very nice.... unfortunately my ass with my profession was working :(

**Comment by dg2k** [comment]
hey, you can't complain with such a view ;-)

**Comment by JerryNixon** [comment]
@syaifulnizamyahya in what way were you unsuccessful?

**Comment by JerryNixon** [comment]
@Pinox I do not believe T10 is compatible with Xamarin Forms. But Prism for Xamarin Forms is to Xamarin Forms what Template 10 is to UWP. I realize UWP is part of both, but once you introduce XF you have a whole new set of rules to play by.

**Comment by Pinox** [comment]
@JerryNixon I agree.  Was simply thinking of reusing my XF viewmodels in native UWP with T10.  Then I only need to rewrite the views if T10 can handle XF Viewmodels + MVVM Light

It looks like XF can be incorporated into Native UWP from May17.  I quote XF Roadmap regarding this.

Version 2.5.0 - May 2017
Xamarin.Forms Embedding - Feature
Embed Xamarin.Forms into a native Xamarin.iOS, Xamarin.Android, or Windows 10 app.
