### ISSUE TITLE
DISCUSSION: drop Visual Stusio 2015 support

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1443]
Here's why I want to drop Visual Studio 2015 support:

1. I hate the idea of supporting more than one version of Visual Studio
2. I want the templates to default to the latest Windows SDK, only in 2017
3. That's all

Is this a deal breaker for anyone?

By the end of this week I will update the Visual Studio gallery with the VSIX in the previous issue which will effectively remove all Visual Studio 2015 support. Unless someone can convince me otherwise, I even think this is a good ongoing policy. It's worth talking about (later) what SDK to support. 

Please I appreciate your feedback.

**Comment by florianmonfort** [comment]
Sounds good 👍

**Comment by brianobr** [comment]
Sounds good to me.

**Comment by richardcastle** [comment]
Yep. No-brainer.

**Comment by harvinders** [comment]
@JerryNixon 
Generally in enterprise we do not get to deploy the latest visual studio version. It goes through internal validation before rest of us can use (is there any point in doing so is a different question), most of the regulated companies like medical/healthcare may fall into this. Sometime it is an year or more. Also, years gone by I have seen companies not going for the latest version because of cost reasons. Now if you want enterprise developer who may want to get a taste UWP through visual studio 2015 and template 10, I think you should support it.

**Comment by Quico20** [comment]
I had stopped using VS2015, since VS2017 went out!!! so, GO AHEAD BUDDY!!!!

**Comment by florianmonfort** [comment]
@harvinders that would mean turning Template10 into its own product or adding the support for it with a dedicated team as part of the enterprise subscription which your companies probably pays for.

Which means in this thread and for the purpose of non-Enterprise/Community use, he can absolutely drop support.

**Comment by GFlisch** [comment]
Do it 👍

**Comment by dg2k** [comment]
+👍
