### ISSUE TITLE
Less of an Issue, and more of a Request

### ISSUE THREAD

**Issue by ekgcorp** [Windows-XAML/Template10#1448]
I am very new to development and I am a constant source of learning. I think I have scratched all the hair off my head..

So here is my request, and please give feedback if I'm way off base. 

What I'm wondering is, why INotifyPropertyChanged interface is not part of ViewModelBase?  Seems like a logical place to put it.

I do see that a Snippet has been provided via the Wiki, but this seems like something that would get implemented enough that it should be apart of the Base Template.

Please shot holes all in this so I can keep learning.

Kind Regards,
Randy
www.echoknowledgegroup.com

**Comment by mvermef** [comment]
If you dig enough because of refactoring it is part of the ViewModelBase, via BindableBase via IBindable, just had to know what to look for...

**Comment by ekgcorp** [comment]
The Noob figured it out..

In ViewModel...
public string Value { get { return _Value; } set { Set(ref _Value, value); } }

In XAML
TextBox Text="{Binding ViewModel.HostName, Mode=TwoWay}"

**Comment by darenm** [comment]
I depends what you mean by "confirm my properties were getting changed?"

In your code:
```csharp
public string Value { get { return _Value; } set { Set(ref _Value, value); } }
```
You have a `Set(ref _Value, value)` - in Template10 that code is responsible for updating `_Value` to `value` (but only if `_Value != value`) and raising a property changed event on the UI thread (so that the UI will actually respond to the change).

Looking at your XAML, are you asking how to bind to the property so you update the value in the UI and have the ViewModel property update? If so, there are a bunch of assumptions we have to make based upon the code you are showing:
1. The DataContext of the XAML page is set to the page itself.
1. The Page has a Property called `ViewModel`
1. The `ViewModel` property is set to an instance of a ViewModel class that implements the ViewModelBase and has a property called HostName.

If so, all you need to do is set a breakpoint on the set part of your property definition. You can do that by putting your cursor inside the set method body and hitting F9, or reformat the property and setting a breakpoint by clicking in the left hand border of the editor, etc.:
```csharp
public string Value 
{ 
    get 
    { 
        return _Value; 
    } 
    set 
    { 
        // set breakpoint here
        Set(ref _Value, value); 
    } 
}
```
You also showed two different ways of binding to the `Text` property of the `TextBox` control in XAML:
1. This updates the `ViewModel.HostName` property *on every key press* (**note** you still need `Mode=TwoWay`):
```XML
<TextBox Text="{Binding ViewModel.HostName, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"/>
```
2. This updates the `ViewModel.HostName` property once the `TextBox` has lost focus
```XML
<TextBox Text="{Binding ViewModel.HostName, Mode=TwoWay}"/>
```

**Comment by ekgcorp** [comment]
Is there a Donation jar I can throw a few dollars in for this brief but prompt educational lesson? 💯 

Sorry about that... I copied the Get Set for Value and not for HostName..  Here is the right one..

private int _HostName;
public int HostName { get { return _HostName; } set { Set(ref _HostName, value); } }

Here is the DataContext of my XAML and all of Properties are in the AddDevicePageViewModel
    <Page.DataContext>
        <vm:AddDevicePageViewModel x:Name="ViewModel" />
    </Page.DataContext>

On setting the BreakPoint, do I need to open up Property to be more than one line? I'm assuming if I do not, then I will break at both Get and Set.. Correct?

I think for me, all I was trying to do was display a list of values on the right and on SelectionChanged update the Fields on the left, they way I can Edit and resave if necessary.

Kind Regards,
Randy

**Comment by darenm** [comment]
If you place your cursor within the body of the property setter and hit F9 (or go to the debug menu and select breakpoint) the breakpoint will be set on that piece of code. This is a handy approach for setting breakpoints within properties, lambda functions, etc. that are on a single line.

[See more on breakpoints here.](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints)

As you aren't having a specific issue with T10, but rather have more general UWP programming questions, I'm going to close this issue. [StackOverflow](http://stackoverflow.com/questions/tagged/uwp) is a great place to ask these more general questions.

**Comment by ekgcorp** [comment]
Thanks again.
