### ISSUE TITLE
.Props

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#1496]
I was getting ready to post a couple of PRs and noticed that since I had to build the fork relative to my machine I have a bunch modified .props files. Do we want to exclude .props from this since it will push those to the REPO as part of the PR.

**Comment by callummoffat** [comment]
Exclude PROPS.

Thx, CJ

From: Morgan Vermef
Sent: Thursday, June 8, 2017 10:01 AM
To: Windows-XAML/Template10
Cc: Subscribed
Subject: [Windows-XAML/Template10] .Props (#1496)

I was getting ready to post a couple of PRs and noticed that since I had to build the fork relative to my machine I have a bunch modified .props files. Do we want to exclude .props from this since it will push those to the REPO as part of the PR.

**Comment by mvermef** [comment]
thanks Callum

**Comment by callummoffat** [comment]
You’re welcome.

Thx, CJ

**Comment by mvermef** [comment]
**this isn't getting ignored... placing it in the .gitignore isn't working.  putting it in my .git/info/exclude isn't working either.**

**Comment by mvermef** [comment]
.

**Comment by dg2k** [comment]
I have just included for *.nuget.props and *nuget.targets to be ignored in my #1479. I know *.props are annoying but here is a workaround:
Once you're ready for a pull-request, point to Team Explorer tab to view Changes, delete [added] ignorables (*.targets, *.props) and Undo modified ones. In effect, the only changes will be your files and the project file .csproj (unless you amended others). Hope this makes sense.
