### ISSUE TITLE
Text box in page header is partially editable

### ISSUE THREAD

**Issue by Dedecekhribecek** [Windows-XAML/Template10#1500]
please see

https://developercommunity.visualstudio.com/content/problem/59249/text-box-in-page-header-is-partially-editable.html

and

https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19382347-text-box-in-page-header-is-partially-editable?tracking_code=509306e38193a47d96caf82c6cc2edd8

**Comment by dg2k** [comment]
Wow!, you're trying to host TextBox in AppBarButton (that is also hosted by PageHeader), and no wonder you're having trouble.

Try putting your search TextBox as PageHeader Content and you should have no trouble. Currently you used PageHeader Content for title (I'm assuming `x:Uid="LoadViewHeader"` for Content??) , but you can put both TextBlock for title and TextBox for search and adjust their positions with RelativePanel container as you used already.

I suspect the trouble is putting TextBox in AppBarButton (deeper nesting) and we don't know what AppBarButton's templating does to it (for sure we know TextBox doesn't behave as expected). I wouldn't even bother to investigate that because I want to stay away from putting TextBox in AppBarButton to start with, and keep it to PageHeader.

**Comment by JerryNixon** [comment]
Great suggestion.

**Comment by Dedecekhribecek** [comment]
I am not sure I done you recommended. My new code is:
        
        <controls:PageHeader x:Name="pageHeader" RelativePanel.AlignLeftWithPanel="True"
                             RelativePanel.AlignRightWithPanel="True"
                             RelativePanel.AlignTopWithPanel="True" Text="Shelves">
            
            <controls:PageHeader.Content>
                <AppBarButton Width="250" Padding="0">
                    <AppBarButton.Template>
                        <ControlTemplate>
                            <TextBox Width="250" Height="32" Margin="0,8,0,0"/>
                        </ControlTemplate>
                    </AppBarButton.Template>
                </AppBarButton>
            </controls:PageHeader.Content>
        </controls:PageHeader>

Unfortunate behavior is the same.

**Comment by mvermef** [comment]
Basically using the appbarbutton is your problem, trying tho squeeze the control into a button control will more than likely never work.  @dg2k suggested is best bet

**Comment by Dedecekhribecek** [comment]
I understand now.

it works
`            <controls:PageHeader.Content>
                <TextBox Name="TextBox" Width="450" Height="32" Margin="0,8,0,0" Text="text to display"/>
            </controls:PageHeader.Content>
`

first problem noneditable text box
`            <controls:PageHeader.Content>
                <AppBarButton Width="250" Padding="0">
                    <AppBarButton.Content>
                        <ControlTemplate>
                            <TextBox Width="250" Height="32" Margin="0,8,0,0" />
                        </ControlTemplate>
                    </AppBarButton.Content>
                </AppBarButton>
            </controls:PageHeader.Content>
`
second problem partially editable
`            <controls:PageHeader.Content>
                <AppBarButton Width="250" Padding="0">
                    <AppBarButton.Template>
                        <ControlTemplate>
                            <TextBox Width="250" Height="32" Margin="0,8,0,0" />
                        </ControlTemplate>
                    </AppBarButton.Template>
                </AppBarButton>
            </controls:PageHeader.Content>
`

It is pity there is no way to make coupled pair of AppBarButton and TextBox via AppBarButton.Content or AppBarButton.Template. Thank you for help.
