### ISSUE TITLE
Memory leak in UWP

### ISSUE THREAD

**Issue by jaedson-barbosa** [Windows-XAML/Template10#1545]
My UWP can't delete pages I navigated, so, after about 15 minutes, the RAM usage is very big because I can't flush the pages... I think we should be able to remove definetely the created pages from the memory, what do you think about this?

**Comment by JerryNixon** [comment]
Is this about Template 10?

**Comment by JerryNixon** [comment]
Are you unsubscribing all your events @JaedsonBarbosa ?

**Comment by JerryNixon** [comment]
Let me assure you, your conclusion is incorrect. Something is going on.

**Comment by ImCarrot** [comment]
It can be the NavigationCache causing an issue. Happened to me once. As soon as I put NavigationCache mode to disabled, It just worked. check it out once.

**Comment by Chris-Marassovich** [comment]
Hey there @JaedsonBarbosa 

I had a similar issue a while back .. if you have a look at #1242 your issue could be related.

Cheers
Chris ...

**Comment by jaedson-barbosa** [comment]
I tested that with an very simples page, it doesn't have any event, binding or x:bind and... The same problem occurs :(
I don't set the NavigationCacheMode to Enabled because my app is very big and I don't want to have every pages in memory.

**Comment by dg2k** [comment]
- Event unsubscribing - check!
- x:Bind AppBarButton - check! (see #1404); PageHeader memory leak fixed (see #1403)
- Page Code-Behind (not convinced of this but some developers advocate to put `Bindings.StopTracking();` and `VidewModel = null;` in the Page `Unloaded` event, but be prepared for side-effects if you use this).
- The Most Important - what does you app do? Do you use bitmap images? Bindings that sit around for *ad infinitum*, etc.

**Comment by jaedson-barbosa** [comment]
@JerryNixon  I do those thins but this problem continue, please, download my app and see this problem with your eyes.
www.microsoft.com/pt-br/store/p/nfe-facil/9n7w789dgd57

**Comment by jaedson-barbosa** [comment]
@JerryNixon  you will see the memory usage increase very fast.

**Comment by darenm** [comment]
We're not going to download and install a paid app :) If you have a sample that replicates the issue, please send us a link to the source.

**Comment by protocolsolution** [comment]
Is this fix?
Because I am facing same issue in my application. The memory goes to the 2gb. But not release the memory by the GC. I check some application Like: xaml toolkit application sample app, XAML sample app, and other sample application which is provided by the microsoft. The same issue found there as well...

**Comment by abhiraheja** [comment]
Is this fix?
Because I am facing same issue in my application. The memory goes to the 2gb. But not release the memory by the GC. I check some application Like: xaml toolkit application sample app, XAML sample app, and other sample application which is provided by the microsoft. The same issue found there as well...
