### ISSUE TITLE
Why doesn't PrimaryButtons derive from ItemsControl?

### ISSUE THREAD

**Issue by nonameworks** [Windows-XAML/Template10#1556]
This applies to secondary buttons as well. It would be useful to bind items source and set items template to generate all of the buttons from a collection if we want to be able to change them based on user input or services.

**Comment by JerryNixon** [comment]
It's a very complicated ordeal to do what you are talking about, in part because we support several types of templates, but also because we tweak the visual tree in special ways. That being said, there is a part of me that regrets that the HamMenu doesn't support ItemsSource, too. Still, it's important for you to know that we are working on Template 10.2 and it will support as the primary Hamburger interface, the new NavigationView, which will be part of RS3. This is a preferred control, in part, because it is written by Microsoft - it is a first party control. And yet, it also does not support ItemsSource. Crazy, huh? Listen, it's  a good question. It would not be impossible to add the functionality, but I am not going to make significant changes to the control as it is very stable at this point. If you are wondering how to handle this on your own however, I have written a very relevant blog article: http://blog.jerrynixon.com/2013/12/xaml-how-to-add-itemssource-to-windows.html
