### ISSUE TITLE
NavigationMode in 1.1.13p Branch

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1557]
@JerryNixon -- I was testing the Hamburger project with 13p codebase and noticed that `NavigationMode` detection is incorrect on Back navigation.

### Test scenario
- Run the project in debug mode (refs to `Template10 Library` and `Template10.Mobile` projects, i.e., delete 1.1.12 NuGet package ref);
- Navigate to another page (Settings or DetailPage);
- Set a Break in `OnNavigatedToAsync` nav event handler in MainPageViewModel.cs to observe the value for `mode`;
- Navigate back to the MainPage/Home page.

Expected value:  **Back**
Actual value:      **New**

**Comment by schuettecarsten** [comment]
I was not able to reproduce this in our app with current 1.1.13p bits. Is it still reproduceable on your code, @dg2k ?

**Comment by stefankueng** [comment]
Had similar problems with 1.1.13p in my project:
* mode was "New" instead of "Back"
* but also the "parameter" was wrong: I use a string there, but what I got instead of my expected string was 
`{"Type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","Data":"\"EXPECTED_STRING\""}`

going back to 1.1.12 solved the problem. But I had to delete the 1.1.13p nuget package manually - as long as it was there the problem persisted even when referencing only 1.1.12.

**Comment by JerryNixon** [comment]
Thankyou
