### ISSUE TITLE
Discussion: is Closed worthwhile?

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1559]
Hey @Windows-XAML/template-10-developer-community ,

I am toying with adding an `Application.OnClosed` override to Bootstrapper that would be called when the user clicks the `X` control button (including `Alt`-`F4`) on their app. It would not be called if the app was terminated by the system for any reason, including resource constraints. 

There is currently no obvious way to monitor for this event in a UWP app, but because of how Template 10 is built, I can actually do it. The question is not how or if, the question is: **is this even valuable to a developer of an app?** Remember, you already have `Suspending`, so you know when your apps is potentially closing, though `Suspending` does not mean your app WILL be closed - the best practice is to treat a `Suspending` as closed. The Template 10 `Closed` override would be called before `Suspending` was raised. 

Before you answer, consider this caveat:

Template 10 ships with a built-in extended session strategy so that a minimized desktop app does NOT suspend. Without this implementation, your UWP desktop app would go into suspension when it is minimized. Extended execution session has a kind called `Unspecified` whose cryptic name actually means it prevents your app from going into suspension. When your app is minimized it does, however, enter `Background` which means its resource constraints change and there is no UI. In Template 10, we publish an `EnteringBackgroundMessage` if you ever wanted to use this state change. To be clear, there is still a `StartKind` of `Background` which calls the `Application.OnStart` override in `BootStrapper` if the app is invoked by a background trigger or as a background task. Template 10 just extends that.

We've also created a global `AppVisibility` property in the `Central` class with an enum value of either `Foreground` or `Background` and an associated `AppVisibilityChangedMessage` if you want to use that for reducing your memory footprint when the user has minimized your app. 

But with this use of `ExtendedExecutionSession.Unspecified`, Template 10 will not only not suspend, it will also not suspend. Let that sink in: if you do not suspend then you will not resume. From a simplicity perspective, this is brilliant, it means your app will act more like the WPF lifecycle (which means developers have far less to deal with), but it will not act like a UWP app and we might actually confuse developers. On device-types that do not support `ExtendedExecutionSession.Unspecified`, like HoloLens, the app will continue to act like normal, calling `OnStart` and automatically saving and restoring the default `NavigationService` state.

So, that's the caveat. Template 10 makes apps better, but it also means developers might be surprised or confused by the lack of suspension. It is not mandatory that we implement `Unspecified` or introduce the `Closed` override, either. I've already done most of the work, and double-checked my work with the shell team who handles the background API. I'm definitely doing it right. 

But do you like it?

**Comment by rpedretti** [comment]
Well, as this is a big deal I talked to my brother (wich also develops UWP apps) and some doubts came up.

First, we would have to still check for suspension to save the ViewModel, etc on devices that don't support ```ExtendedExecutionSession.Unspecified``` so to support it we should have na implementation for both scenarios on ````OnNavigatingFromAsync()``?

Second: On close would be nice to handle serializing the state to filles as we can Always work in memory, if no constraints, while in app. But it will be configurable at, lets say, app constructor?

But the idea is very interesting to me and if it's almost done I can't say why it should not be available. For experienced devs it is not confusing at all, i think. My sugestion is that it should be available for 'insiders' at first to give it a ride and then see how it Works and give a honest opinion.

**Comment by schuettecarsten** [comment]
The new event is `OnClosed`, not `OnClosing`?
Is it possible to add a "do you really want to close app?" dialog to this event and cancel the close?

**Comment by marcusrunge** [comment]
I was thinking about possible Use-Cases. These could be storing something in a local or remote database, performing a REST call or TCP transfer. Maybe it Can cover an app Crash an do something if it happens.  In all of These cases the Impression for the user should be "App closed". Whatever follows "Close-App" should be invisible like a short running Background Task, deferral, something like this if possible.

**Comment by ImCarrot** [comment]
To be honest, I think it would be useful to have it as modern day apps do need to signoff on sessions, store data on to services or save them as drafts or even maintain analytics. It'll be useful to have. It maybe used in an edge case scenario but yeah.

**Comment by callummoffat** [comment]
I think it would be quite useful - would provide a out-of-the-box means of saving data before closing the app.

**Comment by pekspro** [comment]
Maybe I misunderstand something but I have some doubts about this. The first thing I think about is the built-in extended session strategy. It is a nice feature but I think it should be off by default. When the OS tells an app to suspend it should be a good citizen and suspend :-). If you are targeting only computers with a lot resources maybe you could do an exception, but it should be an exception and not the default behavior.

Since we already have the Suspending event, where you are supposed to save data, releasing resources etc., I'm not sure that a special event for closing would be useful. However, I would like to see a twist of this :-) When handling the suspending event it would be useful to know that the app also will be terminated (which is the case when someone pressed the close button). Then you could do all the things you are supposed to do in a Suspend event, but you don't need to prepare for resume.

**Comment by JerryNixon** [comment]
No, @schuettecarsten, you cannot prevent closing once the user clicks X.

**Comment by JerryNixon** [comment]
Well, @rpedretti, my concern is the edge cases where it does not work.

**Comment by JerryNixon** [comment]
In the end, @marcusrunge, Suspending or view-model.OnNavigatedFrom should handle those.

**Comment by JerryNixon** [comment]
Well, @callummoffat, is OnnavigatingFrom not enough today?

**Comment by JerryNixon** [comment]
You know, @pekspro, I am thinking the same thing. Perhaps a setting. SuspensionBehavior of an enum [flags] with things like { `Standard`, `DoNotSuspend`, `ExtendSuspension` } with flags so you could potentially support multiple sates. This is just me thinking out loud here. But it might make more sense.

**Comment by JerryNixon** [comment]
The biggest problem is that if a developer tweaks the behavior of the extended state, the `Closed` is no longer reliable, and we might have made a mistake letting developers think they can count on it.

**Comment by IIARROWS** [comment]
Giving that I think MS should have given a Closing event, I too don't support redundancy.

It might be clear what a "Closed" event does, but you should still support all platforms at least implicitly.
The exception should always been marked as such, and an event that is valid only on some platforms, is not explicit enough.

The day Augmented Reality is mainstream enough, and you decide to extend support, you end with code that doesn't work like it should, and it will be a pain to resolve why you it doesn't log or close the session, because you will not remember that it isn't supposed to work.
Da: notifications@github.com
Inviato: 6 settembre 2017 12:57 AM
A: Template10@noreply.github.com
Rispondi a: reply@reply.github.com
Cc: II_ARROWS@hotmail.it; team_mention@noreply.github.com
Oggetto: Re: [Windows-XAML/Template10] Discussion: is Closed worthwhile? (#1559)



The biggest problem is that if a developer tweaks the behavior of the extended state, the Closed is no longer reliable, and we might have made a mistake letting developers think they can count on it.

**Comment by JerryNixon** [comment]
I think we are all in agreement.
