### ISSUE TITLE
Question about Refreshing a Page

### ISSUE THREAD

**Issue by wyepez** [Windows-XAML/Template10#1564]
I have noticed that when I refresh a page using NavigationService.Refresh(), the OnNavigatedToAsync method is not called. After reading #1304, #1002 and #995, If I provide a parameter to NavigationService.Refresh(), the OnNavigatedToAsync is called but the NavigationMode parameter is New instead of Refresh. I think the OnNavigatedToAsync method must be called always on Refresh, regardless of whether a parameter is passed or not and the NavigationMode parameter must be set accordingly . As someone said, some developers may find annoying this behavior but I think it is the purpose of the NavigationMode parameter.

Or how can I get the OnNavigatedToAsync method being called with the NavigationMode parameter set in Refresh?

**Comment by JerryNixon** [comment]
Well, here's the line that calls the navigation mode in 1.1.13: https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L214 And, here's the line that calls the navigation mode in 1.1.12 https://github.com/Windows-XAML/Template10/blob/version_1.1.12_vs2017/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L180

I assume you are doing this in Template 10 version 1.1.12. 

Well, are you using `NavigationService.ResolveForPage()` to create your page programmatically? Either way, if you are getting mode==New the view-model is there. So, that's not it.

When you refresh you get New instead of Refresh...

So I looked at the 1.1.12 `Refresh()` operation in the `FrameFacade` (which is where the logic resides in 1.1.12) and I saw this implementation: https://github.com/Windows-XAML/Template10/blob/version_1.1.12/Template10%20(Library)/Services/NavigationService/FrameFacade.cs#L165

I see the problem. Instead of wrapping this operation in the NavigationOrchestrator of the NavigationService which would properly call the view-model methods, it ONLY gets and sets the navigation state string of the encapsulated string. 

How is it possible that you are the first person to report this? This is not good and is a real problem. I can't think of an immediate workaround either. I will need to significantly change the Navigation logic to get that to work. I think a quick around would be for you to put something in a static field to check for Refresh like this. 

But, then I think it is worth looking at 10.2 which implements the frame facade logic here: https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Services/NavigationService/FrameFacade.cs#L134

You can see the logic has been removed and marked as obsolete (it is not simply removed so Template 10.1 developers will have a little internal guidance on how to use the changed API. The Refresh logic has been moved to the NavigationService (the only place that made sense for it) and implemented here: https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L370

I guess I realized the problem you identify here while rewriting Template 10 for the Falls Creators Update.  The Refresh operation is now properly wrapped in the NavigationOrchestrator which is responsible for not just navigation but also managing the before and after events for view-models. 

A hack of a workaround is all I can offer you with version 1.1.12

Maybe this:

````
static bool _refresh = false;
void MyMethod()
{
  _refresh = true;
  navigationService.Refresh();
}
void NavigatedTo()
{
  Try
  {
    if (_refresh)
    {
      // special logic
    }
    else
    {
      // normal logic 
    }
  }
  Finally
  {
      _refresh = false;
  }
}
````

**Comment by Hamza54** [comment]
Hello,
I have the same issue with the NavigationService.Refresh(). I see that the issue has been opened for more than 6 months. Any updates on this issue? 
Thanks
