### ISSUE TITLE
Right PaneBorder doesn't show in HamburgerMenu compact view

### ISSUE THREAD

**Issue by schnitty** [Windows-XAML/Template10#1566]
#1563 

Sorry I should have been more clear in my initial issue.

Steps to repro:
New hamburger project
Set PaneBorderBrush and PanBorderThickness properties as shown in previous issue #1563 

CompactView:

![image](https://user-images.githubusercontent.com/6099451/30007910-018928c0-9158-11e7-9306-1e8c3e7b4334.png)

NB: No right hand border.

ExpandedView:

![image](https://user-images.githubusercontent.com/6099451/30007921-1ed20014-9158-11e7-8eb7-8494d4fd4e95.png)

NB: Right hand border appears.

What I would like is to have the right border show when in Compact View.

If that isn't supported then that is ok, just want to know if i'm missing something or there is some trick that I don't know of.

Thanks

**Comment by JerryNixon** [comment]
So, what I am hearing you say is, it's right half the time?

**Comment by dg2k** [comment]
@schnitty is right. The right-border collapses when the pane closes to compact form. Hmmm...
Come to think of it, doesn't look right that for the pane to provide the border. Or should it?
On checking my design it's the RootGrid or ContentGrid left-border that provides a hint of border between page and menu pane. Because of this I never ran into a situation where I needed a border for compact pane.

The page control is actually more flexible.
- If margin is required for a page excluding page-header, set RootGrid margin to 0 and define border for ContentGrid in RootGrid (that excludes page-header).
- If margin is required all the way to the top (including page-header) you do it for RootGrid.
- If the above looks onerous, it isn't.  Just define a border style as ThemeResource and use it consistently in your view pages  for RootGrid or ContentGrid.
- Yes, I needed the right margin when the pane is open (which is working) because you want to see the boundary when using overlay menu modes.

@schnitty - will the above change your mind? 

Why doesn't the right border show up in compact form? I suspect the 48px width is swallowing/disallowing/whatever ... the border. This can be looked into at a lower priority in the todo list.

**Comment by schnitty** [comment]
@dg2k I'll try out those options and let you know how I go.  Thanks

**Comment by schnitty** [comment]
What you have suggested will work fine.  Can't believe I didn't think of that myself.  Sometimes you get a bit of tunnel vision.
