### ISSUE TITLE
Template 10 Validation Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by anthony-salutari** [Windows-XAML/Template10#1584]
I'm really stumped on how to fix this issue.

When my project is built my designer gives me this error
![image](https://user-images.githubusercontent.com/6045425/32109272-39346e6e-bb02-11e7-8e76-901dea0be5de.png)

I've tried emulating the sample project but it isn't using the validation library from NuGet. I'm wondering if it's a problem with the NuGet package.

My Xaml looks like this 

`xmlns:validate="using:Template10.Controls.Validation"`

` <validate:ControlWrapper PropertyName="CustCode">
                <TextBox x:Name="CustCodeTextBox" Text="{x:Bind ViewModel.Customer.CustCode, Mode=TwoWay}" Header="Customer Code" Margin="0,25,0,0" />
</validate:ControlWrapper>`

As soon as I remove the `<validate:ControlWrapper>` the exception immediately goes away.

**Comment by mvermef** [comment]
Don't x:bind the property... Reference the samples source https://github.com/Windows-XAML/Template10.Validation/blob/master/Sample/Views

Part of the problem is that x:bind,  next how are you setting the context for the control wrapper to understand CustCode?

**Comment by anthony-salutari** [comment]
I'm setting the page context to my viewmodel as such

`xmlns:vm="using:OnlineOrderManager.ViewModels.Customers"`

```
<Page.DataContext>
    <vm:AddCustomerViewModel x:Name="ViewModel" />
</Page.DataContext>
```

**Comment by mvermef** [comment]
So bind to the TextBox this way instead of your present...
<Grid DataContext="{Binding Customer}">
    <validate:ControlWrapper PropertyName="CustCode">
        <TextBox x:Name="CustCodeTextBox" Text="{Binding CustCode, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"  Header="Customer Code" Margin="0, 25, 0,0" />
     </validate:ControlWrapper>
</Grid>

I know its redundant but this is very specific to validation.  Customer being your class object that contains the properties to be validated.  Which is how (I am pretty sure) you have it right now.

I missed it the first time I started using the validation library as well... Its very subtle but binding the context for the Grid to your Customer Property of the viewmodel  tells the control wrapper the `IProperty<T>` which is this case has a ValidatableModelBase as its base class

**Comment by mvermef** [comment]
<Grid DataContext="{Binding Customer}">
        <validate:ControlWrapper PropertyName="CustCode">
          <TextBox x:Name="CustCodeTextBox" Text="{Binding CustCode, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"  Header="Customer Code" Margin="0, 25, 0,0" />
        </validate:ControlWrapper>
    </Grid>

So bind to the TextBox this way instead of your present code.

I know its redundant but this is very specific to validation.  Customer being your class object that contains the properties to be validated.  Which is how (I am pretty sure) you have it right now.

I missed it the first time I started using the validation library as well... Its very subtle but binding the context for the Grid to your Customer Property of the viewmodel  tells the control wrapper the `IProperty<T>` which is this case has a ValidatableModelBase as its base class

Every property that has to do with customer and needs **validation** goes inside that grid, beautified as necessary to make it look right in the grid...  **NB** doesn't have to be a grid per se, it can be any container type to hold the contents of the Customer object...
