### ISSUE TITLE
[10.2] Discussion: Feedback on trialing 10.2

### ISSUE THREAD

**Issue by AtomicBlom** [Windows-XAML/Template10#1585]
Hi Jerry (and crew),

I've spent the last few days investigating the possibility of migrating to Template 10.2 to solve a few issues we've had with Template 10.1. (Juddering caused by ViewModels not being pre-populated with data before being assigned to the page, and a few other issues, which seems solvable using OnNavigatingTo)

I'd like to share some feedback I've gathered along the way, but I feel they need more discussion than a straightforward PR to fix some things.

Discussion Points
==
Dependency Injection
---
We're currently using Autofac for DI in the project I would like to port. We're using the advanced scoping that is provided.
Autofac follows a very strict Register -> Resolve architecture. Additional registrations must be made by creating new scopes.
Template10.2's Dependency framework is, by design a bit more ad-hoc. Because there is no definitive "I'm done adding registrations", My autofac adapter attempts to work around this at runtime by automatically creating lifetime scopes. It works, but I'm academically not too happy with the approach.

In addition, I found that I was forced to register everything as a Singleton inside my AutofacContainerAdapter otherwise BootstrapperBase would resolve different instances of `IBootStrapperStrategy` and the application would crash with a null pointer exception.
Because of the usage of lifetime scopes, singletons are not ideal for our application, so I was forced to 
expose the concrete implementation of the autofac Container builder in my bootstrapper in order to get a much finer-grained control over registration.

I've included my investigative implementation as an example.

Here is my current approach to integrating Autofac with Template10.2:
https://gist.github.com/AtomicBlom/722b0d264d4545464d66d6f3d92042b4

Messaging
==
Our application currently uses ReactiveUI's MessageBus, however as part of this potential migration, we're investigating other alternatives with the hope of getting one that natively supports async message processing. To that degree, I've been working to implement Reactive.EventAggregator

My investigations have lead me to believe that it's quite difficult to implement a messaging system that is based on the IDisposable pattern (such as ReactiveUI, Reactive.EventAggregator, Prism events) It is also difficult to work with Caliburn-Micro's EventAggregator, which can only unsubscribe wholesale, it cannot unsubscribe from individual messages.

Because Template10 mandates the presence of a MessageBus for internal purposes, I rather feel like it needs to provide a basic mechanism which will work for Template10 without being forced to take a dependency on MvvmLight for it. 

My solution to the problem was to implement a truely rough-as-guts message bus for Template10, and other than that, it's sole responsibility is to throw a message on the Reactive.EventAggregator as well.
https://gist.github.com/AtomicBlom/1d8742caf330889996da3c38e7850781

The classes are currently resolved via DI

Things that are working well
=
I don't want to leave a feedback issue without also telling you the bits I've tested that are working well:

Template10.Portable
-
Making the Navigation interfaces available in Template10.Portable, and making Portable a .NET Standard 1.4 library is fantastic for us. I'm trying to encourage the team to move towards Unit Testable ViewModels. (We're currently developing for Windows 10 IoT Enterprise, which is stuck on Anniversary edition for a while and we won't have access to .NET Standard 2.0 for a while)

I'd love to see more stuff move into here, specifically implementations of ICommand (which is supported by .NET Standard 1.4), IDispatch, and other services, such as Marketplace, Nag, File.

Navigation
-
You removed the reliance for INavigable, which was not portable and leaked a number of concrete UI concerns
Breaking the navigation up into smaller parts and allowing them to be completely optional, which is a big plus for unit testing

Thanks so much for the INavigatingToAsync, which allows us to pre-set properties on our ViewModels to appropriate initial values, avoiding a flash of default values especially when a page was navigated to for the first time.

Conclusion
=
I'm sure I'll have further feedback as I continue to work through this trial, and I'd love to have a discussion on these points and break them out into issues you think are appropriate to tackle. My workarounds are functional, so there is nothing blocking me from continuing as-is.

Regards,
Steven

**Comment by JerryNixon** [comment]
## Dependency Injection

> I will only address one thing at a time here, you have a lot to talk about. First, let me thank you for working with Template 10 and taking the time to start testing 10.2. 

Before we do much more, add me to Skype (mr.jerrynixon) because I think this will start to clutter GitHub if we keep the conversation going too much here. I like others to see what we are talking about, but at the same time this is the repo for 10.1 and those users don't need to worry about this. For that reason, by the way, I am likely going to create a 10.2 repo, if for no other reason, to isolate Issues. 

### Now, for my initial thoughts

I had forgotten about this with Autofac until I started to read your report. Then it all rushed back. Like you, I am not satisfied with your fake scope solution, even if it does work. I would also like to say I don't like this feature of Autofac and I never have. Still, I think we can resolve this and must resolve this because Autofac is so popular. 

The good news is, Template 10 registers everything at basically the same time, just in two different methods. And, if we have a gap we can fill it. I think we can resolve this with a start and stop mechanism somewhere. Perhaps the container itself could have an implicit start and stop for MvvmLight and Unity that do not care about this and Autofac could actually implement. 

### Something like this

> I will create this mechanism in the next day or so and add it to the solution. I will also be changing the names of some of the services, so please note that some secretarial changes will be coming to the solution that hardly represent architectural changes. 

````
IContainer.BeginRegistration()
IContainer.EndRegistration()
````

I will need to implement it in such a way that if `Begin` is NOT called by developers who are not using Autofac that they do not feel like they are hamstrung by this new feature. This initial scope will wrap both the internal Bootstrapper.RegisterDefaultTypes and Boostrapper.RegisterCustomTypes somehow. This will take a little thinking but I am happy to solve it.

**Comment by JerryNixon** [comment]
@AtomicBlom can you take a peek at the new Template10.2? Thank you for your looking at the preliminary work. Today, when you get what is in Master I think you will find it noticeably simplified. Cheers.
