### ISSUE TITLE
Error after updating Target version to Fall Creators Update

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1588]
I'm developing a UWP app for Windows 10 IoT and I need to use some features introduced in Fall Creators Update 16299. So I try changing my already built app target version to 16299 and leave the min version at 14393 for compatibility. When I open up any XAML page that uses T10 I get numerous errors. "unable to instantiate  settingspageviewmodel", "the resource wideminwidth could not be resolved", "unable to instantiate template10.controls.pageheader", etc. If I change the target version back to 14393 and rebuild, all the errors go away.

How can I resolve these?

**Comment by mvermef** [comment]
Is this the nuget package source is t10.01, it will probably not work correctly without necessary changes from t10.2 source in the master

**Comment by dg2k** [comment]
Just to confirm one point: I have no issues with the Target set to 16299 and min ver 14393 when using the source code. It builds okay, and as @mvermef indicated perhaps the nuget package has issues??

It will help to delete the hidden **.vs** folder in your solution folder, as well as **bin** and **obj** folders for your projects, so as to start with a clean slate. Visual Studio's *memory effect* due to .vs, bin and obj folders is somewhat mind-boggling, to say the least, and it helps to delete these folders. But note that some settings will be lost if deleting .vs (such as Startup Project) but these can be easily restored.

**Comment by schuettecarsten** [comment]
I also have no issues with target version 16299 and min version 10240 and template 10 source code from 1.1.13p branch. So, maybe we should update the NuGet package for version 1.1?

**Comment by mjmeans** [comment]
The NuGet package is updated to the newest release, 1.1.12. I don't want to use prerelease.

**Comment by schuettecarsten** [comment]
Even if you do not want to use the prerelease 1.1.13 build, can you just try it and check if the error still occurs?

**Comment by mjmeans** [comment]
I can probably do it tomorrow. I have to finish another task in the project first. I'll post my results after that.

**Comment by JerryNixon** [comment]
What did you find out?

**Comment by opi-smccoole** [comment]
I've run into this error as well and cannot even get the release_1.1.13p branch to build in order to try it out.  I'm still early in the project at this point but its looking like I might have to abandon Template 10 in order to proceed forward.  This really disappoints me as I would love to leverage all that it brings with it.  Even if I can back down from the fall creators update or make it work somehow I'm also wondering what the impact will be in order to migrate a project to 10.2 when it becomes available?  Are we looking at major effort or rewriting to update?

**Comment by antlhuede** [comment]
template10 development is so far behind its almost useless. Windows template studio is much better.
Your navigation patterns are extremely limited and not very flexible, no real support for suspension out of the box.
are you guys even trying with this library anymore? strictly targeting 16299+ causes huge numbers of errors with template 10, yet it is necessary for anyone building UWP .Net Standard 2.0 compliant applications.

either mark the library as deprecated or keep it up to date.... don't encourage people to pick it up if it is going to die due to underdevelopment / not keeping up with a standard that was released almost a year ago.

**Comment by VarusSeptimus** [comment]
I managed to re-target my T10 app (using T10 version 1.19) to Windows 10 Fall Creators Update (10.0 Build 16299).

Initially I got an error at built time, but changing min target version to 'Windows 10 Anniversary update 14393' (while keeping max target at 10.0 Build 16299) allowed me to build and run.

Then I subsequently upgraded to min target 10.0 build 15063, rebuilt without problem, and then
again upgraded min version to 10.0 Build 16299, and then built and run all right.
