### ISSUE TITLE
[1.1.12] ObservableItemCollection only works with Binding instead of x:Bind in DataTemplate

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1594]
I working with ObservableItemCollection and I have regognized that for example the ListView works only correct with a DataTemplate where the variables uses Binding instead of x:Bind. 

How is it justified that x:Bind not working?

**Comment by michaelhutchful** [comment]
When you set the itemSource using x:bind, then in your data template you need to specify x:DataType as the data structure you are using for your ItemSource. This is an XAML thing, not template 10.

https://stackoverflow.com/questions/38520592/binding-data-into-listview-through-xbind-in-uwp

I hope this helps
Sent from Mail for Windows 10

From: revan1199
Sent: 28 November 2017 17:03
To: Windows-XAML/Template10
Cc: Subscribed
Subject: [Windows-XAML/Template10] [1.1.12] ObservableItemCollection onlyworks with Binding instead of x:Bind in DataTemplate (#1594)

I working with ObservableItemCollection and I have regognized that for example the ListView works only correct with a DataTemplate where the variables uses Binding instead of x:Bind.
How is it justified that x:Bind not working?

**Comment by jp-weber** [comment]
I am aware of this. In my case I use in the DataTemplate of course x: DataType.

For my test I use the sample "MultiplePageHeaders" and created its own class for 'mymodel' model.
If I change in the DataTemplate Binding => x:Bind, it doesn't work.
```
<ListView x:Name="ListView_Main" ItemsSource="{x:Bind ViewModel.Items}" RelativePanel.Below="button">
            <ListView.Header>
                <TextBlock Margin="16">
                    This is testing ObservableItemCollection eventing.
                </TextBlock>
            </ListView.Header>
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="models:MyModel">
                    <TextBlock>
                        <Run Text="{Binding  Text}" />
                        <LineBreak />
                        <Run Text="{Binding  Special}" />
                    </TextBlock>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

```

**Comment by darenm** [comment]
A key difference to understand between `Binding` and `x:Bind` is that `Binding` is `OneWay` by default, whereas `x:Bind` is `OneTime` by default - look at the documentation for the `Mode` property [here](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension). So just replacing `Binding` with `x:Bind` is not like for like - if you are assigning a new instance to the `ViewModel.Items` after the initial `x:Bind` is evaluated, or loading new items into an existing collection, the UI will not update. So, try setting `ItemsSource='{x:Bind ViewModel.Items, Mode=OneWay}'` and see if the issue continues.

Regardless of whether this fixes the issue - `Binding` or `x:Bind` is not part of Template10 so in the future you will be better served raising questions regarding the fundamentals of XAML on [StackOverflow](https://stackoverflow.com/questions/tagged/xaml)

**Comment by jp-weber** [comment]
Thank you! Mode=OneWay fix this.
