### ISSUE TITLE
App's NavigationService is null

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1611]
App's `NavigationService` is null when launching the app and any My People window is open already.

**Comment by panoukos41** [comment]
Yea i was using my own navigation service but my app was crushing on the app back button, creating a service just so that it exists got it solved (and it always needs to be created manually especially if you want to use it) but it was a pretty annoying bug :/

    var nav = NavigationServiceFactory(BackButton.Ignore, ExistingContent.Exclude);

**Comment by JerryNixon** [comment]
Thanks @panoukos41 for this tip. I've done this in edge cases, too. I have not created a custom people add-in yet with Template 10. I will make sure to test it with the new Template 10 before going much further. I am closing this issue because there is a workaround. The next version of Template 10, as an FYI, is really intended for FCU and later, which includes people. So, that's worth testing.
