### ISSUE TITLE
Page bindings are updated even when navigating from.

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1612]

**Comment by FrayxRulez** [comment]
I'm quite sure this line of code shouldn't exist: https://github.com/Windows-XAML/Template10/blob/version_1.1.12_vs2017/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L65

**Comment by JerryNixon** [comment]
That one line is perhaps one of the most significant lines in all of Template 10. Here's what it does. When a page is navigated to, its render pipeline begins and is managed by the platform. After its navigation but before its rendering is complete, I create or collect your page's view-model. I also call OnNavigatedToAsync() and await it. This can take however long, since the implementation code is unique to the developer. It is intended to create your data, fill your properties. But it is possible that your page's render cycles have completed BEFORE your view-model has completed. As a result, Template 10 then updates all of your x:Bind bindings to help ensure any OneTime bindings reflect your new values.

**Comment by JerryNixon** [comment]
Now that I have described what it does. Can you help me understand why you have a problem with it? I have to say, you are one of the only to have ever even discovered this, let alone had any kind of problem with it. This, by the way, is fundamental and part of the next version of Template 10, too. As a result, I am very interested to hear your perspective. If you still think it is a problem.

**Comment by JerryNixon** [comment]
Okay, perhaps I have responded before I completely understood the problem. Looking more closely, because I am genuinely interested, I realize you are right. I am updating the bindings of the exiting page on that line of code. It is here that I update the entering page:

> https://github.com/Windows-XAML/Template10/blob/version_1.1.12_vs2017/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L184

Yeah, that is a real issue. I see it now. I think you will discover that when you look at the preview branch of the update for T10 (which is overdue) this line has been removed.

> https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Services/NavigationService/NavigationService.cs

That doesn't help you, I know. We need to fast-track the update to 13.

**Comment by JerryNixon** [comment]
I am only closing this issue because it is resolved in 13p. I realize 13p has not been published (though you can use it in NuGet if you like). I will make a point to get 13 updated in NuGet quickly. There are a few minor PRs I will include before pushing.
