### ISSUE TITLE
Hang in UWP app

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1616]
I have a hang in a UWP app that might be related to Template 10. The app reads from a USB sensor about 55 times a second and updates a bindable property that is referenced by a Syncfusion gauge control. When the app hangs, the debugger cannot break in, and the close X button cannot stop the app. At some point 5 to 20 seconds later, the app unfreezes by itself and starts running again.

I'm using VS 2017 Community 15.5.6. I've run profiler on the app to see CPU usage and in all cases in the timeline where the app is hung, the CPU usage reported in the profiler is pegged at 25% (this machine has 4 logical processors). Other times it's around 5-10%. The timeline when the app is hung the top CPU usage is 100% at Tempalte10.Mvvm.BindableBase::Set.

**Comment by arpadbarta** [comment]
Do you have any logic in any of the setters that could block?

**Comment by darenm** [comment]
Updating a binding 55 times a second is going to bog down anything if you consider that an event has to be raised, then responded to, the UI refreshed, rinse and repeat. One of the reasons [System.Reactive](https://github.com/Reactive-Extensions/Rx.NET) exists is to assist with handling this type of event flooding. 

You may have a good reason for capturing the data from the device and logging it 55 times a second, but the UI almost certainly does not need to be updated at the same rate. Rx provides the means to throttle the events and update the binding say, once a second. You can learn more about that [here](https://github.com/Reactive-Extensions/Rx.NET). There is more information on Rx [here](http://www.introtorx.com/)

**Comment by michaelhutchful** [comment]
Hi, what are you using the property for? If it is data binding, I will assume that your a displaying something. In that case you could pace the update to as little as twice a second and it should be fine

Michael
Sent from Mail for Windows 10

From: mjmeans
Sent: 09 February 2018 06:07
To: Windows-XAML/Template10
Cc: Subscribed
Subject: [Windows-XAML/Template10] Hang in UWP app (#1616)

I have a hang in a UWP app that might be related to Template 10. The app reads from a USB sensor about 55 times a second and updates a bindable property that is referenced by a Syncfusion gauge control. When the app hangs, the debugger cannot break in, and the close X button cannot stop the app. At some point 5 to 20 seconds later, the app unfreezes by itself and starts running again.
I'm using VS 2017 Community 15.5.6. I've run profiler on the app to see CPU usage and in all cases in the timeline where the app is hung, the CPU usage reported in the profiler is pegged at 25% (this machine has 4 logical processors). Other times it's around 5-10%. In all cases in the timeline when the app is hung the top CPU usage is 100% at Tempalte10.Mvvm.BindableBase::Set.

**Comment by mjmeans** [comment]
I was under the impression that databinding would trigger an update of the UI thread like WM_PAINT such that prior unprocessed triggers of the same property would be skipped in favor of the most recent trigger. That way the UI thread operates at the highest rate for any given PC.

Nevertheless, this problem occurs after several data captures. Each data capture lasts less than 10 seconds, so less than 550 samples. These work fine and the UI is extremely responsive during these captures, until the 4th or 5th data capture, then the hang occurs. Each time a hang occurs it's usually 5 to 20 seconds, though sometimes up to a minute. Thereafter, each data capture might go smoothly and be responsive, or it might hang, or the app might hang at the end of a capture, or it might happen while waiting for the next capture window begins. It's very unpredictable.

**Comment by mjmeans** [comment]
I'm doing my timing using System.Windows.Threading.DispatcherTimer to time when to stop on screen prompts to begin and when to stop the data collection window. I'm wondering if DispatcherTimer may be trying to use the core window dispatcher which isn't hooked up in T10. Do you know of any issues with using DispatcherTimer with T10?

**Comment by mjmeans** [comment]
I tried changing the timing to use ThreadPoolTimer with a period of 100 ms and calling BootStrapper.Current.NavigationService.GetDispatcherWrapper().Dispatch within the timer callback, but to no evail. Hang still occurs.

**Comment by mjmeans** [comment]
I also tried adding a threadpooltimer to update the gauge once every 100 ms instead of as the data is received. No difference.

**Comment by mjmeans** [comment]
I believe I have identified the cause. SyncFusion's Chart control has a LineSeries collection that for some reason ties up the UI thread when using Template10. This control doesn't seem to have the same problem without Template 10, so there must be some kind of thread dispatch issue. The solution was to change to the FastLineSeries collection which provides fewer UI features, but is sufficient for my needs at this time.

**Comment by JerryNixon** [comment]
Oddly enough, I think the human eye can only effectively differentiate 24 frames per second. That being said, if you want the user to respond to your data, or even understand it, updating with such frequency likely  undermines your goal. I can't even move my mouse to a button and click it fast enough to account for 1/55 of a second. I think what you really want to do is to throttle your data so that you saple it only every X milliseconds, instead of so fast. This is not so much a performance of XAML question, as much as it is an architectural question about implementation. What you are doing might feel like the highest-fidelity experience you can offer. What is really happening is a disconnect between the sensor readings and what the interface can show and what the user can grok. There is a throttle in Template 10, and you can use that, but I recommend, instead, that you consider using Reactive Extensions since your event stream is so dense. It will take some time to understand Reactive Extensions and get it implemented. But, I think once you find it working, you will be amazed what it does for you and how finely you can tune the implementation to improve your user's experience. What you suggest with a dispatcher timer can also give a similar experience, depending on your exact requirements.

That being said, and I am sure it has already been pointed out here, but when you bind, be sure and use OneWay instead of TwoWay and x:Bind instead of Binding so you can tweak your performance as much as possible. 

I will close this issue as it is not a T10 issue.
