### ISSUE TITLE
What version of Windows 10 does Template 10 work with?

### ISSUE THREAD

**Issue by rfalanga** [Windows-XAML/Template10#1617]
I'm still pretty new at using Template 10. I've got a UWP app in the Store. When I created the app in Visual Studio, I was given a chance to specify which version of Windows 10 I wanted to target. But when I went to create a quick Template 10 app, I noticed I wasn't given any option.

So, what version(s) of Windows 10 does Template 10 target?

**Comment by mvermef** [comment]
10.0.14393.0 and below, doesn't mean it won't work on later versions just won't use newest bells and whistles

**Comment by dg2k** [comment]
I use T10 with the latest Build 16299 and as @mvermef pointed out you just miss out on the latest features, for instance if you want to use the vibrant colors 16299 provides.

Just as an aside look at this interesting stat on [Windows 10 versions worldwide](http://reports.adduplex.com/reports/2018-01/).

Build 15063 aka ver. 1703 (April 2017) and Build 16299 aka ver 1709 (Oct 2017) together account for over 90% worldwide. 16299 has shot up to 75% in under 4 months! With Build 14393 aka ver 1607 (August 2016) you're close 100%.

Supporting Build 14393 as a minimum is a wonderful thing since a lot of App Store automation is provided starting with 14393.

You can push Template 10 all the way... and with the expected release of 10.2 those bells and whistles can also be reclaimed.

A bit of a disclaimer here: I am using the source code rather than NuGet Package just in case I overlooked somethings on packaging side.

**Comment by rfalanga** [comment]
Thank you all for this feedback. Looks like 10.0.14393.0 will work, if that's the Anniversary Update. Which is what I want to target.

**Comment by JerryNixon** [comment]
@rfalanga I think targeting the Anniversary Update is acceptable. Depending on your use case, I highly recommend you consider Fall Creators Update as your target. It is a considerable improvement . Template 10 supports all of them, so it's all up to you.
