### ISSUE TITLE
SearchScreen is still displayed when HambergerMenu is hidden

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#162]
<img width="382" alt="1" src="https://cloud.githubusercontent.com/assets/485493/10156471/0bd03146-66b4-11e5-9a58-c0f9bbacf4d4.PNG">

When HambergerMenu  is hidden (by click or switch between two monitor), the SearchScreen is stile displayed. it looks strange. 

<img width="413" alt="2" src="https://cloud.githubusercontent.com/assets/485493/10156474/164183e6-66b4-11e5-9185-06f11447b54f.PNG">

**Comment by JerryNixon** [comment]
I have updated the sample project. Please verify with the new updates.

**Comment by lyling** [comment]
Not yet. When the app move off screen and back in narrow mode, the Hambergermenu is hidden while the SearchScreen is still displayed. Looking at the 2nd picture, the element in main frame is shown and can be clicked.

**Comment by lyling** [comment]
I think it is better that when the HambergerMenu is hiding  hide the SearchScreen together or when the SearchScreen is shown don`t hide the HambergerMenu. 
I don`t know how to detect the HambergerMenu hide/show event.

**Comment by JerryNixon** [comment]
The behavior I am seeing in the Search sample is not doing what you are showing. Oh. This is when it is narrow. I will update the sample. I understand now.

**Comment by JerryNixon** [comment]
Okay, I fixed it. This revealed an error, come to find, in the Visibility property of the HamburgerButtonInfo. That is resolved, thanks to you. I took a page from the Groove app and when the Minimal size is invoked, I simply hide the ability to search. I think this makes sense. If you need search in the small width, I would recommend you hide and show different search buttons that do different things. One is for wide and one is for narrow. The narrow should probably navigate to a different page because of real estate. This make sense? Thanks.
