### ISSUE TITLE
NavigateAsync and queue should be improve

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1662]
The current implementation of navigate async is not a good way to navigate with the queue, because the pages which was visited before are displayed again and need performance. I suggest to implement another function which restore the navigation state if the app suspeneded, but for the normal navigation, the function should not navigate each queue.

https://github.com/Windows-XAML/Template10/blob/master/Source/Prism.Windows/Navigation/FrameFacade/FrameFacade.cs#L164

**Comment by JerryNixon** [comment]
Well, I understand what you are asking but some of these design decisions are really an artifact of the XAML Frame control and that there really is no other way to build the navigation state. The other thing to consider is that this behavior is identical to the behavior of Prism on Xamarin.Forms which also navigates the whole stack like the queue. This UWP implementation is coded slightly different, but it behaves the same. So, there's also that. As for a workaround, here's the only thing I can offer you: if you wait to do your initial navigation that includes the queued pages BEFORE you attach your frame to the visual (adding it to Window.Current.Content) most of the UI cost can be skipped and the user isn't likely to see any difference. That's just an idea. I'd be VERY open to suggestions, though. By the way, I have had hours and hours of conversations with the Frame PM for just this thing. We have placed on the backlog of that control a task to expose the page cache so pre-cached pages can be added to it prior to navigation or pulled out of it after navigation. This could offer a potential help, but not much. Further back on the backlog is to change the NavigationState syntax so that it could be constructed by developers and injected, sort of like what you are asking. This is not possible right now - but would give us exactly what you are asking for. These conversations are amazingly long-running to convince these control owners to make changes like this, partly because there are competing priorities from external customers, control vendors and internal consumers, too. So, trust I understand, trust I thought about it, trust I am doing the best thing I can think of at this point, and trust I am open to suggestions you have, too.

**Comment by JerryNixon** [comment]
Understanding that it is not the most efficient (only really in that it does not load the final page until the others have completed), what other downside is there? Also, have you considered that any dependency created by developers on preceding pages (like the view-model) will not be present if we jumped to the front of the queue and didn't recreate the structural context? Consider that last point while also thinking about the "general" developer who wants the platform/framework to just work - and doesn't want to come to this repo and reverse-engineer the code. You know?

**Comment by Quico20** [comment]
@JerryNixon I have two more questions, is T10 V2 gonna have a StartupOrchestrator like T10 V1?(bootstrapper) and second: when is T10 V2 is gonna be available officially? third question: Is there a way I can help to write the wiki with you?

**Comment by jp-weber** [comment]
Thank you Jerry for the detailed describtion. 

At the moment I don't have an idea to do this in a better way. 
 
> Understanding that it is not the most efficient (only really in that it does not load the final page until the others have completed), what other downside is there?

What I only noticed with an older version (two weeks ago) was, that as a user you could see some of the previous pages in the navigation, when the queue is long.

> As for a workaround, here's the only thing I can offer you: if you wait to do your initial navigation that includes the queued pages BEFORE you attach your frame to the visual (adding it to Window.Current.Content) most of the UI cost can be skipped and the user isn't likely to see any difference. That's just an idea. 

That is an interesting idea, which I try out.

>  The other thing to consider is that this behavior is identical to the behavior of Prism on Xamarin.Forms which also navigates the whole stack like the queue. This UWP implementation is coded slightly different, but it behaves the same. 

By the way, I have also said that I forked the project as hobby for Windows Phone 8.1 and it still works brilliant. It is very interesting to know how deep functions work of the template and I learned a lot in the process. 👍

**Comment by JerryNixon** [comment]
Thanks, @jp-weber, be sure and send in some pull requests. Join the team!
