### ISSUE TITLE
MVVM Base Classes

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#18]
Is there a reason the three MVVM base classes (BindableBase, ViewModelBase, and DelegateCommand) are in the projects rather than in the template library?  It would make more sense to me if they were part of the base library, which could be maintained independently of the actual projects using them.

**Comment by darenm** [comment]
The original intent was to have Template10 be somewhat MVVM framework agnostic... I hear what you are saying and we'll discuss - I'm not sure there is a "correct" approach to take though :)

**Comment by JerryNixon** [comment]
This is still in a little bit of transition. I would like your feedback on this, too. We moved them into the library, but in all reality, what we want to do is move them back into Minimal and implement them with MVVM Light instead of our own implementation. 

The reason is, developers who want to use Caliburn or any other library could then just swap the reference to Cliburn and swap the implementation of those classes to Caliburn, too. Repeat that for MVVM Cross or any other MVVM framework. The migration from one framework to another would be super-simple. 

There's no real value in us writing our own micro MVVM framework, no matter how easy it is to do it. At least that is what we are thinking at this moment. I would like your thoughts, for sure.

**Comment by davidezordan** [comment]
I agree with you, Jerry.

It makes sense to not provide another MVVM implementation but to use an existing one like MVVM Light that can be eventually replaced.

**Comment by AmitBhatnagar24** [comment]
I agree with using an existing MVVM implementation. I am confused however in how I would use this template if I downloaded this repo. 

Would I just copy the minimal project into my own solution and modify it as necessary? How would I then swap out to use MVVMLight?

Is there any like 10 line "how to use this" readme or something?

**Comment by JerryNixon** [comment]
You are a step ahead of us on this one. Once we get this up and going, we’ll write the documents. Could use some help authoring if you are willing. As for your first question, an existing solution would not download the repo at all, they would add Template10Library from NuGet (which is not there yet so don’t look today). The only manual implementation would be to update their app.xaml.cs base class to Bootstrapper.

**Comment by JerryNixon** [comment]
Well, it turns out that the custom controls included in the Library simply require a basic set of MVVM implementations. Specifically, the DelegateCommand. This is a class common to most MVVM libraries. I thought I could solve this problem by making the library implementations [internal] and therefore requiring the external implementation by the consuming projects. I have not gotten that to work yet.

**Comment by JerryNixon** [comment]
I think we have a good plan. Gonna close this discussion.
