### ISSUE TITLE
documentation needed - settings service

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#220]
https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-SettingsService-(pre)

**Comment by jbvsmo** [comment]
There are no docs for SettingsService stil... I'm having lots of trouble trying to implement my own settings because they do not seem to save. I always receive the default parameter even after a write.

Are they worth it? I mean, can the settings be stored forever? I can't even read what I wrote, but I suppose it is meant for storage between app runs.

Reading the [source code](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Services/SettingsService/SettingsHelper.cs#L36), only when `Windows.ApplicationModel.DesignMode.DesignModeEnabled` is set, this behavior should occur.
