### ISSUE TITLE
Shell back button still active during busy state

### ISSUE THREAD

**Issue by mizzle-mo** [Windows-XAML/Template10#225]
Everything else works as expected as far as I can tell, but when the busy indicator is active and you use the back button in the shell it seems to cause the navigation to get into a weird state.

**Comment by JerryNixon** [comment]
No it isn't! We fixed that ages ago! Let me see if we lost the fix.

**Comment by JerryNixon** [comment]
I think you are reporting this because you are using the Minimal template in the gallery (which is the right thing to do). I am pleased to tell you that this is corrected in GitHub and we just need to update the gallery. Look here: https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Minimal/Views/Shell.xaml.cs#L33

**Comment by mizzle-mo** [comment]
My bad Jerry, I was indeed looking at the wrong project.
