### ISSUE TITLE
Minimal Template: Layout Issues

### ISSUE THREAD

**Issue by RicardoNiepel** [Windows-XAML/Template10#277]
I'm currently seeing two layout issues at the Minimal template:
1. Because of `controls:PageHeader BackButtonVisibility="Collapsed"` the BackButton is hidden, but the issue with this is, that some space (`Padding`) on the left side of `PageHeader` is missing
2. Because of custom `Background` and `Foreground` values for `controls:PageHeader` at Custom.xaml, if you add `controls:PageHeader.PrimaryCommands` their `Foreground` colors are wrong (black instead of white)

**Comment by dg2k** [comment]
1) Margin="16,0,0,0" is now added for PageHeader control. This will take effect in the next version (1.0.7). Until then, if you want it now, you can add Margin="16,0,0,0" property to PageHeader.

2) Custom.xaml under Minimal template (as well as Minimal template!) is under your control so you can set styles as appropriate. It may be possible for Template10 and Custom.xaml to be out of sync but haven't checked this.

**Comment by RicardoNiepel** [comment]
Thx for fast response.

**Regarding 2) `controls:PageHeader.PrimaryCommands`:**
Do you have a quick/nice solution for this?

**My thoughts:**
I can add

```
<controls:PageHeader.Resources>
    <Style TargetType="AppBarButton">
        <Setter Property="Foreground" Value="White" />
    </Style>
</controls:PageHeader.Resources>
```

But this doesn't fix the hover style (is still black).
However I can replace the template and modify the VisualState - but... this will be a never ending story.

On the other side to use `controls:PageHeader.Resources` is very unhandy, because I cannot set it with a `Style` to minimize XAML.

For me there is something missing like `ItemContainerStyle` for primary and secondary commands or

**(My wish)**
there should be some properties like they exist for `HamburgerMenu`:

```
<Setter Property="NavButtonBackground" Value="White" />
<Setter Property="NavButtonCheckedBackground" Value="White" />
<Setter Property="NavButtonForeground" Value="Black" />
<Setter Property="NavButtonHoverBackground" Value="White" />
```

**Comment by dg2k** [comment]
The following Primary Command set has two examples: the first one a simple with Tapped event handler in codebehind, the second one to handle the command in a ViewModel. Make your pick. You need to add `xmlns:i="using:Microsoft.Xaml.Interactivity"`and `xmlns:core="using:Microsoft.Xaml.Interactions.Core"` in XAML header and provide `MenuClickCommand` command handler method in your ViewModel.

``` c#
    <AppBarButton Label="Download"  Icon="Download" Tapped="AppBarButton_Tapped"/>

    <AppBarButton Label="List View"  Icon="AllApps">
        <i:Interaction.Behaviors>
            <core:EventTriggerBehavior EventName="Click">
                <core:CallMethodAction TargetObject="{Binding Mode=OneWay}" MethodName="MenuClickCommand"/>
            </core:EventTriggerBehavior>
        </i:Interaction.Behaviors>
    </AppBarButton>
```

Yes, you can use the new compile-time binding x:Bind (preferred) instead of Binding as @qmatteoq has indicated.

**Comment by qmatteoq** [comment]
If you can also use the new x:Bind expression added in Windows 10, whih can be used to bind an event with a method in a ViewModel: 

`
<AppBarButton Click="{x:Bind Path=ViewModel.MenuClick}" />
`

**Comment by RicardoNiepel** [comment]
I don't understand how Command binding should help with layout issues?

**Comment by dg2k** [comment]
You said:

> Regarding 2)  controls:PageHeader.PrimaryCommands :
> Do you have a quick/nice solution for this?

Upon revisiting, the above was wrongly interpreted. You're referring to a style but the answer is on how to have a primary command with PageHeader. Sorry for the confusion.

**Comment by JerryNixon** [comment]
As you are solving this problem, I want to share this one detail to remember. The PageHeader in T10 is really just sub-classing the CommandBar object in your Toolbox. This means, the solution you are seeking is a CommandBar solution - this might help you when "binging" for the answer. There's really nothing in T10 that can solve this problem other than what every developer would need to do. 

Let me say another thing. If you were to want to do the same thing to a button - that is, to customize the hover color - you would have to re-template the control to accomplish that. Without looking at the CommandBar, I would assume the same is necessary for what you want. 

One more thing. Since it seems more like you are trying to reverse the color, I wonder if the RequestedTheme property on the control would get you closer to what you want without requiring you to re-template, which is 100% possible and 99% typically overkill.

**Comment by RicardoNiepel** [comment]
Hi Jerry,

I like your solution with `RequestedTheme="Dark"` - already tried before.
But if I apply this at the `controls:PageHeader`, the whole `Page` gets this applied - it seems that this bug still exists: https://social.msdn.microsoft.com/Forums/en-US/7858c7aa-1980-49a7-bfcd-a2d110195fc2/requestedtheme-not-scoping-correctly

I'm now using a _attached dependency property_ to be able to use styles to apply it to all AppBarButtons inside a `controls:PageHeader`.

**Comment by JerryNixon** [comment]
Yuck. Sorry dude.
