### ISSUE TITLE
Does the SettingsService support 'ApplicationDataCompositeValue'?

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#278]
From what I can tell the SettingsService only stores simple types. Does it provide support for 'ApplicationDataCompositeValue' and if not, can we get support for this?

**Comment by JerryNixon** [comment]
Post a snippet here, so I can be sure we're on the same page.

**Comment by calloncampbell** [comment]
I would like to be able to save a composite value. Here is an example of what I mean: https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.applicationdatacompositevalue.aspx 

``` csharp
Windows.Storage.ApplicationDataContainer localSettings = Windows.Storage.ApplicationData.Current.LocalSettings;

// Create a composite setting

Windows.Storage.ApplicationDataCompositeValue composite = new Windows.Storage.ApplicationDataCompositeValue();
composite["intVal"] = 1;
composite["strVal"] = "string";

localSettings.Values["exampleCompositeSetting"] = composite;

// Read data from a composite setting

Windows.Storage.ApplicationDataCompositeValue composite = 
   (Windows.Storage.ApplicationDataCompositeValue)localSettings.Values["exampleCompositeSetting"];
```

**Comment by JerryNixon** [comment]
In the latest version (in GitHub) we are using CompositeValue as the base. This means, implementing it for you is no longer really useful. Not because it is the same functionality, I realize that, but because it automatically receives the increased quota and you can now serialize your data into a simple setting your own way without using the specialized dictionary. This also means that every user of T10 gets this benefit without explaining to them why they need to use a special type. That meets with the design goals of T10. Last thing, I can't imagine why I didn't do this in the first place. Thanks for the issue.

**Comment by calloncampbell** [comment]
Thanks.
