### ISSUE TITLE
NavigationService.SaveNavigation fails on objects

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#280]
NavigationService.SaveNavigation() throws an exception when CurrentPageParam cannot be stored. Exception says that "ToString()" should be implemented. Unfortunately, this is wrong, ToString() is not called here.

```
            try { state["CurrentPageParam"] = CurrentPageParam; }
            catch
            {
                throw new Exception("Failed to serialize page parameter, override/implement ToString()");
            }
```

Also several lines later I get the exception "GetNavigationState doesn't support serialization of a parameter type which was passed to Frame.Navigate":

```
    state["NavigateState"] = FrameFacade?.GetNavigationState();
```

I think the way how Template10 saves the application state should be reworked. Currently it only works when using strings. But UWP10 platform allows to pass objects as navigation parameters.

**Comment by JerryNixon** [comment]
Yeah, I hate this. When you navigate to a page, the best practice is to pass a string or integer that you use to locate the record. It is not a best practice to pass objects. Why? Because SaveNavigationState will only work with simply objects. The solution to your problem is to pass only strings/int. This is 100% not a Template 10 issue, this is just how the Frame state works.

**Comment by JerryNixon** [comment]
One more note, to do what you want with state[] you can serialize it ahead of time.

**Comment by JerryNixon** [comment]
Let me just vent on this a little more. Why did they make it so that you could pass objects only to make that scenario break things? There are some cases where it is important to pass an object. The first is protocol activation to return a result. This requires that the resulting page have a reference to the launch argument in order to return a value. However, I can solve this with Template 10, using our Bootstrapper.SessionState dictionary. You can, too. 
1. Bootstrapper.SessionState[key] = value
2. NavServices.Navigate(type, key)
3. param = Bootstrapper.SessionState[key]

Make sense?

**Comment by schuettecarsten** [comment]
The SessionState is persisted when App is suspended?

**Comment by JerryNixon** [comment]
No it is not. Which means, you would want code that, if it is not present, would load it from scratch otherwise. Make sense? It's basically saying "use this data unless it isn't there"

**Comment by schuettecarsten** [comment]
Jerry, I will send you a pull request soon that will allow users to override two methods in bootstrapper/app to serialize/deserialize custom objects here.

**Comment by schuettecarsten** [comment]
I've send a pull request today that adds two protected method to allow users to implement their own solution to serialize objects - if they want: https://github.com/Windows-XAML/Template10/pull/388
