### ISSUE TITLE
PageHeader User Control

### ISSUE THREAD

**Issue by UeliSchwarz** [Windows-XAML/Template10#3]
cs file is missing

**Comment by ShiroYacha** [comment]
Yeah, also has a missing NuGet package on diagnostics.

**Comment by levarius** [comment]
I'm also unable to build Full or Blank. TODO seems to build and run

**Comment by mkstephenson** [comment]
Also unable to build the project due to this missing cs file, it seems it was never included in the first place when the PageHeader control was commited

**Comment by ernonewman** [comment]
Same here

**Comment by RonnyGydar** [comment]
Same problem here

After watching the http://www.microsoftvirtualacademy.com/training-courses/a-developers-guide-to-windows-10 videos I was hoping these build issues would be resolved soon, so I have not dug into how to get around them.

Since it has been over 2 weeks since last update, I will for now try to just get it to build on my PC, since from the developers-guide-to-Win10-videos it seemed to solve elegantly 90% of the stuff I end up doing over and over again when I make apps for the Store.

**Comment by RonnyGydar** [comment]
I downloaded this slightly older version from June 4. (titleled "Fixing TextBlock") instead
https://github.com/Windows-XAML/Template10/tree/b6966b663b37af779e55ac9ef6ff76e4aefc72ff

That version builds without any errors :)

**Comment by JerryNixon** [comment]
We are updating the templates right now. There are changes coming to the project templates infrastructure we are dealing with, too. Template 10 will not RTM until Windows 10 is RTM.

**Comment by ghost** [comment]
When do you plan to push the changes?
Also when template10 is RTM it will be available as a vsix or it will be part of vs2015?

**Comment by RogerSpiess** [comment]
Jerry, please, can you just add the missing PageHeader.xaml.cs file into the blank project? Thx in advance!

**Comment by JerryNixon** [comment]
Okay. The first rush of changes are in place. The main change is the extraction of the common classes into an external library. Because of forthcoming changes to the NuGet system, this cannot be introduced as a project template for a few weeks. That being said, I think the Blank and minimal projects are 100% ready for you to test, and I want to thank you all for testing it.
