### ISSUE TITLE
Splitview not autoclosing after selection

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#30]
In Minimal, when selecting an item from the splitview it should autoclose. Just like MSN Finance.

**Comment by JerryNixon** [comment]
I believe it already does this. Could you verify with the latest build?

**Comment by joshberry** [comment]
In my testing (commit e5e754046b), sometimes it closes and sometimes is doesn't. For example, if I'm on the home view and click the settings icon, I'm taken taken to the settings page but the SplitView pane remains open. In other situations, it closes automatically as expected.

On a related note, the SplitView used to remain closed when clicking on one of the icons in compact view but now it opens and you have to click somewhere to hide it. Is this by design or an issue? Seems awkward to me.
