### ISSUE TITLE
Incompatible with Microsoft Band

### ISSUE THREAD

**Issue by ViktorBergman** [Windows-XAML/Template10#346]
This is possibly more related to the implementation of Microsoft Band but I'll raise it anyway if it might be of interest. The issue is that you cannot add tiles to the band whilst using Template10 due to the implementation of the Shell and Frame. Theoretically this should also be an issue for other API's that's implemented similarly.

Here's a workaround: http://stackoverflow.com/questions/32876061/how-to-use-the-ibandclient-addtileasync-method-within-an-mvvm-project-such-as-te

**Comment by rickgregory1905** [comment]
This incompatibility continues to cause me much grief. After reviewing the Caliburn implementation as suggested, I have tried equating the "Window.Current.Content" to the template10 WindowWrapper.Window.Content. Does that sound appropriate?

**Comment by rickgregory1905** [comment]
1. Having added public UIElement ShellHolder { get; set; } to the App class.
2. Added a button to the MainPage.xaml.cs with the following inside the click event
   ((App)Application.Current).ShellHolder = Window.Current.Content;
             Frame rootFrame = Window.Current.Content as Frame;
             if (rootFrame == null)
             {
                 rootFrame = new Frame();
                 Window.Current.Content = rootFrame;
             }
             rootFrame.Navigate(typeof(FrameView));
             Window.Current.Activate();
3. Added a new Blank xaml page with a button whose click event contains:
           var app = (App)Application.Current;
           if (app == null) return;
           try
           {
               Window.Current.Content = app.ShellHolder;
           }
           catch (Exception ex)
           {
               Debug.WriteLine("Broke: {0}", ex.ToString());
           }
           Window.Current.Activate();

Results in the following failure when trying to make the Window.Current.Content assignment. Any recommendations would be appreciated. 

"System.ArgumentException: An item with the same key has already been added.\r\n   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)"

**Comment by JerryNixon** [comment]
I will fix this when I am back from vacation.

**Comment by FrayxRulez** [comment]
A solution can be to create a custom Shell`Frame` instead of ShellPage. So libraries that rely on a Frame as Content of Window.Current should work fine

**Comment by JerryNixon** [comment]
@ViktorBergman , I thought the answer would be a simple as nesting the Shell in a Frame, but that doesn't work, does it? Shell requires NavigationService as a parameter to its constructor. This, of course, got e back on the trail to create Navigate(instance) in the FrameFacade. The problem is, of course, this is grossly complex to accomplish. The only working sample (in the Winrt XAML Toolkit) requires using a custom frame and a custom page, which introduces a new nuisance layer to Template 10 that I don't want to include. 

@rickgregory1905's ideas were pretty good. 

The reason a custom frame is necessary is because it must support the ability to inject a new page into the current presenter. The reason a custom page is necessary is because it must support the ability to inject the parent frame into the Frame property. There are other reasons, but those are some of the core reasons you need to sub-class the living daylights out of the thing to accomplish it.

That leads me to conclude your current workaround is the best solution until I come up with something else. Ideally, I would simply like to create a Navigate(instance). Another possible solution would be a `object Bootstrapper.Activate(Content)` method that injects the passed in content onto the stack, returning the current content so you could persist it. This would only act as a helper method, so there's (again) no real reason to add to the complexity of the API just for this scenario that is at its heart just wrapping your workaround solution.

The real solution, of course, is for the Band SDK not to act so stupid, right? What a crazy assumption. 

Another possible solution would be to take away the NavigationService parameter in the Shell constructor and let it call Bootstrapper.Current().NavigationService instead. That would work in 99% of the cases, but in any app where the developer wanted to use the Shell, but NOT use the default NavigationService, then he would be screwed. You might argue that is pretty rare and T10 is already only catering to the 80%. That's a good point.

That solution would allow me to nest Shell in a Frame, navigating to its type. Then everything should work just fine. Except for some detail I am forgetting right now. 

Here's another solution, and I like this one. Just before calling the SDK API, you could call NavigationService.Open() which would launch a new Window. And since the SDK called Window.Current.Content, it would retrieve the content of the new Window, which will automatically be a Frame, since that is how the Open() method works. Then, the first page to which you open could be the one to call the API that does the crazy navigation. It could set a static variable, and if it has value, then you know it is being redirected back from the SDK and you can signal to close the Window with WindowWrapper.Current().Close(). This would get it done, and the user might not ever know anything kinky was going on under the covers. 

Again, just brainstorming. 

As a follow-up, though, another interesting and MAJOR solution might be to change the base type of Shell from Page to Frame as @FrayxRulez suggested. This might be a good idea, to be honest. This is, by the way, how it is done in the MSN Photos app that ships with Windows 10. I considered this in the early life of Template 10, but rejected it because... well, it's been to long to remember. I think it was because I wanted a design-time experience with Page. But it's another possible solution.

**Comment by ViktorBergman** [comment]
The new Band SDK (1.3.11121) released on december 10th shows a messagedialog instead of navigating to a new page so this issue requires no more workarounds.
