### ISSUE TITLE
Pane width not working with nuget package

### ISSUE THREAD

**Issue by aline-almeida** [Windows-XAML/Template10#353]
Although this works fine in the minimal project itself, when using the nuget package, no matter what value I set in the PaneWidth, it stays with the default 220.

**Comment by JerryNixon** [comment]
Suggestions?

**Comment by JerryNixon** [comment]
Does everyone in @Windows-XAML/community see the same behavior?

**Comment by callummoffat** [comment]
I'm seeing this behavior too, however, I have noted the following:
- It seems that the value of PaneWidth is perpetually stuck on the XAML value of PaneWidth in Shell.xaml. So, it will be stuck on 220px by default, but you can change this.
- However, the bug is still there; the pane width cannot be modified.

**Comment by JerryNixon** [comment]
This is resolved in 1.0.9

**Comment by JerryNixon** [comment]
I will release 1.0.9 this week

**Comment by RafaelPlantard** [comment]
Awesome :+1:
