### ISSUE TITLE
Manually updating HamburgerMenu highlighted button

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#372]
Is this possible?

I've tried calling the below from my ViewModel, but it doesn't update:

```
Views.Shell.HamburgerMenu.HighlightCorrectButton(typeof(Views.MainPage));
```

Background is that I am navigating to a page that doesn't have a specific button in the menu, but it should share the icon of another page.

**Comment by JerryNixon** [comment]
I wonder if you should try MyButton.IsChecked = true instead of this approach?

**Comment by JerryNixon** [comment]
The approach you are showing above will never work as HighlightCorrectButton ultimately searches for the PageType and Parameter and there are just too many variables otherwise, using IsChecked will un-check the other buttons while you are at it. Be sure and call it AFTER navigation is complete. Why? Because Frame.Navigated calls HighlightCorrectButton internally.

**Comment by JerryNixon** [comment]
Now that I see it, I think HighlightCorrectButton should not have been public.

**Comment by darshanrampatel** [comment]
Thanks - will give this a go and let you know.

**Comment by JerryNixon** [comment]
Okay, open a new issue if it fails.
