### ISSUE TITLE
x:Bind TwoWay does not update from OnNavigatedFrom

### ISSUE THREAD

**Issue by tpspencer** [Windows-XAML/Template10#373]
If you have a textbox x:Bind ViewModel.MyObject.Fname Mode=Twoway and you make a change to the data in the textbox and then click the "back arrow" to navigate away, the ViewModel's property is not updated.

If you click any other control like a button the data is updated.

Is this a bug?  If not how can I get the bindings to update when the user navigates away?  I do not want to add a "Save" button.

**Comment by byrialsen** [comment]
Hi 
You have to change UpdateSourceTrigger in the binding like:

```
Text="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
```

To do something like "save" when you leave page just override `"OnNavigatingFrom"` in your viewmodel. You should ofcourse inherit from `"Template10.Mvvm.ViewModelBase"`

**Comment by tpspencer** [comment]
UpdateSourceTrigger=PropertyChanged is not available in x:Bind ?

Yes I am using OnNavigatingFrom and inheriting from ViewModelBase.
Thank you.

**Comment by byrialsen** [comment]
Ok, sorry. You are right that `UpdateSourceTrigger` is not supported by `x:Bind`. But then you can use the regular `binding` instead. I think it is completely legal to combine the two binding mechanism.

Check bottom of this page. (https://msdn.microsoft.com/en-us/library/windows/apps/mt210946.aspx)

**Comment by tpspencer** [comment]
Yes, I have read that page entirely.  Still looking for a solution by using x:Bind to keep all of the benefits it affords.  If you think of anything let me know.

Jerry or Darren do you have any suggestions?

**Comment by JerryNixon** [comment]
Yeah, @byrialsen is correct. This is the expected behavior of x:Bind because it does not support UpdateSourceTrigger=PropertyChanged. As a result, any TextBox using x:Bind will not have updated the underlying model when OnNavigatingFrom/OnNavigatedFrom are called - if that TextBox currently has focus. This is the scenario I assume you are experiencing. 

Developers overcome this limit by calling Page.Bindings.Update() when they want to force updates. This is fine, except from a view-model it means you need to somehow message to the page to call this method. It works. But it's messy. So, @tpspencer, you have inspired me to update Template 10. I have added the code that forces Page.Bindings.Update() before calling OnNavigatingFrom(), which precedes OnNavigatedFrom() in the view-model pipeline in Template 10. 

I have tested that the method is called correctly. It was tricky because Bindings is a private field, unique to each Page. It took some fancy reflection, but it works like a charm and the problem you are seeing should be resolved for you and every developer using Template 10. Good work. Also, please note that this will be pushed out in 1.0.9, which might be a week away.

**Comment by tpspencer** [comment]
Jerry, that is great news.  
Thank you.
Terrence

**Comment by lolluslollus** [comment]
That is bollocks, nothing updates, even if you call Bindings.Update(), and I am on 1607 .14393.whatever. These basic things are the reason why we have all gone away to Apple.
The only solution is to use the old binding, maybe with ElementName=me.
