### ISSUE TITLE
Application crashes at loading phase when change window size

### ISSUE THREAD

**Issue by Nab0y** [Windows-XAML/Template10#38]
Application crashes at loading phase (splash by default) when the user changes the window size.

```
    public static Visibility CalculateBackVisibility(Frame frame)
    {
        // by design it is not visible when not applicable
        var cangoback = frame.CanGoBack; // Chash here
```

Since this time frame still null

**Comment by JerryNixon** [comment]
Not sure why this would occur. I added.

``` csharp
// in some cases frame may be null, esp. race conditions
if (frame == null)
    return Visibility.Collapsed;
```

**Comment by eloekset** [comment]
If others are using ["Advanced View States for Windows 10 apps"](http://www.codeproject.com/Articles/896974/Advanced-View-States-for-Windows-apps) this bug causes the app to crash on startup because DeviceTrigger.Initialize() tries to get access to Shell.Frame, which is null. Here is a tip to workaround that issue: http://www.codeproject.com/Articles/896974/Advanced-View-States-for-Windows-apps?msg=5147438#xx5147438xx

It would be great if someone could find a way to fix the Shell.Frame = null bug, to avoid similar issues.
