### ISSUE TITLE
10586 Release mode, fails to build

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#383]
When I try and build a Template10-based app in Release mode when targeting SDK build 10586, the app fails to build with the following error:
Internal compiler error: Access to the path 'C:\Users\Callum Moffat\Documents\Visual Studio 2015\Projects\Petrolhead\Petrolhead\obj\x86\Release\ilc\intermediate\ILTransformed\Newtonsoft.Json.ildll' is denied.
I think it might be related to JSON.NET, but I wanted to check with other Template10 users to see if they had received similar behaviour, and whether there is any known workaround.

**Comment by JerryNixon** [comment]
Of course this needs to be addressed. But what do you think is the best timing to support UWP 1.1? Should I wait a month or two until everyone is upgraded? Should I branch and create a second version? We are still mulling over what to do.

**Comment by callummoffat** [comment]
I think that, at least temporarily, there should be a second version. Some people will want to support UWP1.1 technologies, others may prefer to stick with the original 10240-supported version. I know I'm in the former camp. Two versions makes sense, at least in the short term.

**Comment by callummoffat** [comment]
Also, there is another issue that is a real problem. If I switch my targeting back to UWP1.0 (SDK 10240), the compilation still fails with the same stupid error. Nothing I try lets it build once SDK targeting has been modified. Any ideas, Jerry?

**Comment by AmitBhatnagar24** [comment]
...note that Enterprise editions of Win10 10240 did not automatically get the update to 10586.. we probably have to go the two version route if not properly backwards compatible.

**Comment by JerryNixon** [comment]
The plan is to rev T10 with UWP. Since UWP is now in version 1.1 (or 10586), my plan is to release one last 10240 release of T10 as 1.0.9 and stop there. Then, my plan is change our version numbering scheme to 1.10586.n (for example 1.10586.1, 1.10586.2, 1.10586.3) so that the version of T10 is obviously tied to the version of UWP for which it is intended. If we ever commit a significant update to T10 then I think we could look into a scheme like 2.10586.1. You would basically understand it to be T10ver.UWPver.Build, which seems pretty clear to me - it also allows us to support the same UWP version in multiple versions of T10. So, to respond to your comment, yes, we will branch. I will release one last update to 10240 and from that point forward assume all development is 10586, and update the templates likewise. Then as we move forward, repeat this cycle. As UWP is updated, so will be T10 - releasing the final update for the previous UWP, then branching that, then maintaining MASTER as the current UWP version. It doesn't matter to me that Enterprise edition of Windows 10 does not update. Template 10 is for the majority, not for all. Of corporations using Windows 10 Ent, I would assume 80% will update in a reasonable time. Meanwhile, every other version of W10 will update almost immediately. That means chasing old versions would be an edge case and that violates the basic premise of T10. That being said, I think it makes sense to let a few months pass before we make this break. In this case, since it was Nov, it makes sense to do it around Jan. I will release 1.0.9 in the next few days and do nothing with 1.10586.1 until next calendar year. When we get the next rev around June, I might wait until something like August or so for a major rev. This will let machines and developers rev, but it will also mean that developers wanting to develop in advance of availability will not be able to take advantage of that in T10. So, what we might do is branch early, just not push to NuGet until that delayed time. Does it sound like I am still thinking this through? I am.

**Comment by callummoffat** [comment]
So, I'll be able to add compatibility with 10586 sometime in the next few weeks, but the Nuget library won't gain compatibility until next year.

**Comment by callummoffat** [comment]
How would I make a custom version of T10 that is compatible with 10586?

**Comment by callummoffat** [comment]
Update: I just updated my app to target 10586, by using the Github sources. It's working like a charm.
