### ISSUE TITLE
Keeping the state until the page is in navigation stack

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#403]
Hi Jerry,
I'm thinking to add small enhancement to FrameFacde - optionally to keep the state of pages that exist in navigation stack. I think it could be helpful when we need to restore the page state after back(for)ward navigation without using NavigationCacheMode.

**Comment by JerryNixon** [comment]
This is more complex than you might ever imagine, dude. 
How about using BootStrapper.SessionState instead.

**Comment by mitkodi** [comment]
Using SessionState will lead to different user experience when an app is suspended-resumed or suspended-terminated-activated. In first case the state of a page could be restored from SessionState but not in the second.

I see that FrameFacade.ClearFrameState is called initially and when we navigate to a new page, so I'm thinking to replace it with something like that:

``` javascript
public void PurgeFrameState(bool clear)
{
    FrameStateContainer().Values.Clear();// ?

    if (clear)
    {
        foreach (var container in FrameStateContainer().Containers) {
            FrameStateContainer().DeleteContainer(container.Key);
        }
        pageStateContainers.Clear();
    }
    else
    {
        var currentPageType = Frame.Content.GetType();
        var currentPageKey = GetPageStateKey(currentPageType);
        if (FrameStateContainer().Containers.ContainsKey(currentPageKey))
        {
            FrameStateContainer().DeleteContainer(currentPageKey);
        }
        pageStateContainers.Remove(currentPageType);

        foreach (var container in FrameStateContainer().Containers) 
        {
            if (!Frame.BackStack.Any(e => GetPageStateKey(e.SourcePageType) == container.Key)) 
            {
                FrameStateContainer().DeleteContainer(container.Key);
                var pageType = pageStateContainers.Keys.Where(key => GetPageStateKey(key) == container.Key).FirstOrDefault();
                if (pageType != null) {
                    pageStateContainers.Remove(pageType);
                }
            }
        }
    }
}
```

**Comment by JerryNixon** [comment]
Walk me through a few scenarios:
1. Navigating from DetailsPage to DetailsPage with diff param.
1. Navigating from DetailsPage to DetailsPage with same param (refresh)
1. Navigating back to ListPage from DetailsPage after a data edit
1. Navigating to any page with a non-serializable parameter 

Let me talk through the SessionState approach. The idea is to pass a simple key to the target page. The idea is that it can do one of two things. 1) it can use that key to find a certain record in the SessionState, or 2) it can not find that key in SessionState and use a Repo/Service to fetch it. The idea is that I can nav to pages with only simple keys, which are preserved in the NavState when the app is suspended, and then passed back to the page when it is resumed. If it is a fast-resume where the app was in memory, it can find the existing record in SessionState. If it is a terminated-resume where the app was unloaded, it will not find it, but knows how to load it with the supplied key. 

In this scenario, it is 100% reasonable that the Repo/Service caches the data in some way to account for the terminated-resume scenario so it can hand data back to the view-model quickly. 

SessionState is not my favorite part of T10, by the way. It is ideal to me that we only pass keys and that those keys are they way by which we retrieve from a repo/Service. The end. All this object persistence is wonky to me, but I also recognize that there are edge cases where it might be useful - one of them might be through popup search results. I don't know. But it's bound to drive developers to use it in normal use cases and not just edge cases, and I hate that.

I don't ever have plans to use SessionState or pass non-serializable objects to pages. The PageState (is that what we call it?) is already persisted across suspend/resume so that's handled and it's nice. Doing what you are doing is just encouraging a behavior that I believe is actually the overall wrong approach to UWP. I think this because it adds considerable complexity to keeping objects across views in sync. And because it relies on so much memory.

That being said, I am open to being convinced otherwise.

**Comment by mitkodi** [comment]
I agree that in scenarios where we want to sync related pages (e.g. master details, if I correctly understand your scenarios) we cannot relay on the previous state of the master (even we have it) when we navigate back to it, because it could be invalidated by the detail page. About the last scenario (navigating to a page with non-serializable parameter, which is a bad idea) I don't see how it could be related to what I suggested.
I think that keeping the state of all pages in the stack, not only of the last new navigated page, could be helpful in scenarios where we have in the stack unrelated pages (or at least the last one is an standalone page, unrelated to the others). For example, if we have an data entry form page from which we navigate to another page (e.g. map, settings, help page, etc.) from which we could go to a web page handled by the browser app and finally when we find all we need to complete the data entry form, why we should not be able to restore its state if the app has meanwhile been terminated.

**Comment by JerryNixon** [comment]
I am going to close this. You can always submit a PR or more specific Issue.

**Comment by bigtlb** [comment]
Thanks for the idea.

Assuming you are not navigating to multiple different instances of same View, these helper functions are what I am planning on using.

`````` csharp
    public abstract class ViewModelBase : Template10.Mvvm.ViewModelBase
    {

        /// <summary>
        /// Function to be called in OnNavigatedTo.  Retrieves session state if it exists and we are navigating back, then clears it.
        /// </summary>
        /// <param name="mode"></param>
        /// <param name="state"></param>
        /// <returns></returns>
        protected IDictionary<string, object> GetCombinedState(NavigationMode mode, IDictionary<string, object> state)
        {
            var cacheKey = $"StateCache-{this.GetType().Name}";
            if (SessionState.Contains(typeof(IDictionary<string, object>), cacheKey))
            {
                if (mode == NavigationMode.Back)
                {
                    state = this.SessionState.Get<IDictionary<string, object>>(cacheKey);
                }
                this.SessionState.Remove(typeof(IDictionary<string, object>), cacheKey);
            }

            return state;
        }
        /// <summary>
        /// Function to be called in OnNavigatingFromAsync to provide an alternate sessions state, when not suspending.
        /// </summary>
        /// <param name="state"></param>
        /// <param name="suspending"></param>
        /// <returns></returns>
        protected IDictionary<string, object> SetCombinedState(IDictionary<string, object> state, bool suspending)
        {
            var cacheKey = $"StateCache-{this.GetType().Name}";
            if (!suspending)
            {
                if (SessionState.Contains(typeof(IDictionary<string, object>), cacheKey))
                {
                    this.SessionState.Remove(typeof(IDictionary<string, object>), cacheKey);
                }
                state = new Dictionary<string, object>();
                this.SessionState.Add(typeof(IDictionary<string, object>), cacheKey, state);
            }

            return state;
        }
    }```
``````

**Comment by bigtlb** [comment]
My use case involved have 3 fields and a submit button.  If the user navigates to settings or about pages, then backs up, they will lose the fields that haven't been submitted.

**Comment by mitkodi** [comment]
What if the app has been suspended->terminated before navigating back from settings or about pages?

**Comment by bigtlb** [comment]
It would have been wiped out anyway.  All existing PageState is cleared on any New Navigation in the current code.

If you think you are saving state when you proceed to the next page using the state argument on OnNavigatingFrom(), it won't be there when you go back, unless you put it in SessionState.  These functions just replace the PageState dictionary with a SessionState dictionary when not suspending, and when you go back to the page (which is the only scenario I care about).

**Comment by mitkodi** [comment]
In this case, I think the simplest way is to just put the current object you are editing in SessionState and retrieve it directly from it or repository without adding page level dictionary to SessionState. In this case the current object will be globally discoverable and could be used/shared between different pages.

**Comment by bigtlb** [comment]
You can do whatever you would like.  I was just providing an example of how I am swapping out PageState for SessionState when not suspending, since PageState won't survive the GoBack operation anyway.

@JerryNixon has stated he doesn't want to implement the frame stack teardown logic that was in the original Visual Studio templates.  I respect his reasoning, and offered this as an alternative for those times when you really want to preserve state between go forward/ go back, but don't want to have to make a totally different code path from what you are already doing for Suspension.

My one complaint with the OnNavigatedFrom is that the state argument looks like it works when NOT suspending.  But, it is totally throw away code.  It would almost be better to return a null as that parameter when NOT suspending, to prevent developers from thinking it is useful.

**Comment by mitkodi** [comment]
To avoid misleading we can have:
- two **OnNavigatedFromAsync** methods (one with state parameter and another without).
- **OnNavigatedFromAsync()** and **SaveState(IDictionary<string, object> state, bool suspending)** which will be called first if the PageState won't be cleared.
