### ISSUE TITLE
Deserialization problem with HamburgerMenu.xbf

### ISSUE THREAD

**Issue by SWilkov** [Windows-XAML/Template10#408]
I'm using Template10 in a live app and all was working well but now I'm getting this weird error message when starting the app.

WinRT information: Cannot deserialize XBF metadata type list as 'HamburgerMenu' was not found in namespace 'Template10.Controls'. [Line: 0 Position: 0]

I'm using Template10 version 1.0.4 I have tried updating to 1.0.8. I've also deleted bin, obj folders and rebuilt but its still failing with this exception. Has anyone else experienced this error?

**UPDATE**
Project doesn't build now with error

1>MakePri : error 0x80073b0f: Processing Resources failed with error: Duplicate Entry.
1>MakePRI : error 0xdef00532: Conflicting values for resource 'Files/Template10Library/Controls/HamburgerMenu.xbf'

My Windows 10 version is 10586

**Comment by JerryNixon** [comment]
Give me a little more information. Are you using version 1.0.8 in NuGet or are you referencing the project, or are you creating c:/local-nuget?Does this error occur when you are attempting to build your project or when you are building the T10 library? This error, by the way, is pretty common in this scenario: creating a NuGet package and failing to copy the XBF from the library source into the pack. This was an early dilemma for us when we were creating T10 but I have not seen this error in a long time. 

We resolved this by ensuring a few things. 1) In the properties of the T10 library, in the Build tab, ensure "Generate Library Output" is checked. As an aside, I just checked my current clone and this was NOT checked like it was supposed to be (which may be your problem). And 2) There is a section in the nuget.cmd (in the Library's Nuget folder) that reads something like this:

```
echo Copy \%TARGETNAME%\[Library] (incl. XAML)
xcopy.exe "%TARGETDIR%%TARGETNAME%\*.*" "%NUPKG%\lib\%TARGETNAME%\" /s/e/y >nul
```

This section is responsible for copying the output of the library generated by the checkbox in item number 1 (above) into the NuGet pack. These both are required to get the XBF into the NuGet pack. Why does it need to be in the NuGet pack, because (with Windows 10) we are looking at version 2 of the XAML Binary Format (XBF) and it is required in order to execute. However, you might also note that we are copying over the XAML files, too. These are redundant, no? Yes, except they enable the designtime experience and do not add a cost to our library because we also include the XBF. 

One intent of the XBF, by the way, is that pre-compiled XAML is considerably faster to execute (especially on first use). Including them gives us a nice start-up bump, but they are also required - we get the bonus, but we are just doing what we have to do, too. :) 

This all making sense? See if checking that checkbox helps you. I will also commit an update to the csproj so it is automatically checked, but I am not 100% sure if that is a project setting or a user-project setting. Anyway, give it a try @SWilkov

**Comment by SWilkov** [comment]
Hi Jerry thank you for the detailed response much appreciated. 
Originally my app in the store was using Template10 1.0.4 installed via nuget package. Since the error I have updated to 1.0.8 again using nuget. I since referenced Template10(library) directly so that I was able to tick the "Generate library output" box you suggested above in Build tab. The good news is the original error has disappeared the bad news is that I'm getting a new NullReferenceException from BootStrapper.cs or more specifically  await InitializeFrameAsync(e); in InternalLaunchAsync method.

The strange thing here is that the app was working absolutely fine live in the Store until yesterday and the only thing that may have changed is a Windows 10 update on my laptop. I test before release by sideloading in powershell each time and it definitely worked. Very strange. 
I will need a rethink here as I have no idea what is going on? Be interested to see if anyone else is seeing this issue. Thanks again

**Comment by JerryNixon** [comment]
What are you doing in your OnInit in Bootstrapper?

**Comment by SWilkov** [comment]
Heres my Oninit from App.cs which inherits from Bootstrapper

```
 var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);

        //Setup pages for navigation
        var keys = PageKeys<Pages>();
        keys.Add(Pages.Recipes, typeof(Views.Recipes));
        keys.Add(Pages.Recipe, typeof(Views.Recipe));
        keys.Add(Pages.Seasons, typeof(Views.Seasons));
        keys.Add(Pages.DietTypes, typeof(Views.DietTypes));
        keys.Add(Pages.About, typeof(Views.About));
        keys.Add(Pages.Search, typeof(Views.Search));
        keys.Add(Pages.Favorites, typeof(Views.Favorites));

        //Speech setup
        const string uwpvcdPath = "ms-appx:///Assets/Voice/SAVoiceCommands.xml";
        var vcdUri = new Uri(uwpvcdPath);
        var file = await StorageFile.GetFileFromApplicationUriAsync(vcdUri);
        await VoiceCommandManager.InstallCommandSetsFromStorageFileAsync(file);

        //Notification setup
        try
        {
            NotificationPush.UploadChannel();
        }
        catch (Exception e)
        {
            //likely offline so dont do anything regarding notifications
        }

        //in app purchases
        var licenseInformation = CurrentAppSimulator.LicenseInformation;
        Window.Current.Content = new Shell(nav);
```

Shell sets the HanburgerMenu NavigationService. Thanks

**Comment by SWilkov** [comment]
Hi Jerry think the problem is with my Notifications not Template10 as your fix above has solved my original issue. Thanks a lot for your help

**Comment by callummoffat** [comment]
I've been having this issue too. Enabling library layout does nothing to fix this. I'm running build 10586 with VS2015.1

**Comment by 9kon** [comment]
I'm having this issue too using Nuget 1.0.8 and VS2015.1 is arrived after the update to VS2015.1 wasn't there before, but don't know if that is a coincident.

**Comment by 9kon** [comment]
For me it was a problem with VS2015.1 worked on another computer with VS2015
