### ISSUE TITLE
Question about adding existing controls to a Template10 page?

### ISSUE THREAD

**Issue by alanb6448** [Windows-XAML/Template10#413]
Hi,
I have a user control written quite a while ago that I have placed on a template10 page. Will that control automatically inherit the pages view model as its own view model ?  Should I create a view model specifically for the control and pass common data to it on initialisation or x:bind its  datacontext to the parent pages datacontext? Still getting my head around the concepts involved.

I tried adding the pages viewmodel as the data context as below

```
<MyControls:PathDisplay x:Name="BazleyPathDisplay" >
       <MyControls:PathDisplay.DataContext>
                        <vm:BazleyPageViewModel />
         </MyControls:PathDisplay.DataContext>
 </MyControls:PathDisplay>
```

builds with no errors but squiggles under the above and message 
Object reference not set to an instance of an object.

I was looking to share viewmodels is this frowned upon/wrong should I replicate stuff in both view models instead by inheritance from a common base class?

Alan

**Comment by JerryNixon** [comment]
Here are some rules of thumb to remember. First, the technical question. The data context set for the page will flow automatically down to child controls because of how dependency properties work in XAML. As for the view-model, it is not impossible to justify a view-model specific to a custom control, but it is very unusual. Typically, you create a single view-model for each view - and, conversely, you create a single view for each view-model. That being said, it is sometimes appropriate to have a nested view inside a larger view - especially when that nested view is repeated or reused in other locations in the app. Typically, in those cases, the nested view's view-model is a property of the page's view-model. This approach means that every view-model, regardless of how many may be on a page, is accessible from a single point of entry, the data context of the outer-most page. 

Here's an illustration. My MainPage has a MainPageViewModel. But there is a reused view (think user control, in this case) that handles the user's profile that is present on every page. This nested view is called the UserView and inherits from user control instead of page because it is never intended to be navigated to by itself. It has a view-model called UserViewViewModel, and there is a property on my MainPageViewModel called UserViewViewModel (MainPageViewModel.UserViewViewModel). Accessing either view-model or any property in them is easily accomplished by accessing the MainPageViewModel that is set to the page's data context. Moreover, the UserView.DataContext is set to {x:Bind ViewModel.UserViewViewModel} or {Binding UserViewViewModel} if you are using classic binding. 

I hope this helps.

**Comment by JerryNixon** [comment]
I thought I might also comment on why there is one to one for views and view-models. This is really a convention and not a hard rule. Doing this makes your app far more simple, and gives you the flexibility to expand a view-model for the sake of additional view capabilities without strange code to hide that functionality from views that should not have it. 

As for using a base class, this is fine. Derived classes are a solid part of C#/managed development, so there is no reason to avoid it. That being said, try to avoid inheriting from another view-model. Why? Well, for the same reason as above. If the base view-model needs functionality that is not relevant to the derived sub-classed view-models, then you start to muddy the waters again for no reason. Creating instead a UserViewModelBase that has all the user code which is reused in several view-models makes plenty of sense.  

That being said, I want to add one thing. Repeating code is sometimes more effective than abstracting your implementation. This make sense? If you want a base class, but you also need to change some subtle parameters on the methods you use, and now you need an interface for the sake of unit testing... you just need to consider if you are making your app better or just more abstract, which is typically counter to the maintainability of your code.

Those are just words to think over, nothing there is a solid rule.

**Comment by JerryNixon** [comment]
Some more pontification. When you are adding functionality to your view-mode at such a volume that you are considering a base class, you might be going down the wrong path, not using view services like they are supposed to be used. A view service is basically a "service" in which a lot of functionality is encapsulated. Because of view services, a view-model can have very little logic. Meaning, with view services, you can repeat your view-models that have similar functions without much of a care because those view-models oursource their logic to view services. 

I hope this helps you think it through.

**Comment by alanbattersby** [comment]
Thanks for that. My program is about generating gcode to get my cnc to  cut various types of pattern. I have 5 different types each on it's own page. But each page contains a view of the path generated by the pattern. The path view is the same for all and is my common control. However the data for each pattern type is unique to that type but there is some commonality. Hence the need for a different view models for  each page . I used a base view model class so that my database service would be available to all the derived view models.  Also I know that I am guilty of abstracting as much as I can.  Probably too much as is becoming apparent as I rewrite this code I originally wrote several years ago 

Finally I do not think that this is the best forum for my questions but do not know where else to try.  Thanks for being so patient
