### ISSUE TITLE
System.ArgumentException after resuming

### ISSUE THREAD

**Issue by frostieDE** [Windows-XAML/Template10#438]
When resuming an app that utilises Template10, the app crashes with a `System.ArgumentException` with message `TODO`. After some debugging, it seems the error occurs [here](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Common/BootStrapper.cs#L384). However, I am not sure why this error occurs, but it is reproducable on my own apps. Somehow, the sample app works but I am not sure why. 

Maybe one of you can take a look what is wrong? :)

**Steps to reproduce:**
1. Download the attached application.
2. Deploy the app to either an emulator or a device and start the app in debug mode from visual studio.
3. Now suspend\* the app using "lifecycle events"\* in visual studio
4. Now tap on the application icon in the application list on the phone.
5. The app will crash with an unhandled `System.ArgumentException`

BTW: It does not matter if deploying the app to build 10240 or 10586. Also, this problem occures with the latest NuGet build as well as when linking to the library from source (latest master branch).

*) I am not sure how the English labels are titled - in German it is "Anhalten" and " Ereignisse des Lebenszyklus" ;-)

[App1.zip](https://github.com/Windows-XAML/Template10/files/74738/App1.zip)

**Comment by frostieDE** [comment]
Update: After some investigation, it turns out that the error only occurs when not setting any `SplashFactory` of the `BootStrapper`. When adding a `SplashFactory` it works like charm.

**Comment by schuettecarsten** [comment]
We have the same problem here. When we are adding a SplashFactory, the app does not crash but locks on the splash screen on resume. So I do not think that the problem is related to SplashFactory.

We were able to fix this by changing our code that creates the Shell and the navigation service to this:

```
// Show the shell
var shell = Window.Current.Content as Shell;
if (shell == null)
{
    var nav = this.NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude);
    shell = new Shell(nav);
    Window.Current.Content = shell;
}
```

The problem is that when you use ExtistingContent.Include, Template10 tries to use the Shell itself as Frame content, which causes the argument exception. Unfortunately, Template10 does not know about the Shell, so you always need to create the shell yourself and then call `nav.RestoreSavedNavigation();` to restore the saved navigation state.

**Comment by JerryNixon** [comment]
I have added this syntax to the new Minimal template
