### ISSUE TITLE
Validation - DataContext not IModel

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#442]
Guess I am missing something with respect to this
      `<val:ControlWrapper x:Name="UserNameWrapper"  PropertyName="User"  
                                 RelativePanel.AlignHorizontalCenterWithPanel="True" RelativePanel.AlignVerticalCenterWithPanel="True">
                <TextBox PlaceholderText="User Name"  Width="200"
                     Text="{Binding Path=User.UserName, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
            </val:ControlWrapper>`
           `<val:ControlWrapper x:Name="PasswordWrapper" PropertyName="User" 
                                RelativePanel.AlignHorizontalCenterWithPanel="True" RelativePanel.Below="UserNameWrapper">
                <PasswordBox PlaceholderText="Password" Width="200"
                         Password="{Binding Path=User.Password, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                          Margin="0,5,0,0"/>
            </val:ControlWrapper>`

Based on your setup this should work but I guess I am missing how this should be setup since my ViewModel is based on ViewModelBase in the Template, User is UserInformation class object based on ModelBase in the Validation library. Every time I try to make this work it goes TU on the Property dependency DataContext not IModel, yet the UserInformation is indeed based on this, do I have to set a binding to Property with the converter that you posted ages ago?

**Comment by patcan80** [comment]
Try binding the wrapper to the an instance of User at the data context level. etc <val:ControlWrapper Datacontext="{Binding Users}">

**Comment by mvermef** [comment]
I have and that doesn't go very far either.  The example uses a service within the project to create the users, where as I am trying to validate the user(s) as they attempt to login.  I attempted using property converter from some older code based on Jerry's work in the past prior to the T10 release and it doesn't get far either.

**Comment by JerryNixon** [comment]
That property converter from the old code almost made it to the current sample, @mvermef . Thanks for the shout out to my past work. Meanwhile, let me explain that the page is bound to the view-model which is based on ViewModelBase from T10, that part is right. Then the ListView is bound to the Items property in the view-model that is an ObservableCollection<User>. Are we together so far? 

Finally, the form where the individual field is handled is bound to the individual user class. In the case of the sample, this is a User object implementing IModel. This works, too. So you should NOT be implementing IModel in your view-model with one exception: if you you are using the façade pattern to create an item view-model, which I do often myself, then you can implement IModel in that item view-model. You should note that item view-models don't need to inherit from ViewModelBase since they will never have INavigable methods called by the NavigationService. 

Does this make sense?

**Comment by mvermef** [comment]
So with the ControlWrapper,  I get the PropertyName, is this a deep property or can it be a property of a Class object (eg User.UserName)?  Property dependency property, does this need to know that its content is a Class object that is based on IModel?  User is my one of my models, is it expecting a ViewModel inheriting IModel? Doesn't ModelBase satisfy this requirement?  Would have answered earlier had to go fly.
    `<val:ControlWrapper x:Name="UserWrapper" PropertyName="UserName" Property={Binding User} />`
