### ISSUE TITLE
wrong heigth for HamburgerMenu when PageHeader is open

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#451]
I use Minimal template and i have this problem with little screen
thanks to all for your hard work!!

![drawing_162105 1](https://cloud.githubusercontent.com/assets/8555750/12137300/85188524-b44f-11e5-9a95-9f8e66a65855.jpg)

**Comment by chrisleyva** [comment]
This only happens when you tap on the "..." button in the CommandBar, correct?

**Comment by a-iafrate** [comment]
Yes, correct

**Comment by chrisleyva** [comment]
This happens in Microsoft's Photos app as well. This is not a bug. I agree that it looks ugly, but it's not a bug.

**Comment by JerryNixon** [comment]
Because the height of the page header buttons is the result of inheriting from CommandBar, what you are seeing is actually an overlay and not a change in the layout. In fact, it disappears with a light dismiss anywhere on the page. There would be no practical reason to resize the Hamburger in this case, but if you come up with a reason, let me know.
