### ISSUE TITLE
Application crash after suspend

### ISSUE THREAD

**Issue by Opiumtm** [Windows-XAML/Template10#459]
How to reproduce:
1) Start Windows 10 mobile emulator
2) Deploy application to emulator
3) Start debug session from Visual Studio
4) Emulate suspend+terminate lifecycle event from Visual Studio Debugger ("Lifecycle events" -> Suspend+Terminate)
5) Application suspended, terminated and remains in operation system applications list as expected
6) Hold "Back" button to switch tasks, select our application
7) Application does not reload/resume, it crashed instead

So, when operating system decides to unload suspended application from memory (which we emulate by sending "suspend+terminate" lifecycle event from VS debugger), there is no way to resume. It crashes instead and must be started from OS app list or live tile.

Application crashes only when it resumed by task switcher. When application in "suspend+terminate" state is started from OS application list or live tile it starts normal.

**Comment by ozzy1873** [comment]
This may be related to #457

**Comment by bc3tech** [comment]
I actually think it's an OS bug that the App remains in the task switcher after it's been **terminated**. I followed these steps and after 4 I turned on break on all exceptions & set VS to start debugging when app was launched then attached the debugger to the emulator. When I chose the app from the task switcher I observed the "crash" but the debugger didn't even initiate a wireup. So I don't think the app was really "launched".
Keep in mind, when you terminate an app on an actual device, it's the swipe down gesture (or X button) on the task switcher. Both of which remove it from that list. In this case we have the _debugger_ issue a terminate so the task switcher isn't involved in the action and (likely) doesn't get the message that the app went away in order to remove it from the list it shows the user.

It follows that you can't _resume_ a **terminated** app.

**Comment by Opiumtm** [comment]
Anyway, I observed in my another published app on an actual device that it can not resume some times. When I use task switcher it crashes. I think there is problem with Template 10.

**Comment by bc3tech** [comment]
Can you repro with one of the templates so we can troubleshoot?

**Comment by JerryNixon** [comment]
I believe this is related to using the Factory after a resume. Please change your SHell code to look like this:

```
public override async Task OnInitializeAsync(IActivatedEventArgs args)
{
    // content may already be shell when resuming
    var shell = Window.Current.Content as Views.Shell;
    if (shell == null)
    {
        // setup hamburger shell
        var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
        Window.Current.Content = new Views.Shell(nav);
        await Task.CompletedTask;
    }
}
```

And please try with the current code base, not 1.0.8

**Comment by bc3tech** [comment]
@JerryNixon I'm able to repro this w/ Minimal at `HEAD`. I don't think it's a Template10 thing.
