### ISSUE TITLE
Template10 1.0.9 on NuGet

### ISSUE THREAD

**Issue by marcominerva** [Windows-XAML/Template10#542]
When will Template10 1.0.9 will be published on NuGet?

**Comment by JustinXinLiu** [comment]
+1. I've been waiting for this too. :)

**Comment by AuroraDysis** [comment]
I've been waiting for two months....Behavior is not compatible with others in 1.0.8.

**Comment by JerryNixon** [comment]
Yeah, what's the plan for this?

**Comment by callummoffat** [comment]
How is Nuget 1.0.9 coming along? I've been using the Github sources since early January without issues, and there appear to be very few issues slated for the 1.0.9 milestone. My personal opinion is that 1.0.9 is as ready as it will ever be, and holding off any longer is counter-productive. There are thousands of fixes and new features in the latest code (post-1.0.8) that are well worth having, and I for one can't live without them.

**Comment by JerryNixon** [comment]
Yeah! 1.1.0 is on Nuget. Because it has breaking changes to the previous Templates, we had to skip 1.0.9 since all the current templates use 1.0.\* in their Project.JSON. If you want the new func, just upgrade to 1.1.0. Make sense?
