### ISSUE TITLE
Problem in PropertyStore when reading UseShellBackButton

### ISSUE THREAD

**Issue by GuillaumeGrillonLabelle** [Windows-XAML/Template10#57]
Hello, I have the following error when I start my project based on Minimal. The Minimal project works correctly, but not my project. I did an update today of the git repo and now the app does not start while last week it did. I've copy/pasted the whole Minimal folder on top of my project,  then fixed namespaces and other things.

Where is this "UseShellBackButton" setting is supposed to be save? In my other XAML apps (not windows store) it usually would be in app.config, but neither my app nor Minimal have one.

Object reference not set to an instance of an object.

Template10.Services.SettingsService.PropertyStore.Read<bool>(key = "UseShellBackButton", fallback = true) Line 45   C#
Template10.Services.SettingsService.SettingsHelper.Read<bool>(key = "UseShellBackButton", otherwise = true, strategy = Local) Line 38   C#
MyApp.Services.SettingsServices.SettingsService.UseShellBackButton.get() Line 29    C#
MyApp.App.App() Line 21 C#
MyApp.Program.Main.AnonymousMethod__0_0(p = {Windows.UI.Xaml.ApplicationInitializationCallbackParams}) Line 24  C#

Thank you for any help.

**Comment by kopfkraft** [comment]
Hi GuillaumeGrillonLabelle!

For all I know the settings stored within your apps folder(s) - c:/Users/..../AppData/.. . There are different types of persistent settings. while "local" means "only on the current computer" another possibility is "roaming" what means "sharing and syncing across different devices". 

https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.applicationdata.localsettings.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2

For a hint on where to find the actual files, you might debug the following property:

Windows.Storage.ApplicationData.Current.LocalFolder

Line 45 in property store is within a try {} catch-all block and would return the default value in case of 
an exception. So I am not yet sure how you could get an exception ... do you have further information about this (sample code, further Infos, what is 'null')?

**Comment by JerryNixon** [comment]
Now that I am re-reading your question, I wonder if you are asking where the initial value is before the user selects a custom value. In the case of the shell back button it is the default value set /Services/SettingsService/SettingsService.cs line 29. The default is true. 

So that this type of investigation is easier for you next time, I recommend placing your cursor on the UseShellBackButton reference in app.xaml.cs and using F12 to navigate to the definition. This will take you to the definition. If you want to put your default settings somewhere else, you might review this question: http://stackoverflow.com/questions/19994632/what-is-the-equivalent-of-an-app-config-in-a-winrt-app
