### ISSUE TITLE
Why isn't there a designer WYSIWYG for Hamburger menu items?

### ISSUE THREAD

**Issue by rickengle** [Windows-XAML/Template10#574]
Other than the image for the hamburger itself, there doesn't seem to be a designer view of Hamburger menu items and button icons.  I was hoping it would render similar to Windows Phone ApplicationBar which has a design-time view.
Is the only option at the moment to handcode XAML and view the results at runtime?

Thanks,
  Rick

**Comment by callummoffat** [comment]
There is a designer view (in Minimal template at least). Look in Shell.xaml. That's where the hamburger menu is coded, so the design-time view is in there. 

Unfortunately, due to the way T10 does things, I don't think there is a way to see the hamburger menu over any of your pages at design-time. @JerryNixon, am I correct on this point?

**Comment by JerryNixon** [comment]
Not sure what could be done different at this point.
