### ISSUE TITLE
HamburgerButtonInfo: ToolTipService.ToolTip not working[not visible]

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#580]
Currently it doesn't work to define ToolTip at HamburgerButtonInfo or content of it because the ToolTip isn't visible.

**Comment by JerryNixon** [comment]
Define the ToolTip on the content of the button, maybe?

**Comment by jp-weber** [comment]
I defined the ToolTip at Shell.xaml(Minimal sample)
`<Controls:HamburgerButtonInfo ClearHistory="True" PageType="views:MainPage" ToolTipService.ToolTip="Home">...
`

or

`<Controls:HamburgerButtonInfo ClearHistory="True" PageType="views:MainPage" >
<StackPanel Orientation="Horizontal" ToolTipService.ToolTip="Home">
<SymbolIcon Width="48" Height="48" Symbol="Home" />
                            <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Home" />
                        </StackPanel>
                    </Controls:HamburgerButtonInfo>`

But the ToolTip is not visible. Finally I edited the "NavButtonTemplate" at HamburgerButton.xaml. And it works if I define the ToolTip in the RadioButton(not in the "RadioButton.Template"). 

In that conlusion do we need a new parameter at HamburgerButtonInfo so that we can create easily the content with the ToolTip at Shell.xaml?

**Comment by JerryNixon** [comment]
Please add {ToolTipService.ToolTip} to the RadioButton in NavButtonTemplate and submit a Pull Request so I can merge it into the source. We'll shoot for 1.1.4. Good catch. You wont need a new property, you can use the default attached property.

**Comment by jp-weber** [comment]
Curiously my trying has failed to bind the attached property.It's almost like wouldn't pass the ToolTip to the NavButtonTemplate.

Can someone look into it?

**Comment by lombo75** [comment]
It can only be done in code, I did submit a pull request about a month ago, but it was ignored.

```
  void NavButton_Loaded(object sender, RoutedEventArgs e)
       {
        DebugWrite($"Info: {(sender as FrameworkElement).DataContext}");

        // add this radio to the list
        var r = sender as RadioButton;
        var i = r.DataContext as HamburgerButtonInfo;
        var sp = i.Content as StackPanel;

        // Get the text of the button
        var buttonText = string.Empty;
        foreach (var child in sp.Children)
        {
            if (child.GetType() == typeof(TextBlock))
            {
                buttonText = (child as TextBlock).Text;
            }
        }

        // Set the automation properties for each button
        AutomationProperties.SetAutomationId(r, buttonText + "Button");
        AutomationProperties.SetName(r, buttonText);
        AutomationProperties.SetHelpText(r, "Click to go to " + buttonText + " page");
        ToolTipService.SetToolTip(r, buttonText);

        //Debug.WriteLine("AutomationId : " + AutomationProperties.GetAutomationId(r));
        //Debug.WriteLine("Name : " + AutomationProperties.GetName(r));
        //Debug.WriteLine("HelpText : " + AutomationProperties.GetHelpText(r));

        _navButtons.Add(r, i);
        HighlightCorrectButton();
    }
```

**Comment by JerryNixon** [comment]
Not ignored. Perhaps misunderstood.

**Comment by lombo75** [comment]
So we are on the same page now?

this is not the solution but a workaround as the developer might not have a textblock in the menu, therefore making this code redundant.

As I stated before, I believe it is impossible to make the template accessible and for it to pass accessibility tests with the current structure of menu control. I have been trying to come up with a solution for two months

Narrator identifies the button as a radiobutton not a button if using this code to set automationproperties, also it doesn't identify the stackpanel as a list of items, therefore a blind person would not know they are in a list of menu items so I don't think a stackpanel is the right control to use. A listbox does express to the user that they are in a list of items

I hope I have made it clear that I believe the radiobutton design will not work and needs to be changed now instead of down the track where it will take more effort to fix. 

I would like to see a solution to this problem before using the template. I think this is a great project, hope somebody can work out this issue soon.

**Comment by jp-weber** [comment]
Thanks for the workaround, works pretty well. I agree to the not good access to the HamburgerButtonInfo and looking forward to a greater access.

**Comment by lombo75** [comment]
No worries, you might want to add
AutomationProperties.AccessibilityView="Raw" 

```
<ToggleButton AutomationProperties.AccessibilityView="Raw">

<ToggleButton>
```

in RadioButton.Template

**Comment by JerryNixon** [comment]
I would like to start a thread identifying accessibility issues in Template 10.
