### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException when passing parameter to Navigate

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#597]
I'm passing a List of Contacts to NavigationService.Navigate() and I'm getting an exception as shown below.
Notice that I never had this issue prior updating to 1.1.2

Exception thrown : 'Newtonsoft.Json.JsonSerializationException' inTemplate10Library.dll

Type specified in JSON 'System.__ComObject, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not compatible with 'System.Collections.Generic.IList`1[[Windows.ApplicationModel.Contacts.IContactField, Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path '$values[0].Fields.$type', line 1, position 116.

```
    public MainPageViewModel()
    {
        StartRouteCommand = new RelayCommand(async () =>
        {
            var contacts = await GetContacts();
            NavigationService.Navigate(typeof(Pages.ContactPicker), contacts);
        });
    }

    private async Task<List<Contact>> GetContacts()
    {
        var listResults = new List<Contact>();
        var store = await ContactManager.RequestStoreAsync(ContactStoreAccessType.AllContactsReadOnly);
        var list = await store.FindContactListsAsync();
        foreach (var reader in list.Select(contactList => contactList.GetContactReader()))
        {
            var batch = await reader.ReadBatchAsync();
            listResults.AddRange(batch.Contacts);
        }

        return listResults;
    }
```

**Comment by JerryNixon** [comment]
Allow me to offer you a simple solution. Instead of passing the records as a parameter to the page (which is really intended only for simple data like serializable structs) put it in the session state like this: `ViewModel.SessionState["ContactList"] = ContactList;` which you can write in the sending page and  fetch from in the receiving page. Why is it a bad idea to pass a big ole collection of things in param? Because it must be serialized in order to properly restore state when your resumes from suspension. Template 10 does this resuming for you, and enforces it by making sure your params can be serialized. This is 100% as designed. And, it's the reason we appended SessionState as a standard property to view-models.

**Comment by ghost** [comment]
Perfect workaround, thanks!

**Comment by darshanrampatel** [comment]
@JerryNixon, I'm unable to get this to work with SessionState; I get the following error when using your code:
`Cannot apply indexing with [] to an expression of type 'IStateItems'`

This works when I do SessionState.Add(...), but then I need to check for the key beforehand and it's getting messy.

I'm using 1.1.2.
