### ISSUE TITLE
Load Data in OnNavigatedToAsync stopped working / hangs

### ISSUE THREAD

**Issue by DominikErnst** [Windows-XAML/Template10#611]
This following line loads data from a local SQLite DB.
_Items = await _RadioStationTable.ToCollectionAsync();

But after the latest Update (1.1.2), it stopped working.

How to repair this? Is there a recommendation where an how to load data? 
BTW the ShowBusy never pops up.

public override Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
{
            state.Clear();
            ShowBusy();
            try
            {
                WindowWrapper.Current().Dispatcher.Dispatch(async () =>
                {
                    await _RadioStationService.RefreshRadioStationsAsync();
                    await _RadioStationService.RefreshFavoriteItemsAsync();
                });
            }
            catch ()
            {}
            FavoriteRadioStations = _RadioStationService.FavoriteItems;
            HideBusy();
            return Task.CompletedTask;
}

public async Task RefreshRadioStationsAsync()
{
            _Items = await _RadioStationTable.ToCollectionAsync();
}

**Comment by mvermef** [comment]
don't think you will need the WindowWrapper, you can simple add async to the overridden Nav method and call your Async methods that are required for your application.  Are ShowBusy() and HideBusy() in the same vein as SetBusy(bool isbusy, string busymessage = null) in the examples?  Secondly, why not see if the catch is actually catching something instead of dropping thru it, add an exception and see if it actually has some debug information to provide you... 

Because of the breaking changes in the latest release your code might need to evolve a bit.

**Comment by DominikErnst** [comment]
Hi mvermef,

Thanks. I will try your suggestions. The code is shortened, I have an error handling ☺. But I receive no exception 😩. The code hangs in the tocollection method.

Regards
Dominik

**Comment by mvermef** [comment]
Is that ToCollectionAsync() method something someone else wrote?  Sounds like its dead locked waiting for something to finish inside that Method not saying it isn't related to the changes but it could be something not exactly right in the Method its self.

**Comment by DominikErnst** [comment]
Thanks mvermef,

ok, after the Template 10 Update I had to remove the WindowsWrapper.and remove the "return Task.CompletedTask;".
BTW The ShowBusy() works!!! :-)
The ToCollectionAsync() is from "Microsoft.WindowsAzure.MobileServices".

THANK YOU VERY MUCH!!!

**Comment by mvermef** [comment]
no problem :)
