### ISSUE TITLE
Repository & Organization cleanup?

### ISSUE THREAD

**Issue by robertmuehsig** [Windows-XAML/Template10#616]
I discovered this project a couple of months ago and thought this was great and besides some issues, it's still great and a good starter kit.

But I think this repository could be cleaner. Currently I'm a uncertain what is part of the actual NuGet package and what not or how to work on the actual project template.

I will point out a few issues, or parts that I don't understand:
- Why is there a folder "Template10 (Services)" and a folder "Services" inside the "Template10 (Library)" or why is this not part of the actual library? At least services, without "external" dependencies could be part of the "core", or do I miss something?
- Is [this folder](https://github.com/Windows-XAML/Template10/tree/master/VisualStudio) even needed?
- Is [this](https://github.com/Windows-XAML/Template10/tree/master/ShareTarget) a sample? Could it be moved to samples?
- Are [validations](https://github.com/Windows-XAML/Template10/tree/master/Template10%20%28Validation%29) coming to the core library?

What is the idea behind the library and what should we call "samples". Currently there are some pieces of code that I must copy over, because it's not part of the NuGet package.
Someone could argue that the "core" nuget library should be small, which is totally fine, but then we could create a nuget package just for this use cases.

The last point is the super huge Windows-XAML organization that I'm (and I bet most of you) are part of. I honestly don't know why am I part of this organization. I just asked one question and was invited. I don't think this project will benefit from a +100 organization...
I think there should be a small core team and other can contribute via pull requests. 

What do you think?

**Comment by JerryNixon** [comment]
First of all, I am immeasurably grateful for this kind of feedback.
1. No, I deleted it.
2. Yes, I moved it.
3. Read below...

The remaining problem with validation is only in serialization. I have not circled back to validation to solve this problem, but I don't feel it is appropriate to include it until we solve this problem. Do you have a recommendation?

Samples is intended to demonstrate the use of the Library. In many cases, the implementation of things like Cortana, FileType, Share, etc. will require a technique that will NOT match the MSDN documentation on the subject. That's the intent of a sample.

I can only agree with the size of the library. I am not sure when the change will come, but it only makes sense that (at least) Controls be broken into separate NuGet packages. This will introduce some significant work and more than likely a breaking change for every single user of the library right now. It's just a matter of time.

The Library is the only project that comprises the Nuget package.

So, the Contributors team is special. It doesn't grant anyone permissions. They has the ability to interact with Issues, and submit Pull Requests like anyone else. That's all. The intent of the group is to establish a list of developers familiar with the library who can be called on simply adding @Windows-XAML/community to a post. It works brilliantly.

By the way, you are part o the Collaborators team because you accepted the invitation.

I forgot to respond to your question on services. Services is not tested and should be labeled as EXPERIMENTAL. They originated from my own library of services from Windows 8 development and are part of this so the code can be used, but I have not adequately tested it to be comfortable including it in the library at this time. I hope that makes sense.

**Comment by robertmuehsig** [comment]
Ok - got it. I think (after I restored a Windows version that is not breaking git) I will try to submit some PRs to getting this repo more clean. I didn't know the permissions from the Windows-Xaml group - so it makes sense.

**Comment by luiscantero** [comment]
Reg. the git issue that you mentioned, this fix apparently works:
-   Download portable 1.9.5 zip from https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20150319
-   Extract and add the new path to the PATH environment variable
-   (optional) If you are using a 3rd party client like Sourcetree, make sure it’s using system git instead of embedded.
