### ISSUE TITLE
Be able to set the hamburger button as always visible (mimic Groove app)

### ISSUE THREAD

**Issue by sebfrie** [Windows-XAML/Template10#689]
Being aware of #274 and #661, I still don't know how to enable an always (read: in all states) visible hamburger button.

I don't want to set `<HamburgerMenu.VisualStateWideMinWidth = -1 />` because I'd like to switch to the CompactInline DisplayMode in the wide state.

My final goal is being able to toggle between CompactOverlay and CompactInline modes in the wide state by clicking/tapping on the hamburger button. Please see the _Groove_ app as a reference.

**Comment by f4lke** [comment]
Same here. What i would love to see is the behaviour of the Groove or Photos app:
Narrow Mode: Not used.
Normal Mode: Hamburger visible and toggleable, CompactOverlay mode
Wide Mode: Hamburger visible and toggleable, CompactInline mode

**Comment by JerryNixon** [comment]
I like that look, too.

**Comment by DecaTec** [comment]
Today I started using Template10 mostly because the Hamburger control and ran into the same problems. 
Actually you can make the hamburger button to be always visible by "overriding" the visual states on the page using the Hamburger control. Let's say you start with the 'Hamburger (Template 10)' VS template, then you can add these things in the Shell.xaml. A little redundant, but it works.

But now I ran into the next problem: In the wide state, the user should be able to click on the hamburger button in order to 'pin' the full menu (DisplayMode=CompactInline) or to let it disappear (DisplayMode=CompactOverlay).
I think this behavior has to be implemented in the Hamburger control itself in the ExecuteHamburger command.

**Comment by JerryNixon** [comment]
Done

**Comment by sebfrie** [comment]
Nuget package 1.1.5 looks awesome! Why is there no commit info for the library under the code tab?

Edit: Tapping any button in the hamburger menu closes the pane (-> compact mode in the wide state). Is this by design? How can this be disabled?
