### ISSUE TITLE
HumburgerBackground overrides whole HamburgerMenu background

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#699]
After having v 1.1.5 the color of HamburgerBackground is also set to the whole content background (my pages now have the same color as hamburger button background). Is it expected behavior or a bug?

**Comment by JerryNixon** [comment]
Show me a screenshot.

**Comment by angusbreno** [comment]
@JerryNixon 
This is what happens 
![happens](https://cloud.githubusercontent.com/assets/5822893/13498784/210705c0-e13a-11e5-893d-8a8a189f307d.png)

There is no background for content... When u use a page with background the color it's ok but in the navigation second glitches the hamburguer background because of transition animation... 

My temporary workarround for this was: 

HamburgerMenu.NavigationService.FrameFacade.Frame.Background = ...

**Comment by angusbreno** [comment]
https://github.com/Windows-XAML/Template10/blob/db7f761a930a4f404b38d92bccd9a8996712cdff/Template10%20(Library)/Controls/HamburgerMenu.xaml#L185

**Comment by angusbreno** [comment]
@JerryNixon I think there is a general misunderstood about HamburgerMenuBackground and the probably wanted "HamburgerMenuButtonBackground" :smile: 

Makes sense?

**Comment by angusbreno** [comment]
I think this is solved with the latest commits. Setting just control background fixes, right?
@JerryNixon 
@Viachaslau-Zinkevich
