### ISSUE TITLE
Fix a template icon

### ISSUE THREAD

**Issue by mklemarczyk** [Windows-XAML/Template10#712]
Please fix the template icon with something more professional.
Current icon looks like a student project not something that companies want to use.

**Comment by jhalbrecht** [comment]
I find it amazing that folks can make such requests and statements. Template 10 is all volunteer. Rather than complain about this excellent free resource why not fork and create an icon that you feel would be more appealing to the group. Then the group will have an opportunity to input their support or lack thereof.

**Comment by mvermef** [comment]
would have to have to agree with Jeff...

**Comment by JerryNixon** [comment]
Plus, I like the icon.

**Comment by mklemarczyk** [comment]
I used a few times this template.
It just introduce noise and chaos to the project, I switch to blank template.

There are too many bugs here.

**Comment by qmatteoq** [comment]
Then don't use it if it doesn't fit your needs :-) If you have issues or constructive feedback feel free to share it, there's always room for improvements. Otherwise, statements like your are just made to trigger flames and useless discussions.
