### ISSUE TITLE
SecondaryCommands ellipses showing up when no secondarycommands are present 

### ISSUE THREAD

**Issue by Vidyogamasta** [Windows-XAML/Template10#716]
Re-making this case with a few extra details to clarify the problem. 

There are two types of controls on the command bar: PrimaryCommands and SecondaryCommands. Unless I am misunderstanding something, PrimaryCommands are standalone buttons (similar to save/print icons), whereas SecondaryCommands are all kept within a flyout menu that opens when an ellipse icon is pressed. 

The problem is that in my page header I want a primary button, but I DO NOT want the ellipse icon to show up. The PageHeader class specifies the behavior as EllipseBehaviors.Auto, and EllipseBehaviors.Auto checks to see if primary OR secondary commands are present. This means if I add only a primary command I also get an ellipse with an empty flyout menu. Again, unless I'm misunderstanding how this works, this ellipse should only be present if there are SecondaryCommands and should not be checking for PrimaryCommands at all. 

EDIT: I had sample xaml but I have no idea how to format it, I'll take out that eyesore since the above text should be enough to replicate the issue.

**Comment by Vidyogamasta** [comment]
I do see now that interaction behaviors present in the Minimal template so I can override this behavior to be collapsed if I want. I'm still not sure if this is the expected default behavior of "auto" though.

**Comment by JerryNixon** [comment]
Okay, I understand. Tell me this. How will your users see the labels on your primary commands if you remove the ellipsis from the command bar?

**Comment by Vidyogamasta** [comment]
Ahhh, I see it now. So I was misunderstanding it =) I just wasn't putting a label on my primary command so it wasn't clear what was happening there in my example. I'll go ahead and close this, thanks for pointing that out.

**Comment by artemious7** [comment]
Perhaps, it may be a good idea to let the user know somehow if there are secondary command under the ellipsis or not. Right now the user has to tap on the ellipsis just to find out that there are no additional buttons there. 
I agree that the ellipsis is useful even if there are no more buttons, because tapping it expands the labels of primary commands. However, if there were some way to distinguish between the two situations, it would eliminate the need to do extra actions (expanding the CommandBar and then closing it).
I would make the ellipsis bold if there are more buttons, and leave it as is otherwise. Or something like that.
