### ISSUE TITLE
NavButtonBehavior.cs deadlock in 1.1.7

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#725]
Latest changes to NavButtonBehavior.cs cause deadlock. I am not sure about the root cause, but application locks up in "NavButtonBehavior.LayoutUpdated", Line 61, while several other threads stopping in CalculateBackVisibility/CalculateForwardVisibility.

Commenting out everything from "NavButtonBehavior.FrameChanged" method fixes this issue, but breaks NavButton, of course.

**Comment by JerryNixon** [comment]
How do you cause the deadlock?

**Comment by arpadbarta** [comment]
It might be related to this issue so I don't open another one, with version 1.1.7 and 1.1.8 application locks up at seemingly random places, although VS (update 1) sais it is running... Reverting to 1.1.5 everything works just fine.

**Comment by darshanrampatel** [comment]
@barptad, yep, I'm seeing similar behaviour - though, like you said, it's seemingly random...

**Comment by toituu** [comment]
Same experience here

**Comment by Opiumtm** [comment]
Maybe using of Rx for event throttling was not wise?
Now I carefully profile my application (to optimize it before release) and I found that Reactive Extensions spawn a separate thread and use somewhat sophisticated scheme to dispatch events to observers. Such a complex pattern of event processing can cause a deadlock - it needed to be carefully debugged to find a root cause of deadlocks.

Also, I found in my code a weird situation of deadlock and later read on stack overflow web site that **`await` keyword should never be used with `Task.Wait()` on same execution path** because this combination certainly can lead to weird and random deadlocks because task parallel framework is not suited for use  `await` and `Task.Wait()` on same execuction path, these methods of task interaction are mutually exclusive. You can use only one - `await` or `Task.Wait()` on execution path but not both. When I removed single `Task.Wait()` from my code and moved entirely to `await` pattern, deadlocks in my code gone away. Maybe this experience in task parallelism can help. At least I already got similar problems and fixed it by using only one method of task interaction, because you should never use both on same execution path or you get deadlocks.

**Comment by Opiumtm** [comment]
I found explanation why `Task.Wait()` and `await` should never be used together.
It is simple. It's because `async` methods with `await` code always try to reuse same thread context. It is form of cooperative parallel work, it is very similar to classic Win32 applications message processing loop. When one part of code `await` on external resource (http request or file I/O operation for example), other work is scheduled on same thread (most often UI thread, but thread context may be different if `async` method is called on different thread context in first place). But when you use `Task.Wait()` instead of `await`, thread will explicitly wait for task execution instead of scheduling other work on same thread. So, it will break scheduling logic and deadlock may occur. `Task.Wait()` should never be used as a gateway between `async` world and sycnhronous logic. It can only be used if waiting for an **atomic** external aync work such as file I/O or http requests _on dedicated thread_. **Tasks created by `async` method pattern should never be waited using `Task.Wait()` from same thread context and should never call `Task.Wait()`**. It is somewhat vague and it's very simple to misuse because there is no explicit warning on MSDN. To know this you must read more on task async architecture to understand how it works.

Also, using `TaskCompletionSource` as a method to coordinate work is safe. You can safely use `TaskCompletionSource` in `async/await` code without any deadlocks.

**Comment by Opiumtm** [comment]
@JerryNixon and for this situation I can _assume_ (it need to be investigated to be sure) that Reactive Extensions Framework event dispatching is incompatible with C# generated async tasks code. When RX was first used to throttle events, deadlocks start to occur. If RX use explicit task wait in its code it make RX code incompatible with cooperative async/await methods called from UI thread and weird and hard to debug deadlocks may occur in any arbitrary place of code. If it is a case, it just completely ruin all UI cooperative scheduling logic and deadlock may occur anywhere on cooperative scheduling.

**Comment by Opiumtm** [comment]
@JerryNixon in my text changed event throttling behavior pull request (#665) I argued that RX should not be used to throttle UI events, it may be a misuse. And this issue revealed that I was right. We have no exact knowledge on how RX handle event dispatching (profiler show that it spawn a separate thread for event throttling) and so we have a vague threading deadlock bug because of RX misuse.

**Comment by Opiumtm** [comment]
@JerryNixon As RX spawn separate thread this fact alone is a warning. `async/await` C# pattern is built on _cooperative_ multitasking paradigm and it should be mixed with .NET traditional multithreading approach with care. Any explicit task/event wait (widely used in multithreading paradigm) is disastrous to cooperative multitasking environment. To counter this risk `TaskCompletionSource` should be used as a gateway between cooperative and multithreading worlds. Cooperative multitasked code should never use multithreading primitives such as mutexes, automatic and manual events, semaphores and so on to coordinate work (or must use similar primitives specifically built on top of cooperative multitasking using a `TaskCompletionSource`). RX seems (and likely is) to be built as multithreaded framework (at least it spawn new threads as profiler show) and is not directly compatible with cooperative multitasking because of this. RX should not be used to throttle async UI events or its use must be wrapped in `TaskCompletionSource` to make it compatible.

**Comment by schuettecarsten** [comment]
I can confirm that the way how event throttling is implemented causes our deadlocks. I've removed it - and the locks are gone.

**Comment by arpadbarta** [comment]
I don't want to sound disrespectful, in fact I'm grateful for all of the hard work which is being done for us. It is a wonderful library for getting up and running without too much boilerplate. However, please try to be a bit more careful with such changes. I recon that most of us don't expect "wow" built in features, however stability is a primary concern.

**Comment by schuettecarsten** [comment]
The issue was reproduceable on VS2015, VS2015 with Update 1 and with Update 2 CTP and RC. It does not have anything to do with the VS2015 version, so I removed this from the title.

**Comment by Opiumtm** [comment]
@carstenschuette There is no need to remove event throttling. It's just RX dependency must be removed and more `async/await` friendly class to be used instead of RX.

https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/EventThrottleHelper.cs

**Comment by Opiumtm** [comment]
Noticed weird behavior on .NET Native ARM. When my code use pattern like this

```
    lock (SomeDictionary)
    {
         SomeDictionary[key] = value;
    }
```

inside `async/await` method running on UI thread **and code inside lock section is not async, it's just an atomic update to dictionary and not more**, I start to observe regular deadlocks with fatal UI freezes here. It can not be, because code inside `lock` section is synchronous! There should be no arbitrary yields of cooperative execution. But it is And most weird, deadlocks are random and occured most when you press "back" hardware button to go back on navigation stack.

I think there is some not known internal platform dependent implementation details in `async/await` and threading synchronization. I just written "thread safe in general" code which can be called from any thread. And it deadlocks because of otherwise atomic `lock` when run on UI thread in async context. Weird. It should be noted.

Need to admit and get a firm point. `async/await` code is not intended to be mixed with multithreading primitives, it's just not work, not supported and can cause crazy looking platform dependent bugs.

**Comment by lyling** [comment]
I meet the same issue.
@Opiumtm the Task.Wait()  codes all you removed are in Template10 projects totally?

**Comment by Opiumtm** [comment]
@lyling problem is, Reactive Extensions Framework is used to throttle events. RX is not `async/await` aware framework (as far as I know), it is built as a classic multithreaded framework. Profiler show that throttling code at RX spawn new threads, etc. It certainly can cause deadlocks and is incompatible with cooperative multitasking of `async/await` on UI thread. It's just created for another purposes and misused here at T10. There are two opitions - stop using RX as event throttling can be solved without heavy external frameworks (this task is not a rocket science), or RX calls needs to be wrapped using `TaskCompletionSource` which is supposed to be safe gateway between `async` cooperative world and any other asynchronous and parallel sources or move such calls to other threads (not UI thread!) in a classic multithreading manner. In T10 when event from Windows Runtime arrive, RX throttler is triggered. But, you can not say that RX code do not block in the deep when you trigger event. Single `lock` to synchronize access can cause a deadlock on UI because if throttled event receiver on UI thread yield execution inside some lock (you can not say that throttled event callback is not executed from inside some lock at RX), triggering a new throttled event from UI thread from other scheduled part of code can cause deadlock if RX trigger code again aquire some lock. You just have no guarantees here, RX is an external _multithreaded_ code, RX can lock and spawn threads on its own and you have no control on it. In classic COM calls between multithreaded and single threaded apartments are marshalled for a good reason. You can see `async/await` and multithreaded code as an exact model of that classic COM threading apartments. `async/await` on UI thread is a single threading apartment, RX is a multithreading apartment and calls between not compatible apartments should be marshalled.

**Comment by disklosr** [comment]
Why not have a simple event aggregator class that is async/await friendly? Do you really have to use Rx library for this? (My understanding is that Rx is only used for Messenger)

**Comment by Opiumtm** [comment]
@disklosr this simple `async/await` friendly event aggregator class already here
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/EventThrottleHelper.cs
Just need to use it.

**Comment by lyling** [comment]
I have never use Rx in my project. when my app hang on, I check it the thread is stay on navbavior's layout updated method for hamburger menu.

**Comment by disklosr** [comment]
@Opiumtm I'm pretty sure that's not an event aggregator class. But nevermind, I thought that problem you were discussing here was because of using rx to implement an event aggregator helper but now that I checked the code I couldn't find an implementation for it. But where's rx used then?

**Comment by Opiumtm** [comment]
@disklosr I'm pretty sure it's an `async/await` friendly event throttle class because I wrote it myself. It's used in a throttled event behavior
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Behaviors/ThrottledEventTriggerBehavior.cs

It does not "aggregate" events in a full sense (it does not save all event data), it just throttle events and fire throttled event when time pass with a possibility to auto reset throttle timer if needed. But event data here is not needed. Just a fact of layout change event matter.

**Comment by Opiumtm** [comment]
@disklosr In T10 library RX is **only** used in NavButtonBehavior class as far as I know. @JerryNixon just love RX and arbitrarily (mis)used it here.

**Comment by schuettecarsten** [comment]
#740 updated. Please review.

**Comment by toituu** [comment]
@carstenschuette worked for me at least. No deadlocks seen versus seeing them far too easily before.
