### ISSUE TITLE
Clicking the hamburger button don't work.

### ISSUE THREAD

**Issue by disklosr** [Windows-XAML/Template10#751]
When I click the hamburger button, nothing happens. I expect it to expand the view of its items.

**Comment by kdowswell** [comment]
This works fine for me. Can you give some more information?

What device type, window size, etc..

Are you using the latest code from GitHub? Or are you referencing via Nuget?

**Comment by raifordb** [comment]
Make sure you are using Template 10 Version 1.1.8. You will see this issue if you are using version 1.1.6.

Open Nuget manager and check your installed version. If it is 1.1.6 update it to the latest and it should work.

**Comment by dg2k** [comment]
The NuGet Version 1.1.8 is fine although I have a minor issue with it as described in #754.

The Visual Studio Extension Version 1.15, on the other hand,  behaves as @disklosr described.

**Comment by disklosr** [comment]
@dg2k you're correct. I installed the extension which automatically adds version 1.1.6 which has this bug. I changed the version to 1.1.8 and the problem disappeared. You should probably update the VS extension.

Thanks.

**Comment by jakobpn** [comment]
@dg2k, are the steps to update the VS extension described somewhere?

**Comment by dg2k** [comment]
@jakobpn - You can check for updates in Visual Studio via: **Tools > Extensions and Updates** and by selecting **Template 10 Template Pack** in the Installed list (of course, assuming that this is installed with Extensions and Updates manager, or with NuGet package manager console, or manually downloaded [from here](https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5) and installed).

Also VS extension updates are pushed with VS update notification. Since I see no notification for **Template 10 Template Pack** (I can see one for Application Insights - just to confirm my system works as it should) it means as yet no update beyond V1.15.

**Comment by JerryNixon** [comment]
I will release a template update with 1.1.*
