### ISSUE TITLE
Static fields initialization for page not even loaded

### ISSUE THREAD

**Issue by pellea** [Windows-XAML/Template10#775]
Hello,

I noticed that each static fields of my views are instantiated even if the page is not displayed because of the `<controls:HamburgerButtonInfo PageType="views:MapPage">`.

Is this behavior normal ?

Regards,
Adrien.

**Comment by rcbevans** [comment]
I have taken a look into this and it appears to be XAML related.

To test, I took the Hamburger project template and added a simple static field to the `SettingsPage` which I could break on.

I then ran the app as-is and saw, as you have reported, that the static field is initialized not when the page is first created, but when the app is initializing.

In the call stack you can see the call is coming from some external code, but the next caller in the stack is the call to `InitializeComponent` in the constructor of the `Shell` view.  The `InitializeComponent` method does a number of things, but mainly it invokes the system static `LoadComponent` method which loads and parses the XAML portion of the view class, among other things (see http://stackoverflow.com/questions/245825/what-does-initializecomponent-do-and-how-does-it-work-in-wpf).

I then tweaked the `Shell` class, so that the `PageType` property of the `SettingsPage` is set in the codebehind, after the `InitializeComponent` call is made using `typeof(SettingsPage)`.

This time, the static field of the `SettingsPage` class WASN'T initialized until the page was navigated to the first time.

My hypothesis is, that something in the way the page XAML is parsed forces any referenced types to be eagerly initialized.  By putting a breakpoint in the `SettingsPage` constructor, you can see that no instances of the class are actually constructed until the page is navigated to, suggesting that the XAML compiler for some reason forces initialization of the type when referenced.

In WPF I believe that you could use the `x:Type` markup extension in situations such as this, but it isn't supported in UWP.

I'm not sure exactly what's going on, would be interesting to find out.  Hopefully your static fields in your views aren't too heavyweight to initialize, but as a workaround you could name the `HamburgerButtonInfo` you want to set the `PageType` of, and just set it in the code behind as a workaround for the time being.

Hope this is helpful

**Comment by pellea** [comment]
The `PageType` could be a `string` like in PRISM (or an URI to be precise).

**Comment by rcbevans** [comment]
With a string the user would  have to manually write out the fully qualified name of the type they want, and would you not you'd lose the benefits of intellisense to help you complete the property value?

I don't disagree that the statics initializing isn't ideal, but for most users I wouldn't imagine it's a huge problem.

**Comment by JerryNixon** [comment]
To be clear, your XAML is the second half of the Page partial class. Any reference to any C# class with a static field forces instantiation. The best test would be to create a static constructor in your class and watch as it occurs. If you don't want this to be called, you need to delay the invocation of the class.
