### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by toituu** [Windows-XAML/Template10#777]
While profiling our Template10 base app, we noticed that the app performance seems to drop over time. Sure enough, memory profiler indicates that the app memory consumption seems to increase all the time just by switching between views.

Now, just for reference, we run an app based on the Template10 Hamburger template without any changes through the memory profiler, and the memory consumption appears to increase all the time just by switching between home and detail pages. The consumption does not increase in alarming rate, but it does seem to constantly grow...

While it does not explain the issues within our own app, it seemed to be worth raising as something within the Template10 internals seem to be leaking...

**Comment by dubstylee** [comment]
I suspect that this may be related to an issue with the 1.0.3 Behaviors package. There is an issue with navigation that I think may be part of the problem. I don't know the exact details of the issue, but in my case, the back stack increases in size every time I navigate to a new page, even if I go back to the main page first... That issue was resolved in Behaviors 1.1.0, but Template 10 doesn't play nice with the new package yet.

It might be worth trying the new Behaviors package and see if the leak still exists anyway.

**Comment by JerryNixon** [comment]
There are a lot of questions I have to ask. Are you testing a simple template? If not, what s the NavigationCacheMode you are using? Are your view-models singletons? Are you caching data in services? Are you using SessionState? What is the way you are releasing objects to GC? Finally, and most importantly, can you repeat your results using just the simple templates?

**Comment by toituu** [comment]
I just created blank application from Template10 Hamburger template. No changes at all. In Release build, just by clicking back and forth between the home button in menu and submit button to navigate to details page, slowly but surely the memory usage just increased.

![untitled](https://cloud.githubusercontent.com/assets/6338637/14003581/64c718b8-f15c-11e5-9509-f0772c6fe27a.png)

**Comment by JerryNixon** [comment]
I agree, there's some hook holding it in memory. I am open to suggestions. It might be a bit before I can dig deep in this. But, without question, we will resolve this.

**Comment by schuettecarsten** [comment]
This happens only in Release build?

**Comment by toituu** [comment]
Well, I didn't test this with Debug build as much as I just wanted to verify that there is a leak wit blank app with Release build. It's quick to test though.

**Comment by rcbevans** [comment]
I just ran a profiling session against the Hamburger sample app switching between home and settings pane, using Behaviors 1.1.0 and over a period of 2 minutes clicking back and forth I observed a growth in the managed heap of 616KB but a growth in the unmanaged heap by 5.17 MB.

In the managed heap, it appears the main leaked objects are

| Object Type | Count | Count Diff. | Size (Bytes) | Total Size Diff. (Bytes) | Inclusive Size (Bytes) | Inclusive Size Diff. (Bytes) | Module  |
| mscorlib!??_7RoutedEventHandler | 152 | +126 | 32,408 | +30,992 | 51,336 | +20,352 | Sample.dll |
| mscorlib!??_7DependencyPropertyChangedCallback | 74 | +74 | 3,552 | +3,552 | 126,560 | +126,560 | Sample.dll |
| mscorlib!??_7AppBarButton | 35 | +35 | 38,360 | +38,360 | 60,200 | +60,200 | Sample.dll |
| mscorlib!??_7BehaviorCollection | 39 | +34 | 58,800 | +41,496 | 91,432 | +65,368 | Sample.dll |
| mscorlib!??_7?$VectorChangedEventHandler$1 | 48 | +34 | 3,576 | -2,104 | 41,792 | +9,656 | Sample.dll |
| mscorlib!??_7NavButtonBehavior | 32 | +32 | 37,792 | +37,792 | 126,152 | +126,152 | Sample.dll |

In the unmanaged, a majority of the leak is coming from:

| Identifier | Count | Size (Bytes) | Count Diff. | Size Diff (Bytes) | Module |
| McgInterop.ComCallHelpers.ComCall__HRESULT | 35,134 | 3,613,743 | +15,283 | +1,646,976 | Sample.dll |

though I have no idea what exactly that is.

I'm having a tough time identifying anything meaningful in the unmanaged heap traces to suggest an issue.

**Comment by Opiumtm** [comment]
It's not "potential", it's surely is.
I also experience huge performance degradation on old timed Lumia 920 test device and I can not say it's not because of my code. But too many evidence points to Template 10. Just another case. I do not point finger without proper evidence, I have no such carefully measured evidence. I just want to say my application experience huge performance degradation with time. Many people on forums also complain.

**Comment by Opiumtm** [comment]
@o0rebelious0o I'm not sure than Template 10 is exactly responsible for this memory leaks. I have done some deep investigation with memory profiler and was very confused because it's very hard to understand results without exact knowledge of how UWP internals work. Too many questions and too few answers. I already writed complains to .NET Core and .NET Native teams. System behavior is very strange. First, most "leaked" objects are no more than wrappers and interop glue to native COM/WinRT objects. .NET Native team answered in very vague form. They say that current version of .NET Core and .NET Native  .NET/WinRT interop code is not optimal and allocate too many intermediate objects and they promise to make it much better in future releases. After careful investigation with memory profiler (and these measures are consistent with reports and complains on Stack Overflow forum) I found that most of retained in memory intermediate objects are marked as "weak handles" by profiler (I use JetBrains profiler) and these "weak handles" are responsible for retaining bigger objects (like pages, view models and so on) in memory. These "weak handles" typically become collected by garbage collector, but on its own weird schedule. Manual invoke of `GC.Collect()` with any flags and options does not collect these "weak handles" at all. These "weak handles" are immune to .NET garbage collector and are eventually collected on conditions that are unknown to me and to everyone else except UWP team. So, if you use at least one compiled `{x:Bind ...}` binding in your code, generated compiled code-behind binding classes are retained by native COM events and in turn these compiled binding classes retain View Models and Page objects because compiled bindings do not use `WeakReference` to host Page, they reference it directly. If you do not use compiled `{x:Bind ...}` bindings and use old classic runtime `Binding` instead, there are no weird "weak handles" that retain entire object tree and collected eventually on schedule absolutely independent from standard .NET garbage collector. What is most weird, unlike classical memory leaks, these "semi-leaks" caused by compiled bindings are collected eventually on a completely unknown conditions. Retained "weak handles" may be dropped almost immediately or they may be dropped after a 10-20 navigations to other pages. They may be dropped all at once, or just oldest ones. I have not found any rational pattern in these "weak handles" garbage collection. They just live on their own. Maybe their removal from memory is dependent on native heap size? Or maybe they are collected on independent system-wide timer? Or maybe .NET Core garbage collector treat these "weak handles" so weird. No one knows. 

If you read description of "weak handle" retained object in JetBrains documentation, "weak handle" is a handle to native COM/WinRT object that can be collected by garbage collector unlike "reference-counted handle" that can not be collected by garbage collector and must be disposed manually. Memory profiler documentation say that these "weak handles" can be collected and they are really eventually collected as observed with profiler. But unlike .NET objects these "weak" native handles are immune even to a manual full `GC.Collect()` and collected on unknown conditions and these "weak handles" are collected signinficantly less frequent. When .NET objects are collected regularly, weak handles are collected eventually at best. To make things worse these eventually collected "weak handles" can retain entire big dependent .NET object tree in memory because as you know, event handlers include reference to an object and .NET event handlers most often cause memory leaks. So, when these "weak handles" (often `RoutedEventHandler` mentioned in your listing) retained in memory, immune to .regular NET Garbage Collector and disposed eventually at best, they indirectly retain all the burden of fat and heavy.NET objects tree. This situation looks like a memory leak and can severely degrade application performance after app run some time.

To make it short, investigation with profiler does not answer all questions. It looks more like a platform issue, but I wasn't investigated it in clean environment, without T10. To say it is a platform issue we need a clean project without T10 to reproduce these memory issues in most minimal environment possible. If it is not reproduced without T10, then T10 is responsible for these "semi-memory-leaks". If it is reproduced without T10, then it is a platform issue and we should complain to Universal Platform team about very poor quality of .NET/WinRT interop.

**Comment by Opiumtm** [comment]
So, to summarize said before. This summary may not be exhausive, but it have some points.
1. Any use of `{x:Bind ...}` compiled binding cause "semi-memory-leak" with eventually less frequent collected "weak" native object handles. There are many complains about `{x:Bind ...}` weird memory behavior and investigation with JetBrains memory profiler proven these complains are true. 
2. Standard T10 page templates do use `{x:Bind ...}` compiled bindings
3. Use of `{x:Bind ...}` compiled bindings **is recommended** by Microsoft and compiled bindings are significantly faster than classic runtime `Binding`. When I for experiment replaced every `{x:Bind ..}` with `{Binding}`, performance of dynamic UI updates was reduced dramatically and become visibly asynchronous (if you bind to `Height`, `Width`, `Visibility` or other UI properties, it become very visible and cause visible UI convulsions, compiled bindings do not cause these UI convulsions). But use of `{x:Bind ...}` cause "semi-memory-leaks" that cause much often garbage collections and severe performance degradation with time because garbage collector check too many objects and run too often and GC as you know freeze any running threads and so it freeze entire application. It is not so critical on x86 desktop machines. but on resource constrained ARM devices it becomes a disaster.
4. This situation have no good outcome. It's a stalemate. If you use runtime `{Binding}` it severely degrade performance immediately because compiled bindings are much faster. If you use compiled `{x:Bind ...}` it severely degrade performance with time and make things very unstable and dependent on unknown "weak handle" collecting conditions which is not so frequent, inconsistent with .NET garbage collector and just looks horrible when you observe it with memory profiler.

You can use some tricks to minimize damage. For example you can hande `OnUnloading` events and manually set ViewModel and other .NET tree references on page object to `null`. But it is certainly is not a good practice and these tricks should be used only in desperate situation (like a situtation we have). In current state of things we have very inconsistent automatic memory management model (because of .NET and native COM/WinRT objects mix within an universal windows application) and these tricks are here because automaitc memory management in UWP apps is broken and we need to use old but not so good manual memory management in some parts. It's a shame.

**Comment by Opiumtm** [comment]
And some personal opition on situation. After these investigations I have a thoughts about **why exactly** Microsoft decided to not distribute Windows 10 Mobile on many less powerful devices. Universal Windows Model is clearly designed for x86 desktops and perform well on x86. But on less powerful ARM devices UWP app model performance is terribly untolerable. Such a vile concotion of .NET and native COM perform visibly unstable and poor on resource constrained devices. Entirely managed Silverlight apps on these devices performs much more stable and fast. More computational CPU power and more memory make things looks much better. Older ARM devices just can not lift burden of unoptimized mixed .NET/COM universal model. To be honest, Windows Phone 8.1 WinRT apps also performed badly but it wasn't a big problem because developers preferred old good Silverlight app model on Windows Phone 8.1 devices. WinRT 8.1 apps was very rare and for good reason. But with Windows 10 Mobile this mixed .NET/COM model is a recommended approach and silverlight apps have become obsolete. So, you surely can throw your older Lumia and HTC devices into a trash can. They are not supported, they rely on obsolete app model and they have no power to run new unoptimized universal app platform. Ironically, Windows Phone/Mobile platform now looks much like Android. It is now require modern CPU and plenty of memory, older devices are not supported and universal platform itself is much less stable. So we have another resource hungry Android instead of promised "optimized" and not resource hungry Windows Phone platform. Universality demands its terrible price. We all known it before but was too fearful to speak it openly.

**Comment by Opiumtm** [comment]
@JerryNixon as for my investigation, T10 is not responsible with 80% probability. T10 is only "responsible" for use `{x:Bind ...}` compiled bindings, but `{x:Bind ...}` is a Microsoft recommended approach. My current conclusion after a quite deep investigation - it is a **critical platform issue**. No "memory leaks" if you use runtime `Binding` instead of compiled `{x:Bind ...}` bindings. And there are no memory leaks in a full sense. I call this leaks "semi-leaks" because retained objects are **freed eventually on an unknown conditions** independent from .NET garbage collector logic. And this weird behavior is most probably because of managed and native objects mix in any C# UWP application.
Any UI objects (pages, controls) are in fact native COM Windows Runtime objects, this is true for any system classes which are referenced from native COM libraries with _.winmd_ metadata. So, any C# UWP application is not entirely managed, it heavily depend on native COM. And because of this fact automatic memory management is weird and too many objects retained by so called "native weak handles" which collected on its own schedule independent from managed garbage collector.

**Comment by JerryNixon** [comment]
Thanks, @Opiumtm, I'll chase this more. Would like @toituu conclusion, too.

**Comment by Opiumtm** [comment]
@JerryNixon main issue is with a `{x:Bind ...}` compiled bindings.
I performed some tests about it. On stack overflow there are some posts about `{x:Bind ...}` memory issues. I have tested it myself and can say it clear - yes, these reports about `{x:Bind ...}` are true.

**Comment by Opiumtm** [comment]
@JerryNixon just for reference

http://stackoverflow.com/questions/32581432/uwp-compiled-binding-xbind-produces-memory-leaks

https://social.msdn.microsoft.com/Forums/vstudio/en-US/c2bde144-47ae-4eb9-817f-1f434caa05f5/uwpcxaml-compiled-binding-xbind-cause-memory-leaks?forum=wpdevelop

**Comment by Opiumtm** [comment]
@JerryNixon well, and no fix for this critical issue in a Visual Studio 2015 update 2...

**Comment by schuettecarsten** [comment]
@Opiumtm: I doubt that this is a Visual Studio 2015 issue which will be fixed in an Update, it sounds like a major issue in the UWP runtime.

**Comment by Opiumtm** [comment]
@carstenschuette runtime `{Binding}` do not cause memory issues. Maybe some fixes in compiled bindings generated code-behind can make things better. Do not reference host page derectly but reference it via weak link for example? There is some weird situation. "Weak handles" (associated with host page object and routed event handlers) and compiled code-behind `{x:Bind ...}` generated classes retains each other. It seems like it will be collected on regular .NET schedule (or maybe weak handles will be not visible to memory profiler if they do not reference .NET classes?) if they do not reference each other. Anyway it all stuck at Visual Studio 2015 code behind compiled code. I think, so called "weak handles" are collected on their own schedule and become invisible to .NET memory profiler if they do not reference any .NET objects and not referenced by .NET objects. When memory profiler find .NET object it looks what referenced by it and by what it referenced and there are "weak handles" which have direct references with .NET objects.

Maybe generated by Visual Studio 2015 binding code can put some effort. It can at least listen to `Unloaded` event and clean up things. It attaches on `Loaded` event to assign data changing event listeners and set initial values, why it can not clean up things after itself? If there is native COM interop which can cause memory issues why Visual Studio 2015 generated code can not clean up things on page unloading? It surely can. 

As for now `{x:Bind ...}` generated code **does not** clean up things. It does not remove event handlers, does not set internal references to null. It rely on garbage collector to clean it up automatically, but garbage collector works bad on a .NET/Native interop boundary. If automatic garbage collection works bad, you always can clean up things manually (which sadly too often required if you do interop with native code). After all, when page unload it fire `Unloaded` event and it's a best place to clean up all event handlers and retained references to COM objects.

So, this issue can be solved on a Visual Studio 2015 side.

**Comment by Opiumtm** [comment]
@carstenschuette and good side of UWP platform is - .NET runtime libraries are distributed in appx package and does not shipped with a system. System only provide native COM/WinRT APIs. So, .NET Core (and related .NET Native) runtimes are independent from system libraries and shipped within appx package for UWP apps. All updates to .NET UWP part are shipped not with system, but with Visual Studio instead. It's why I complained about Visual Studio 2015 update 2 absence of much needed .NET platform fixes.

**Comment by Opiumtm** [comment]
@carstenschuette and for meaning of the "runtime" word in UWP platform. Operating system do not include **any** runtime at all. It just provide native COM/WinRT API surface and when you write apps in C++/CX it doesn't differ much from a classic Windows native COM approach. C++/CX language dialect just add some syntactic sugar for COM (Windows Runtime API is really a COM and .winmd metadata is just a standardized and restricted binary form of C++ header files). When you look at a .NET application universal windows package internals, you will see native bootstrapper .exe file which start managed runtime distributed alongside your application code. There is no system provided .NET runtime. All UWP apps **are essentially native apps**, and managed runtime is just a regular dynamic linked library referenced by bootstrapper .exe file. All system calls are native COM calls and it mapped to a managed world via runtime interop wrappers. All native system objects (including UI pages and controls) are not garbage collected, they are **reference counted** because they just regular classic COM objects with `IUnknown` interface and so on. All garbage collector magic and so called "weak handles" for COM objects are created by .NET runtime which placed just near your code in application package.

**Comment by schuettecarsten** [comment]
Maybe #812 helps a bit when the new method is called from Unloaded events of pages.

**Comment by Opiumtm** [comment]
@carstenschuette It will help a bit, but will not solve entire problem. Compiled bindings have private fields and private event handlers in generated classes which is not cleared and can not be cleared manually because these handlers and fields are private. Only option now is to manually clear view model on page object to minimize damage at least. If view model cache too many data it will turn into disaster. Retained page with direct reference to heavy view model is a certain disaster. So, to minimize damage view model on page **must** be cleared on page unload. But it is only a partial solution.

**Comment by schuettecarsten** [comment]
@Opiumtm: You're right. To minimize memory leaks, I do the following in Dispose method of ViewModel, which is called in my Page.Unloaded implementation:

``` csharp
        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        protected virtual void Dispose(bool disposing)
        {
            this.logger.Trace("Disposing...");
            if (disposing)
            {
                this.ClearPropertyChanged();

                // Clear all fields
                var fieldInfos = this.GetType().GetFields(BindingFlags.FlattenHierarchy | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                foreach (var fieldInfo in fieldInfos)
                {
                    TypeInfo fieldType = fieldInfo.FieldType.GetTypeInfo();
                    if (!fieldInfo.IsInitOnly && (fieldType.IsClass || fieldType.IsInterface || fieldType.IsArray))
                    {
                        fieldInfo.SetValue(this, null);
                    }
                }

                // Force GC
                GC.Collect(GC.MaxGeneration, GCCollectionMode.Optimized, false);
            }
        }
```

**Comment by Opiumtm** [comment]
@carstenschuette You should not use reflection here. When you compile this with .NET Native (and native compiling is required for store publication) you will get problems with reflection.
1. Implicit reflection is harmful because it will interfere with rd.xml reflection settings. If programmer choose to disable reflection in native package, he will get runtime errors. If view model is a system class or class from nuget package, reflection also should fail at runtime because by default in .NET Native compiler reflection is only enabled for classes in solution.
2. Reflection in .NET Native compiled code is slow. Very slow. You should avoid reflection by all costs.

_update: Sorry, I not understood that it's not a T10 code but your own code. Anyway, reflection in .NET Native is slow and there are complains on stack overflow about it._

**Comment by schuettecarsten** [comment]
@Opiumtm: By adding the following code to the rd.xml file, you can enable Reflection for the whole application. I know it is slow. But I have no better idea how to workaround the memory leaks.

``` xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="*Application*" Dynamic="Required All" />
  </Application>
</Directives>
```

**Comment by Opiumtm** [comment]
@carstenschuette Why you clear ViewModel fields?
This memory "semi-leaks" issue is apply only to a Page and UserControl with `{x:Bind ...}` compiled bindings. Compiled bindings classes and host Page object (because compiled bindings directly reference host Page!) retained in memory. If your Page (or UserControl) reference view model in ViewModel dependency property, view model should be retained with Page (or UserControl).
Only thing you need is to clear ViewModel property on host Page (or UserControl) object.

Compiled binding classes are clever enough to automatically remove `PropertyChanged` event handlers to your view model **if** you clear view model on Page. Compiled binding classes clean up some things **if** you manually clean view model reference on host Page. Page/UserControl (with `RoutedEventHandler` delegates and so on) and compiled binding classes still will be retained in memory, but view model should be not. Only thing you need is to manually clean view model property referenced by compiled binding!

**Comment by schuettecarsten** [comment]
@Opiumtm : Okay, I will test.

**Comment by Opiumtm** [comment]
@carstenschuette you can any time look into a _\obj\_ folder and check generated binding classes here. It's very interesting to investigate how things are working internally :smile:

**Comment by schuettecarsten** [comment]
Have you tried to update Microsoft.NETCore.UniversalWindowsPlatform to 5.1.0?

**Comment by Opiumtm** [comment]
@schuettecarsten I have filed bug on Microsoft connect about leaky compiled `{x:Bind ...}` bindings

https://connect.microsoft.com/VisualStudio/feedback/details/3077894/memory-leaks-in-c-uwp-apps-using-compiled-x-bind-bindings

This bug is still here after all Visual Studio and .NET Core updates.

**Comment by ddelapasse2** [comment]
I'm not using Template10, but I'm having the same problems discussed above in my UWP app.  Have there been any improvements in the last 6 months on these leaks?  

I am currently using x:bind to help performance and trying to avoid memory leaks by setting all allocated memory variables to null and also calling Bindings.StopTracking() but I am still leaking memory.  The VS memory profiler tool shows an increase in XamlUserType every time I leave/revisit my page.

Looks like MS closed Opiumtm's issue as not reproducible.  Would appreciate any good reference leaks or ideas on how to proceed.

**Comment by Opiumtm** [comment]
@ddelapasse2

To completely prevent memory leaks you should unsubscribe all events you have subscribed manually in code. Microsoft propose that if event handler is attached in XAML, it automatically unsubscribed on page/control unload (as XAML handling code knows what and when subscribe and unsubscribe). But if you attach events in C# code, you **should** unsubscribe manually at unloaded event handler as you have subscribed.
It's not good at all and it break .NET developer expectations, but radical solution to memory leaks problem in UWP XAML is to unsubscribe to all events you have subscribed in code (not XAML). It's because XAML controls are essentially unmanaged COM objects, and they're use reference counting instead of garbage collector. As managed GC still don't understand COM proxies as "fundamentally different kind of object" and treat them as regular managed objects, unsubscribed events would leak. Generated by Visual Studio code for XAML pages try hard to hide this issue from developer (automatic unsubscribe of events which are subscribed in XAML is generated by VS, for example), but if you do subscribe in C# code, this "leaky abstraction" do leak.
