### ISSUE TITLE
Getting "You must add a reference to assembly 'Microsoft.Xaml.Interactivity" when attempting to build unchanged template code

### ISSUE THREAD

**Issue by raifordb** [Windows-XAML/Template10#801]
Error   CS0012  The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   WindowsApp9 c:\users\raiford\documents\visual studio 2015\Projects\WindowsApp9\WindowsApp9\obj\x86\Debug\XamlTypeInfo.g.cs  1819    Active

**Comment by vlastimilmaca** [comment]
Seems like old issue with Xaml.Behaviours.Uwp version 1.1.0 ( #685  ) ... few months ago this was solved by moving everything back to version 1.0.3 but now it seems to be 1.1.0 again ... I really lost track on what is actual version supported by T10 ... it is probably somewhere half way if it is doing this again ...

**Comment by raifordb** [comment]
Yes I had to update it to 1.0.3. Thanks!

**Comment by vlastimilmaca** [comment]
@JerryNixon
As this issues is more common lately I looked a little into this ... source of problem is that Microsoft.Xaml.Behaviors removed StrongName signing from managed assembly in v1.1.0. 

This error appears because of KeyBehavior class in library, which references ActionCollection from Microsoft.Xaml.Interactivity. (T10-Signed to Behaviors-Unsigned is not allowed)

Here are some links to stackoverflow about this problem:
[How to fix “Referenced assembly does not have a strong name” error?](http://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error)
[Reference to assembly without strong name](http://stackoverflow.com/questions/6370753/reference-to-assembly-without-strong-name)
[.NET-fu: Signing an Unsigned Assembly (Without Delay Signing)](http://buffered.io/posts/net-fu-signing-an-unsigned-assembly-without-delay-signing/)

They are all pretty old and I'm not sure how this is handled in UWP now. It seems that unsigning T10 should solve this, but I don't know what it will mean for T10 users.
So I will let someone more experienced to take it from here :).

**Comment by JerryNixon** [comment]
This is irritating. Behaviors goes open source and then starts going sideways.

**Comment by Opiumtm** [comment]
@JerryNixon I think, strong naming is required for NuGet package. Library can be open source, but NuGet package is an another story - it's a binary repository and require strong naming for a particular package. Anyone can create fork of open source library and publish it independently on NuGet with another strong name.

**Comment by vlastimilmaca** [comment]
@JerryNixon @Opiumtm 
Chmm .. I just run into this bug https://github.com/Microsoft/XamlBehaviors/issues/96 ... which is bug of behaviors and was fixed in version 1.1.0 and it is really bad bug ... I think this update is really needed to happen.

**Comment by vlastimilmaca** [comment]
@Opiumtm In that case I'm missing something and my previous observation might be wrong... How did they manage to make v1.1.0 without strong name(changelog says they removed StrongName signing form DLLs) and still make a NuGet package for version 1.1.0?

**Comment by dubstylee** [comment]
@vlastimilmaca yeah, the 1.1.0 version fixed some issues I was having, but I'm currently stuck at 1.0.3 to be able to work properly with Template 10. Hoping that they play nice together soon!

**Comment by JerryNixon** [comment]
Updated in latest Nuget (today)
