### ISSUE TITLE
How to pass parameters back to previous page?

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#808]
I'm porting an app from Android and I'm trying to use Template10 as a foundation but have stumbled upon something a bit troublesome.

In Android it seems pretty common to simply push a "page" onto the stack without actually using a NavigationService, meaning that the instance of this page is created on the original page and hence can be constructed with parameters (such as callbacks to original page) which in turn can be used to modify the original page properties and content.

I've successfully implemented a similar behavior when using the standard UWP NavigationService, simply by passing a ICommand instance as parameter when navigating, and invoking that command on the called page, allowing it to modify the content on the original page.

However, due to the serialization mechanics of Template10's navigation service, it's not possibly since I can't deserialize a Command properly.

I see three options:

1) Use a singleton pattern on the pages I want to modify properties of, allowing other pages to check for a valid instance and then calling Commands or other methods on that instance.
2) Change the serialization mechanism of Template10 (suggested in another issue I noticed).
3) Try to bypass the navigation service mechanism of Template10.

Any suggestions or am I missing some obvious functionality that could allow for this to work?

/Johan

**Comment by JerryNixon** [comment]
Well, it's a messy thing that you are wanting to accomplish, but you can do it with Template 10 with the following pieces and parts...
1. You will need to change the NavigationCacheMode to Required. This will ensure your previous page is not taken out of memory when you navigate away (which is the default). 
2. Since you want to Nav back and not re-Nav (forward), just accept that you simply cannot pass a parameter with the Back operation. You do, however, get an OnNavTo in your T10 view-model.
3. Save the non-serializable stuff in SessionState (which is a property of your view-model). The changes you want can be delegates (which is crazy, but should work) or just properties, which you handle in OnNavTo when NavMode is Back. 

Does this make sense?

**Comment by JerryNixon** [comment]
It's worth pointing out that a singleton View is 100% impossible. A singleton view-model would be possible, but again, a little wonky and might make your life harder than it needs to be.

**Comment by JerryNixon** [comment]
I want to mention that changing the serialization requirement of the T10 NavService would result in breaking your ability to properly restore from a suspend+termination event. That's not a T10 artifact, by the way, it's how the Frame state works in UWP.

**Comment by johanlindfors** [comment]
Thank you @JerryNixon! Much appreciated and I'll investigate the leverage of SessionState, never though about that!

**Comment by AmitBhatnagar24** [comment]
I have come across this issue too and while I did manage to solve this by allowing my ViewModels to be singleton and fire off a Message to the previous page's VM. This worked OK for me. 

I often wondered if it is possible / useful if OnNavTo was provided the key/type of the previous page. This would allow for a bit neater use of SessionState

**Comment by JerryNixon** [comment]
You can infer the Key/Type of the previous page by using the BackStack and ForwardStack in concert with the NavMode passed to OnNavTo.
