### ISSUE TITLE
TimeoutAction not closing AttachedFlyout

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#823]
I'm using this code to bind a `Command` to `Grid.Tapped` event and, after executing the `Command`, I'd like to show a `Flyout` for just 1s. The `Flyout` is shown but it doesn't hide.
Here's my code:

```
<FlyoutBase.AttachedFlyout>
    <Flyout>
        <TextBlock Text="copied" />
    </Flyout>
</FlyoutBase.AttachedFlyout>

<interactivity:Interaction.Behaviors>
    <core:EventTriggerBehavior EventName="Tapped">
        <core:InvokeCommandAction Command="{Binding CopyCommand}" />
        <behaviors:OpenFlyoutAction />
        <behaviors:TimeoutAction Millisecndos="1000">
            <behaviors:CloseFlyoutAction />
        </behaviors:TimeoutAction>
    </core:EventTriggerBehavior>
</interactivity:Interaction.Behaviors>
```

**Comment by JerryNixon** [comment]
Is it because you have misspelled "Milliseconds"?

**Comment by JerryNixon** [comment]
No, now I see the problem. It is because those actions hunt up the Visual Tree and because they are outside the branch that has the Flyout they cannot find it. I have updated the behavior to have a new TargetObject property to allow you to push it into the visual tree you want. It will be part o the next NuGet update. Thanks.

**Comment by Gh0s7** [comment]
Misspelling is related to my VM failing with copy&paste, so I rewrote it here and I messed up. I'm glad that you fixed that, thanks for your work :+1:
