### ISSUE TITLE
Prevent saving/restoring navigation history?

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#83]
Is there an easy way to prevent saving and/or restoring of navigation history?  I want to use the navigation service, but I'd like my app to start at the home screen every time.
Thanks!
Brad.

**Comment by JerryNixon** [comment]
Yes, this is very simple. In your app.xaml.cs constructor put the following line:

``` c#
CacheMaxDuration = TimeSpan.Zero;
```

This will, basically, disable all suspend/resume caching. Which is what you are asking to accomplish. This, by the way, is a very reasonable thing to do in an app. 

> Docs: https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Cache

I am sure you can see, we have a little work to do in order to document how to accomplish this. Thanks for the question @plettb.

**Comment by JerryNixon** [comment]
By the way, if you wanted to contribute to the WIKI page, you are welcome to help out.

**Comment by plettb** [comment]
LOL!  Thanks a lot!

I actually wouldn't mind helping with this project, but I simply don't have the time at present.

Brad.
