### ISSUE TITLE
HamburgerMenu requires AccentColor

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#858]
There are several style properties to the HamburgerMenu, even more now with 1.1.10. those need to be individually set, or a developer can set them all at once using the AccentColor property of the control. If, however, a developer does not supply any of those values, the initial HamburgerMenu is transparent, like Wonder Woman's jet. 

This could be called a feature, but it's not the intended behavior. In the past, it has defaulted to SteelBlue, and even SystemColor in recent versions. Because dragging the HamburgerMenu is not an important use case, this didn't get tested. But, it should be resolved, and this is the work item for it. 

The plan, right now, will be to use SteelBlue.

**Comment by 1iveowl** [comment]
Is this why the menu now look dark gray instead of light gray and the top bar is white/transparent"?

 I'm only using the light theme for this particular app.

I've tried to add `HamburgerBackground="SteelBlue"` to `controls:HamburgerMenu` but that does not change the color of the menu back to where it was.

My Hamburger menu now looks like this.
![hamburger colours](https://cloud.githubusercontent.com/assets/12871120/14737647/7018eec0-087d-11e6-8847-9ade4500c890.png)

How do fix the white top bar of the menu and turn it into the right kind of blue again? :-) 

It used to look like this before the upgrade to 1.1.10:
![hamburger colours - as it was](https://cloud.githubusercontent.com/assets/12871120/14737756/01d7690e-087e-11e6-9f89-6342be04cbc8.png)

**Comment by mitchcapper** [comment]
This is not causing that but the default theming has changed.  There are a lot of color options that can be set on the menu (per the samples).

**Comment by 1iveowl** [comment]
Thank you. 

I've played around with a lot of them, but I've yet to find the one that fixes the white bar? A more specific lead would be much appreciated ;-)

**Comment by 1iveowl** [comment]
One more observation. If the user changes the size width of the App and then drags it out to wide again the top bar turns from white into steelblue - i.e. thing look correct after this narrow-back-to-wide motion.

**Comment by mitkodi** [comment]
You can fix it (temporary until it's fixed in library) by adding the following in your shell page:

``` javascript
    var shellSplitView = XamlUtils.AllChildren<SplitView>(MyHamburgerMenu).FirstOrDefault();
    if (shellSplitView != null)
        shellSplitView.PaneBackground = MyHamburgerMenu.AccentColor.ToSolidColorBrush(); // or some other color

```

In library, it could be fixed if in **HamburgerMenu.xaml** **ShellSplitView.PaneBackground** is bound to a property instead to be set as Transparent.

**Comment by 1iveowl** [comment]
Thank you mitkodi! Yes, this work-around works.

**Comment by JerryNixon** [comment]
The desired behavior is that the HeaderContent area has the background color matching that of the HamburgerButton. This can be overcome by setting the HeaderContent background (in your own content). In addition, the Pane MUST be set to Transparent, that is a bug. Fixed now.

**Comment by johanlindfors** [comment]
May I suggest that the [documentation](https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Controls#hamburgermenu) also gets updated with this mandatory explicit styling of setting the AccentColor? I had to search the issues to realize what's causing the transparent behavior of it...
