### ISSUE TITLE
HamburgerButton is visible while IsFullScreen=true

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#859]
There is a bug that leaves the HamburgerButton visible even when the HamburgerMenu is set to IsFullScreen=true. This is is not the property behavior. 

Fixed in GitHub.

**Comment by 1iveowl** [comment]
Is this why the menu now look dark gray instead of blue when using the light theme ? ;-)

I've tried to add `HamburgerBackground="SteelBlue"` to `controls:HamburgerMenu` but that does not change the color of the menu back to where it was.

My Hamburger menu now looks like this. I'm using only the light theme for this app. 
![hamburger colours](https://cloud.githubusercontent.com/assets/12871120/14737647/7018eec0-087d-11e6-8847-9ade4500c890.png)

How do I get it back to where is was? :-)

**Comment by schuettecarsten** [comment]
See https://github.com/Windows-XAML/Template10/pull/873, this should fix the issue.

**Comment by JerryNixon** [comment]
Leave a comment

**Comment by schuettecarsten** [comment]
Ok, you used Opacity. :)
