### ISSUE TITLE
Question: Would you consider Views.Shell as a special case for MVVM?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#912]
**Views.Shell**, as we already know, is a special view which is hosting the **HamburgerMenu** and, once loaded,  it stays for the lifetime of the app. It can also conveniently host other app-wide views, for instance, as shown in Samples with Search and Login utilities thru a ModalDialog control.

The MVVM purist approach tells me that I shouldn't reference anything in a view class from a ViewModel, but I see no strong reason for doing so for the special case of **Views.Shell**. I find it convenient (but see no pressing downside) to refer to methods and properties in Views.Shell from other ViewModels, for instance for timed logout management (e.g., login dialog from Views.Shell  displayed on idle timeout; authenticated flag conveniently provided as a property with a login dialog, and so on). I am not suggesting a loose approach to Views.Shell but the use cases are usually limited to ViewModels for **MainPage** (for startup config) and SettingsPage (for user option setting).

Saying all that, I can avoid Views.Shell altogether but at a cost of _code-bloat_, and ask myself, why when View.Shell is _in situ_ for the lifetime of the app?

What do you think? Should I avoid Views.Shell from ViewModels, and if so why?

**Comment by darenm** [comment]
At the risk of stumbling into a political/religious debate here... I believe a certain degree of pragmatism is often called for when building non-trivial apps. Is the maintainability of an app truly enhanced by creating a ShellService abstraction which brokers shell oriented functions between a ViewModel and the Views/Shell instance? Does Shell.Instance.ShowBusy() really impact your app and it's maintenance? The key here is to consider _your_ scenario, not a purist abstraction for a theoretical app. If, in your app, you are aiming for significant test coverage, the need to inject mock Shell instances to test responses to signals, etc. then the service abstraction is essential and you get a gold star for purist architecture. If, however, YAGNI (you ain't gonna need it) then why suffer the code bloat and inherent maintenance? I often allow some view references to creep into my ViewModels unless I have a compelling reason not to. Elements such as the MapControl, are unfriendly to simple integration activities from the ViewModel so pragmatism and a desire to solve the problem at hand, rather than to perform an exercise in architecture, lead me to reference the MapControl in the ViewModel. Could I solve it through abstraction? Yes - but I have yet to find a compelling need to do so. YMMV :)

**Comment by dg2k** [comment]
Exactly my thoughts @darenm and thank you for taking the time to share your thoughts.

I am encouraged by Views.Shell being loaded throughout the app lifetime (in contrast to other pages getting loaded and unloaded, may be cached but ...) and as you indicate with your own MapControl  example, I see numerous similar features easily implemented in Views.Shell, for instance, status bar message display, login control, search, etc. It just feels unconvincing to abstract the interaction between Views.Shell and ViewModels for the sake of adhering to the ideal MVVM with little or no tangible gain than a more pragmatic approach.
