### ISSUE TITLE
A thought for Discussion: Rename Shell to AppShell?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#93]
With Shell.xaml now at the heart of the Hamburger Menu (as the root visual) we'll no doubt see more reference code like Views.Shell.SetBusyIndicator() (as used to show the busy ring on Settings page). I have just implemented error and status notifications (in preference to popup dialogs, which I intend to share this with a pull request) so I have references like Views.Shell.NotifyErrorMessage("error message to show") and Views.Shell.NotifyStatusMessage("status message to show").

This is obviously a matter of opinion and getting used to, but the reference "Views.Shell" just looks a bit far-removed. Compare this with "Views.AppShell" and feels closer to home; we're referring to the app's own shell class.

If this makes sense to most of you, this is to request for renaming of Shell as AppShell. Any thoughts?

**Comment by JerryNixon** [comment]
We've already been talking about this. We are thinking of the following, possible new controls:
1. Template10.Controls.Shell
   - Property Shell.Modals : List where T: IModal
   - Method Shell.ShowModal(params[]) where T: IModal
   - Method Shell.HideModal() where T: IModal
   - Template10.Controls.IModal
   - Template10.Controls.BusyModal : IModal
   - Template10.Controls.LoginModal (potential) : IModal
   - Template10.Controls.ErrorsModal (potential) : IModal
2. Template10.Controls.HamburgerShell : Shell
   - HamburgerShell.HeaderContent
   - HamburgerShell.PrimaryCommands
   - HamburgerShell.SecondaryCommands
3. Template10.Controls.TabShell : Shell
   - TabShell.HeaderContent
   - TabShell.Commands

The idea is, we are building some nice functionality into Shell that is very valuable with or without the Hamburger. Also, we want to build a pivot interface because the request for it is growing.

As far as calling it AppShell, there's nothing stopping us from doing that. Though I like to name things with as simple names as possible. I am open to the idea and have read your points.

We're also considering making the AppShell (as you call it) a property off Bootstrapper with the assumption that an app would only use one (primary) shell and you could access it, then, with BootStrapper.Current.Shell or something like that. Again, just starting to consider that one.

**Comment by dg2k** [comment]
Obviously there is much more thought to the naming idea than my rather simplistic one. I am quite content that the need for naming is in existence already which means hopefully more logical names will evolve and arrived at in a wider context Jerry has just outlined.
