### ISSUE TITLE
Template10.Validation Library

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Windows-XAML/Template10#951]
Hi, in #678 Template10.Validation Library is marked (Maybe).

Why so? 

Is there any chance for RS1 XAML to include validation natively?

**Comment by JerryNixon** [comment]
The validation library is not completely serializable at this time. If you would like to fix that, it's the only missing piece to having it a full member of the family. I say _you_ because I am currently busy with other things. I wrote the validation library, so I certainly don't want to throw it away, but I don't have time to focus on it right now.

**Comment by MichaelPetrinolis** [comment]
Unfortunately neither do I, at least not for now.
