### ISSUE TITLE
Could not load file or assembly Microsoft.Xaml.Interactivity...

### ISSUE THREAD

**Issue by SamuelLioult** [Windows-XAML/Template10#960]
Hi,
I've updated the template10 package to version 1.1.10 in the Hamburger Template from the latest version of the Template10 extension and I have this issue again. My project.json is the same that Jerry Nixon :
`{
    "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.*",
    "Newtonsoft.Json": "8.0.3",
    "Template10": "1.1.*"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}`

I have re-builded and restarted VS.
My app runs well but I can't change the hamburger color (for example) because I have the famous warning the Shell.xaml.
This works well with latest version of Template10 and latest version of Microsoft.Xaml.Behaviors.Uwp.Managed

Thanks for help ;-)

**Comment by johanlindfors** [comment]
Do you still get this error even when specifying x64 as target platform?

**Comment by SamuelLioult** [comment]
Hi @johanlindfors,
thank you for responsiveness!
Indeed it seems that the warning is not displayed well. Should I consider it normal?
However, the color change appears to be broken. 
I tried this:
`<Controls:HamburgerMenu x:Name="MyHamburgerMenu" NavButtonCheckedBackground="Green">`

**Comment by JerryNixon** [comment]
@SamuelLioult you should not consider it as normal. This problem is a result of the Behaviors SDK changing from being strong-named to not being strong-named, while Template 10 remains strong-named. At least in the version you are using. Later today a new version of Template 10 (version 1.1.11) will be released to NuGet and will resolve this by removing strong-name from Template 10. In the meanwhile, @johanlindfors has given you a fine workaround - but it's worth noting that the XAML designer typically does not work when you specify x64. One thing leads to another. Anyway, the current 1.1.10 should help you a lot already, but 1.1.11 which is forthcoming will help you more.
