### ISSUE TITLE
Save navigation between sessions

### ISSUE THREAD

**Issue by ephracis** [Windows-XAML/Template10#967]
I am using the Hamburger template and noticed that every time I start the app it defaults to the same place. I would like it to remember my navigation between sessions, preferably in the roaming settings store, so when I reopen the app it loads right back to where it was when I closed it.

**Comment by dg2k** [comment]
Isn't this something that the developer should implement?

**Comment by ephracis** [comment]
Sounds reasonable. Perhaps you could nudge me in the right direction on where to put such code? :smile:

**Comment by NewBLife** [comment]
save your app data use suspensionState in viewmodel.OnNavigatedFromAsync method,and restore your app data use suspensionState in viewmodel.OnNavigatedToAsync method.

[template10 sample]
https://github.com/NewBLife/UWP/blob/master/MvvmDemo/FileOperationDemo/ViewModels/MainPageViewModel.cs

**Comment by JerryNixon** [comment]
There are a few things you will want here.

If you are going to manually handle restoring the navigation state, then you are going to want to disable the automatic handling of the navigation state setting BootStrapper.EnableAutoRestoreAfterTerminated to false. Please note that this property is new in the GitHub source, and can only be found in NuGet when accessing the preview versions of T10.

Next, you need to handle the suspending event in your app. The good news is that when your app is closing, it is also suspending, so you don't need to handle two events. Just override the BootStrapper.OnSuspendingAsync() method in your app.xaml.cs.

Next, you want to save the navigation state. The navigation state is accessible from the BootStrapper.NavigationService.NavigationState property. Please note that this property is new to T10 in the GitHub code, and has not yet even made it to the preview NuGet editions. A temporary workaround is to use BootStrapper.NavigationService.FrameFacade.GetNavigationState() but I am planning on making the property off NavigationService the primary access - but that will not be for several versions from now, so you are safe using either one. 

Next, you will get the string from the NavigationState property or method, and you need to save it. Using the Windows.Storage.ApplicationData.Current.RoamingSettings.Values["NavState"] = x; Here's a word of warning. Saving to a setting has a 6k limit. This means that if you have a large NavState then it's possible this will fail. The fall-back solution is to save it as a file. The easiest way to do this is to use the Template10.Services.FileService.FileHelper which has a simple method called WriteFileAsync<T>(key, T) that can persist the state for you.

Finally, you need to restore state. You can simply handle this in your OnStartAsync. Typically, OnStartAsync is not called when resuming from Terminated, but because you will have set EnableAutoRestoreAfterTerminated to false, then this behavior has been short-circuited. This means, it is up to you to test if the navigation state needs to be restored or not. Once you have determined this, you can then set BootStrapper.NavigationState to the value in settings or in the file you saved. Just use the read alternatives of how you saved the state in the first place.

Next time, this type of question is best served on Stack Overflow. :) Later.

**Comment by ephracis** [comment]
Thanks a lot for the answer.

My OnStartAsync in App.xaml.cs previously called `NavigationService.Navigate(typeof(Views.DashboardPage))`. I have replaced it with setting `NavigationService.NavigationState` as you recommended and the app now returns to the previous view at startup, with the whole stack of previous states so I can use the back button and everything.

But there's one drawback: the hamburger menu doesn't seem to be aware of the navigation state at startup. There is no indicator (white line to the left of the text) on the item that is currently active. I guess that this comes from removing the call to `NavigationService.Navigate()`.

What do I need to do to get this back?
