### ISSUE TITLE
"Show telemetry in the Windows Dev Center" checkbox does not work with Template 10?

### ISSUE THREAD

**Issue by resolutedreamer** [Windows-XAML/Template10#988]
Hi, I am using Template 10 for the first time, and it seems like if I check this checkbox
![image](https://cloud.githubusercontent.com/assets/3419924/15384620/c65b3f30-1d50-11e6-92a6-c68d7f9c7dbd.png)
none of the Templates seem to work. If I uncheck the box they work fine. I am using Visual Studio 2015 Update 2.
Thanks!

**Comment by mvermef** [comment]
Correct, it doesn't take check box into account, already been reported

**Comment by JerryNixon** [comment]
Hey @resolutedreamer, the way the Telemetry wizard is implemented, it simply is not properly compatible with custom project templates. That being said, nothing is stopping you from creating a quick Blank project and copying the three or four lines from it into your Template 10 project. That's what I do, and, honestly, I prefer doing it that way because I know what's being added to my project.

**Comment by resolutedreamer** [comment]
Thanks for the suggestions! Maybe a note about this could be added to the docs? I didn't see anything about it this while browsing them.

**Comment by JerryNixon** [comment]
Where would you look to see it? You might edit the Wiki to make it most clear?
