### ISSUE TITLE
Visual Studio 15 Support

### ISSUE THREAD

**Issue by baqwas** [Windows-XAML/Template10#997]
Any plans to make this template an integral part of the Visual Studio 15 experience sooner rather than later? Thanks.

**Comment by dg2k** [comment]
Is it not an integral part of Visual Studio 15 already?

You can install Visual Studio Extension of Template 10 -- [Template 10 Template Pack](https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5?SRC=VSIDE) from Visual Studio Gallery. Better still, within VS you can just reach for **Tools** -> **Extension and Updates** and tap on **Online** in the left margin and type **t10** in the search box. You should find **Template 10 Template Pack** in full glory.

You can also add Template 10 to a project with project **References -> Manage NuGet Packages..** as another option.

I don't know what's more integral than this.

**Comment by baqwas** [comment]
Can reproduce the suggestion in Visual Studio 2015.

Cannot reproduce the suggestion in Visual Studio 15 Preview 2.

Regards.

**Comment by dg2k** [comment]
Sorry, this Issue thread is closed, but responding regardless just if it helps ...

I take it by _Preview 2_ you mean _Update 2_?

If you installed Visual Studio 2015 (with or without _Update 2_) and you've a network connection, just check out the menu command **Tools** -> **Extension and Updates** and tap on **Online** in the left margin and type **t10** in the search box. Instead of the short name **t10**, you can type in the full name **Template10**.

If Visual Studio 2015 is installed properly and network connection is there, you should be able to reproduce what I suggested above without any problem. Hope this helps.

**Comment by mvermef** [comment]
He really did mean preview 2, visualstudio.com/en-us/news/releasenotes/vs15/vs15-relnotes

**Comment by dg2k** [comment]
Thanks @mvermef for the note.

Didn't expect a new update of Visual Studio 2015 is in the offing, when **Update 2** is just weeks old.

Interesting text [in there](https://www.visualstudio.com/en-us/news/releasenotes/vs15/vs15-relnotes): **This is an unsupported pre-release version of Visual Studio ...**
That says a lot and perhaps @baqwas is having an issue to do a new product?? Something to look into ...

Thanks again @mvermef.

**Comment by baqwas** [comment]
Sorry to belabor the point. My sincere apologies. Please consider the issue as closed.

We are talking at cross purposes:

·         I was simply trying to point out that the search for “t10” under Visual Studio 15 Preview 2 does not yield the expected results.

·         You are persisting in reassuring me that the search for “t10” in Visual Studio 2015 works. I concede this fact since I have done so successfully (w/ and w/o Updates). This is precisely why I logged the issue not recognizing that there is limited support by Visual Studio 15 Preview issues. My fault. Apologies again.

Perhaps there will be a new name for Visual Studio 15 prior to RTM.

Regards.

I take it by "Preview 2" you mean "Update 2". No!
